SoundFiles_Names = {
"Cinematics - DSI Act1",
"Cinematics - DSI Act2",
"Cinematics - DSI Act3",
"Cinematics - DSI Act4",
"Cinematics - Goblin",
"Cinematics - Logo",
"Cinematics - MOP ASL",
"Cinematics - MOP BR",
"Cinematics - MOP GSE",
"Cinematics - MOP HSL",
"Cinematics - MOP JADE CRASH",
"Cinematics - MOP JADE",
"Cinematics - MOP WRA",
"Cinematics - MOP WRH",
"Cinematics - ORO Alliance",
"Cinematics - ORO Horde",
"Cinematics - Worgen",
"Cinematics - WOW FotLK",
"Cinematics - WOW Intro BC",
"Cinematics - WoW Intro LK",
"Cinematics - WoW Intro MOP",
"Cinematics - WOW Intro",
"Cinematics - WOW Wrathgate",
"Cinematics - WoW3X Intro",
"Cinematic Voices - BloodElfNarration",
"Cinematic Voices - DeathKnightNarration",
"Cinematic Voices - DraeneiNarration",
"Cinematic Voices - DwarfNarration",
"Cinematic Voices - GnomeNarration",
"Cinematic Voices - GoblinNarration",
"Cinematic Voices - HumanNarration",
"Cinematic Voices - MaelstromNarration",
"Cinematic Voices - NightElfNarration",
"Cinematic Voices - OrcNarration",
"Cinematic Voices - PANDARENNARRATION",
"Cinematic Voices - TaurenNarration",
"Cinematic Voices - TrollNarration",
"Cinematic Voices - UndeadNarration",
"Cinematic Voices - WorgenNarration",
"Cataclysm - faeriedragon 01",
"Cataclysm - ZA altarbloodgod 01",
"Cataclysm - ZA altarbloodgod 02",
"Cataclysm - ZA altarbloodgod 03",
"Cataclysm - ZA bethekk 01",
"Cataclysm - ZA bethekk 02",
"Cataclysm - ZA cacheofmadness 01",
"Cataclysm - ZA cacheofmadness 02",
"Cataclysm - ZA devilsterrace 01",
"Cataclysm - ZA devilsterrace 02",
"Cataclysm - ZA mandokir 01",
"Cataclysm - ZA mandokir 02",
"Cataclysm - ZA templebethek 01",
"Cataclysm - ZA templebethek 02",
"Cataclysm - ZA terracedevils 01",
"Cataclysm - ZA terracedevils 02",
"Cataclysm - ZA thecoil 01",
"Cataclysm - ZA thecoil 02",
"Cataclysm - DruidsoftheFlameA Hero 01",
"Cataclysm - DruidsoftheFlameA 01",
"Cataclysm - DruidsoftheFlameA 02",
"Cataclysm - DruidsoftheFlameA 03",
"Cataclysm - DruidsoftheFlameB Hero 01",
"Cataclysm - DruidsoftheFlameB 01",
"Cataclysm - DruidsoftheFlameB 02",
"Cataclysm - DruidsoftheFlameB 03",
"Cataclysm - Elemental AirA 01",
"Cataclysm - Elemental AirA 02",
"Cataclysm - Elemental AirB 01",
"Cataclysm - Elemental AirB 02",
"Cataclysm - Elemental AirC 01",
"Cataclysm - Elemental AirD 01",
"Cataclysm - Elemental AirD 02",
"Cataclysm - Elemental EarthA 01",
"Cataclysm - Elemental EarthA 02",
"Cataclysm - Elemental EarthA 03",
"Cataclysm - Elemental EarthA 04",
"Cataclysm - Elemental Water Ambient 01",
"Cataclysm - Elemental WaterA UD01",
"Cataclysm - Elemental WaterA UN01",
"Cataclysm - Elemental WaterB UD01",
"Cataclysm - Elemental WaterB UN01",
"Cataclysm - Elemental WaterC UD01",
"Cataclysm - Elemental WaterC UN01",
"Cataclysm - ElementalBondsA 01",
"Cataclysm - ElementalBondsA 02",
"Cataclysm - ElementalBondsA 03",
"Cataclysm - ElementalBondsB 01",
"Cataclysm - ElementalBondsB 02",
"Cataclysm - FirelandsA Hero 01",
"Cataclysm - FirelandsA 01",
"Cataclysm - FirelandsA 02",
"Cataclysm - FirelandsA 03",
"Cataclysm - FirelandsB Hero 01",
"Cataclysm - FirelandsB 01",
"Cataclysm - FirelandsB 02",
"Cataclysm - FirelandsB 03",
"Cataclysm - FirelandsB 04",
"Cataclysm - ThrallAggraA ED01",
"Cataclysm - ThrallAggraA EN01",
"Cataclysm - ThrallAggraB ED01",
"Cataclysm - ThrallAggraB EN01",
"Cataclysm - ThrallAggraC EU01",
"Cataclysm - ThrallAggraC EU02",
"Cataclysm - CorruptedDragonblight 01",
"Cataclysm - CorruptedDragonblight 02",
"Cataclysm - CorruptedDragonblight 03",
"Cataclysm - DeathwingCorruption 01",
"Cataclysm - DeathwingCorruption 02",
"Cataclysm - DeathwingCorruption 03",
"Cataclysm - DeathwingCorruption 04",
"Cataclysm - DeathwingCorruption 05",
"Cataclysm - DeathwingCorruption 06",
"Cataclysm - DeathwingCorruption 07",
"Cataclysm - DeathwingOutro 01",
"Cataclysm - DeathwingsFall Hero 01",
"Cataclysm - DeathwingsFall 01",
"Cataclysm - DeathwingsFall 02",
"Cataclysm - DragonSoulA Hero 01",
"Cataclysm - DragonSoulA Moment 01",
"Cataclysm - DragonSoulA Moment 02",
"Cataclysm - DragonSoulA Moment 03",
"Cataclysm - DragonSoulA Moment 04",
"Cataclysm - DragonSoulB 01",
"Cataclysm - DragonSoulB 02",
"Cataclysm - DragonSoulB 03",
"Cataclysm - FangsOfTheFatherA Hero 01",
"Cataclysm - FangsOfTheFatherA 01",
"Cataclysm - FangsOfTheFatherA 02",
"Cataclysm - FangsOfTheFatherA 03",
"Cataclysm - FangsOfTheFatherB 01",
"Cataclysm - FangsOfTheFatherB 02",
"Cataclysm - FangsOfTheFatherB 03",
"Cataclysm - FangsOfTheFatherC Hero 01",
"Cataclysm - FangsOfTheFatherC 02",
"Cataclysm - FangsOfTheFatherC 03",
"Cataclysm - FangsOfTheFatherC 04",
"Cataclysm - Gunships Hero 01",
"Cataclysm - Gunships Stinger 01",
"Cataclysm - Gunships Stinger 02",
"Cataclysm - Gunships Stinger 03",
"Cataclysm - Gunships Stinger 04",
"Cataclysm - Gunships 01",
"Cataclysm - Gunships 02",
"Cataclysm - Gunships 03",
"Cataclysm - Gunships 04",
"Cataclysm - NightWalk 01",
"Cataclysm - NightWalk 02",
"Cataclysm - NightWalk 03",
"Cataclysm - NightWalk 04",
"Cataclysm - ThrallEarthWarder 01",
"Cataclysm - ThrallEarthWarder 02",
"Cataclysm - ThrallEarthWarder 03",
"Cataclysm - ThrallEarthWarder 04",
"Cataclysm - TwilightsHammer 01",
"Cataclysm - TwilightsHammer 02",
"Cataclysm - Warships Hero 01",
"Cataclysm - Warships 01",
"Cataclysm - Warships 02",
"Cataclysm - WellOfEternity Hero 01",
"Cataclysm - WellOfEternity 01",
"Cataclysm - WellOfEternity 02",
"Cataclysm - WellOfEternity 03",
"Cataclysm - WellOfEternity 04",
"Cataclysm - WellOfEternity 05",
"Cataclysm - WellOfEternity 06",
"Cataclysm - ZinAzshari Hero 01",
"Cataclysm - ZinAzshari 01",
"Cataclysm - ZinAzshari 02",
"Cataclysm - ZinAzshari 03",
"Cataclysm - ZinAzshari 04",
"Cataclysm - ZinAzshari 05",
"Cataclysm - ZinAzshari 06",
"Cataclysm - AdventureA Hero 01",
"Cataclysm - AdventureA Moment 01",
"Cataclysm - AdventureA Moment 02",
"Cataclysm - AdventureA Moment 03",
"Cataclysm - AdventureA Moment 04",
"Cataclysm - AdventureA 01",
"Cataclysm - AdventureA 03",
"Cataclysm - AdventureA 04",
"Cataclysm - AdventureA 05",
"Cataclysm - AdventureA 06",
"Cataclysm - Aftermath 01",
"Cataclysm - Aftermath 02",
"Cataclysm - Aftermath 03",
"Cataclysm - Aftermath 04",
"Cataclysm - AllianceHero 01",
"Cataclysm - ArathiHighlandsA GD01",
"Cataclysm - ArathiHighlandsA GN01",
"Cataclysm - ArathiHighlandsA GN02",
"Cataclysm - ArathiHighlandsB GD01",
"Cataclysm - ArathiHighlandsB GN01",
"Cataclysm - ArathiHighlandsB GN02",
"Cataclysm - ArathiHighlandsC GD01",
"Cataclysm - ArathiHighlandsC GN01",
"Cataclysm - ArathiHighlandsC GN02",
"Cataclysm - Azshara GD01",
"Cataclysm - Azshara GN01",
"Cataclysm - BarrowDens GU01",
"Cataclysm - BarrowDens GU02",
"Cataclysm - BarrowDens GU03",
"Cataclysm - BarrowDens GU04",
"Cataclysm - BarrowDens GU05",
"Cataclysm - BurningSteppes GU01",
"Cataclysm - BurningSteppes GU02",
"Cataclysm - BurningSteppes GU03",
"Cataclysm - BurningSteppes GU04",
"Cataclysm - Cataclysm UD07",
"Cataclysm - Cataclysm UN08",
"Cataclysm - Cataclysm UN09",
"Cataclysm - Cataclysm 01",
"Cataclysm - Cataclysm 02",
"Cataclysm - Cataclysm 03",
"Cataclysm - Cataclysm 04",
"Cataclysm - Cataclysm 05",
"Cataclysm - Cataclysm 06",
"Cataclysm - ChoGall E01",
"Cataclysm - ChoGall E02",
"Cataclysm - ChoGall E03",
"Cataclysm - ChoGall E04",
"Cataclysm - ColdMountain GU01",
"Cataclysm - ColdMountain GU02",
"Cataclysm - ColdMountain GU03",
"Cataclysm - ColdMountain GU04",
"Cataclysm - ColdMountain GU05",
"Cataclysm - ColdMountain GU06",
"Cataclysm - ColdMountain GU07",
"Cataclysm - ColdMountain GU08",
"Cataclysm - Crypt 01",
"Cataclysm - Cursed 01",
"Cataclysm - Cursed 02",
"Cataclysm - Cursed 03",
"Cataclysm - Cursed 04",
"Cataclysm - Cursed 05",
"Cataclysm - Cursed 06",
"Cataclysm - Cursed 07",
"Cataclysm - Cursed 08",
"Cataclysm - Cursed 09",
"Cataclysm - Cursed 10",
"Cataclysm - Cursed 11",
"Cataclysm - Cursed 12",
"Cataclysm - DarkEvent E01",
"Cataclysm - DarkIronforge GU01",
"Cataclysm - DarkIronforge GU02",
"Cataclysm - DarkIronforge GU03",
"Cataclysm - DarkIronforge GU04",
"Cataclysm - DarkIronforge GU05",
"Cataclysm - DarkIronforge GU06",
"Cataclysm - DarkIronforge GU07",
"Cataclysm - DarkwhisperGorge GU01",
"Cataclysm - DarkwhisperGorge GU02",
"Cataclysm - Darnassus GI01",
"Cataclysm - Darnassus GI02",
"Cataclysm - Deepholm GU01",
"Cataclysm - Deepholm GU02",
"Cataclysm - DeepholmEvent E01",
"Cataclysm - DeepholmEvent E02",
"Cataclysm - DurotarA GU01",
"Cataclysm - DurotarA GU02",
"Cataclysm - DurotarA GU03",
"Cataclysm - DurotarB GU01",
"Cataclysm - DurotarB GU02",
"Cataclysm - DurotarB GU03",
"Cataclysm - DurotarB GU04",
"Cataclysm - DurotarC GU01",
"Cataclysm - DurotarC GU02",
"Cataclysm - DurotarC GU03",
"Cataclysm - DurotarC GU04",
"Cataclysm - DurotarD GU01",
"Cataclysm - DurotarD GU02",
"Cataclysm - Elemental 01",
"Cataclysm - Elemental 02",
"Cataclysm - Elemental 03",
"Cataclysm - Elemental 04",
"Cataclysm - Elemental 05",
"Cataclysm - Elemental 06",
"Cataclysm - Elemental 07",
"Cataclysm - EyeOfTheVortex GU01",
"Cataclysm - EyeOfTheVortex GU02",
"Cataclysm - EyeOfTheVortex GU03",
"Cataclysm - Feralas GU01",
"Cataclysm - Feralas GU02",
"Cataclysm - Feralas GU03",
"Cataclysm - Feralas GU04",
"Cataclysm - Feralas GU05",
"Cataclysm - Feralas GU06",
"Cataclysm - Feralas GU07",
"Cataclysm - Feralas GU08",
"Cataclysm - Fire 01",
"Cataclysm - Fire 02",
"Cataclysm - Firelands GU01",
"Cataclysm - FlowerAura EU 01",
"Cataclysm - Ghosts 01",
"Cataclysm - Ghosts 02",
"Cataclysm - Ghosts 03",
"Cataclysm - GilneasEvent E01",
"Cataclysm - GilneasEvent E02",
"Cataclysm - GilneasEvent E03",
"Cataclysm - GilneasEvent E04",
"Cataclysm - Goblin 01",
"Cataclysm - Goblin 02",
"Cataclysm - Goblin 03",
"Cataclysm - Goblin 04",
"Cataclysm - Goblin 05",
"Cataclysm - Goblin 06",
"Cataclysm - Goblin 07",
"Cataclysm - Goblin 08",
"Cataclysm - Goblin 09",
"Cataclysm - Goblin 10",
"Cataclysm - Goblin 11",
"Cataclysm - Goblin 12",
"Cataclysm - Goblin 13",
"Cataclysm - Goblin 14",
"Cataclysm - Goblin 15",
"Cataclysm - Goblin 16",
"Cataclysm - Goblin 17",
"Cataclysm - Goblin 18",
"Cataclysm - Goblin 19",
"Cataclysm - Goblin 20",
"Cataclysm - Goblin 21",
"Cataclysm - Goblin 22",
"Cataclysm - Goblin 23",
"Cataclysm - Goblin 24",
"Cataclysm - Goblin 25",
"Cataclysm - Goblin 26",
"Cataclysm - Goblin 27",
"Cataclysm - Goblin 28",
"Cataclysm - Goblin 29",
"Cataclysm - Goblin 30",
"Cataclysm - Goblin 31",
"Cataclysm - Goblin 32",
"Cataclysm - Goblin 33",
"Cataclysm - Goblin 34",
"Cataclysm - Goblin 35",
"Cataclysm - Goblin 36",
"Cataclysm - Goblin 37",
"Cataclysm - Goblin 38",
"Cataclysm - Goblin 39",
"Cataclysm - Goblin 40",
"Cataclysm - Goblin 41",
"Cataclysm - Goblin 42",
"Cataclysm - Goblin 43",
"Cataclysm - Goblin 44",
"Cataclysm - Goblin 45",
"Cataclysm - Goblin 46",
"Cataclysm - Goblin 47",
"Cataclysm - GoblinHotRodRadioLoop EU01",
"Cataclysm - Grimtotem 01",
"Cataclysm - Grimtotem 02",
"Cataclysm - Grimtotem 03",
"Cataclysm - Grimtotem 04",
"Cataclysm - GroveOfTheAncients GU01",
"Cataclysm - GroveOfTheAncients GU02",
"Cataclysm - GroveOfTheAncients GU03",
"Cataclysm - GroveOfTheAncients GU04",
"Cataclysm - GuardiansofHyjal GU01",
"Cataclysm - GuardiansofHyjal GU02",
"Cataclysm - GuardiansofHyjal GU03",
"Cataclysm - GuardiansofHyjal GU04",
"Cataclysm - Haunted 01",
"Cataclysm - Haunted 02",
"Cataclysm - Haunted 03",
"Cataclysm - Hyjal GU01",
"Cataclysm - Hyjal GU02",
"Cataclysm - Hyjal GU03",
"Cataclysm - Hyjal GU04",
"Cataclysm - LandWillWeep 01",
"Cataclysm - LandWillWeep 02",
"Cataclysm - LIRescue EU01",
"Cataclysm - LIRescue EU02",
"Cataclysm - LIRescue EU03",
"Cataclysm - LIRescue EU04",
"Cataclysm - LostCity GU01",
"Cataclysm - LostCity GU02",
"Cataclysm - LostCity GU03",
"Cataclysm - LostCity GU04",
"Cataclysm - LostCity GU05",
"Cataclysm - Marsh 01",
"Cataclysm - Marsh 02",
"Cataclysm - Marsh 03",
"Cataclysm - Marsh 04",
"Cataclysm - Marsh 05",
"Cataclysm - Marsh 06",
"Cataclysm - Marsh 07",
"Cataclysm - Marsh 08",
"Cataclysm - Moonglade GU01",
"Cataclysm - Moonglade GU02",
"Cataclysm - Moonglade GU03",
"Cataclysm - Moonglade GU04",
"Cataclysm - Moonglade GU05",
"Cataclysm - Moonglade GU06",
"Cataclysm - Moonglade GU07",
"Cataclysm - Mulgore GU01",
"Cataclysm - Mulgore GU02",
"Cataclysm - Mulgore GU03",
"Cataclysm - MulgorePlains GU01",
"Cataclysm - MulgorePlains GU02",
"Cataclysm - Mysterious 01",
"Cataclysm - NightElves GU01",
"Cataclysm - NightElves GU02",
"Cataclysm - NightElves GU03",
"Cataclysm - NightElves GU04",
"Cataclysm - NightElves GU05",
"Cataclysm - Nordrassil GU01",
"Cataclysm - Nordrassil GU02",
"Cataclysm - Nordrassil GU03",
"Cataclysm - Orgrimmar GU01",
"Cataclysm - OrgrimmarLegacy GU01",
"Cataclysm - PiratesSurrender 01",
"Cataclysm - Rift 01",
"Cataclysm - Rift 02",
"Cataclysm - Rift 03",
"Cataclysm - Rift 04",
"Cataclysm - RuinsOfAuberdine GU01",
"Cataclysm - RuinsOfAuberdine GU02",
"Cataclysm - RuinsOfAuberdine GU03",
"Cataclysm - RuinsOfAuberdine GU04",
"Cataclysm - RuinsOfAuberdine GU05",
"Cataclysm - Scarred 01",
"Cataclysm - Scarred 02",
"Cataclysm - Scarred 03",
"Cataclysm - Scarred 04",
"Cataclysm - Shadowglen GU01",
"Cataclysm - Shadowglen GU02",
"Cataclysm - Shadowglen GU03",
"Cataclysm - Shadows 01",
"Cataclysm - Shadows 02",
"Cataclysm - Shadows 03",
"Cataclysm - Shadows 04",
"Cataclysm - Shadows 05",
"Cataclysm - Shattering 01",
"Cataclysm - Silithus GU01",
"Cataclysm - Silithus GU02",
"Cataclysm - Silithus GU03",
"Cataclysm - Silithus GU04",
"Cataclysm - Silithus GU05",
"Cataclysm - Silithus GU06",
"Cataclysm - SirenQuest EU01",
"Cataclysm - Skywall GU01",
"Cataclysm - Skywall GU02",
"Cataclysm - Skywall GU03",
"Cataclysm - Skywall GU04",
"Cataclysm - Skywall GU05",
"Cataclysm - Skywall GU06",
"Cataclysm - Skywall GU07",
"Cataclysm - Skywall GU08",
"Cataclysm - Skywall GU09",
"Cataclysm - Skywall GU10",
"Cataclysm - SouthernBarrens GU01",
"Cataclysm - SouthernBarrens GU02",
"Cataclysm - SouthernBarrens GU03",
"Cataclysm - SouthernBarrens GU04",
"Cataclysm - SouthernBarrens GU05",
"Cataclysm - SouthernBarrens GU06",
"Cataclysm - Stonetalon GU01",
"Cataclysm - Stonetalon GU02",
"Cataclysm - Stonetalon GU03",
"Cataclysm - Stonetalon GU04",
"Cataclysm - Stormwind GU01",
"Cataclysm - Stormwind GU02",
"Cataclysm - Stormwind GU03",
"Cataclysm - Stormwind GU04",
"Cataclysm - Stranglethorn GU01",
"Cataclysm - Stranglethorn GU02",
"Cataclysm - Stranglethorn GU03",
"Cataclysm - Stranglethorn GU04",
"Cataclysm - StranglethornVale GU01",
"Cataclysm - StranglethornVale GU02",
"Cataclysm - StranglethornVale GU03",
"Cataclysm - StranglethornVale GU04",
"Cataclysm - Tanaris GU01",
"Cataclysm - Tanaris GU02",
"Cataclysm - Tanaris GU03",
"Cataclysm - Tanaris GU04",
"Cataclysm - Tanaris GU05",
"Cataclysm - Tanaris GU06",
"Cataclysm - Tanaris GU07",
"Cataclysm - Tanaris GU08",
"Cataclysm - Tanaris GU09",
"Cataclysm - Tanaris GU10",
"Cataclysm - Tauren 01",
"Cataclysm - Tauren 02",
"Cataclysm - ThunderBluff GU01",
"Cataclysm - ThunderBluff GU02",
"Cataclysm - ThunderBluff GU03",
"Cataclysm - Treasure 01",
"Cataclysm - Treasure 02",
"Cataclysm - Treasure 03",
"Cataclysm - Treasure 04",
"Cataclysm - Treasure 05",
"Cataclysm - Treasure 06",
"Cataclysm - TwilightHighlands GU01",
"Cataclysm - TwilightHighlands GU02",
"Cataclysm - TwilightHighlands GU03",
"Cataclysm - TwilightHighlands GU04",
"Cataclysm - TwilightHighlands GU05",
"Cataclysm - TwilightsHammer 01",
"Cataclysm - TwilightsHammer 02",
"Cataclysm - TwilightsHammer 03",
"Cataclysm - TwilightVale GU01",
"Cataclysm - TwilightVale GU02",
"Cataclysm - TwilightVale GU03",
"Cataclysm - TwilightVale GU04",
"Cataclysm - TwilightVale GU05",
"Cataclysm - UldumA GU01",
"Cataclysm - UldumA GU02",
"Cataclysm - UldumA GU03",
"Cataclysm - UldumA GU04",
"Cataclysm - UldumA GU05",
"Cataclysm - UldumB GU01",
"Cataclysm - UldumB GU02",
"Cataclysm - UldumB GU03",
"Cataclysm - UldumB GU04",
"Cataclysm - UldumB GU05",
"Cataclysm - UldumB GU06",
"Cataclysm - UldumEvent E01",
"Cataclysm - Undead 01",
"Cataclysm - Undead 02",
"Cataclysm - Undead 03",
"Cataclysm - Undead 04",
"Cataclysm - Undead 05",
"Cataclysm - Vashjir GU01",
"Cataclysm - Vashjir GU02",
"Cataclysm - Vashjir GU03",
"Cataclysm - Vashjir GU04",
"Cataclysm - Vashjir GU05",
"Cataclysm - Vashjir GU06",
"Cataclysm - Vashjir GU07",
"Cataclysm - Vashjir GU08",
"Cataclysm - Vashjir GU09",
"Cataclysm - VashjirNaga GU01",
"Cataclysm - VashjirNaga GU02",
"Cataclysm - VashjirNaga GU03",
"Cataclysm - VashjirNaga GU04",
"Cataclysm - VashjirNaga GU05",
"Cataclysm - VashjirNaga GU06",
"Cataclysm - VashjirNagaThrone GU01",
"Cataclysm - VashjirNagaThrone GU02",
"Cataclysm - VashjirNagaThrone GU03",
"Cataclysm - VashjirNagaThrone GU04",
"Cataclysm - VashjirNagaThrone GU05",
"Cataclysm - VashjirNagaThrone GU06",
"Cataclysm - WarMarch 01",
"Cataclysm - Westfall GU01",
"Cataclysm - Westfall GU02",
"Cataclysm - Westfall GU03",
"Cataclysm - Westfall GU04",
"Cataclysm - Westfall GU05",
"Cataclysm - WestPlagueA GD01",
"Cataclysm - WestPlagueA GN01",
"Cataclysm - WestPlagueA GN02",
"Cataclysm - WestPlagueB GD01",
"Cataclysm - WestPlagueB GN01",
"Cataclysm - WestPlagueB GN02",
"Cataclysm - WestPlagueB GN03",
"Cataclysm - WestPlagueC GD01",
"Cataclysm - WestPlagueC GN01",
"Cataclysm - WestPlagueC GN02",
"Cataclysm - Winterspring GU01",
"Cataclysm - Winterspring GU02",
"Cataclysm - Winterspring GU03",
"Cataclysm - Winterspring GU04",
"Cataclysm - Winterspring GU05",
"Cataclysm - WordsAndMusicByEvent E01",
"CityDarnassus - Darnassus Intro",
"CityDarnassus - Darnassus Walking 1",
"CityDarnassus - Darnassus Walking 2",
"CityDarnassus - Darnassus Walking 3",
"CityDarnassus - Druid Grove",
"CityDarnassus - Warrior Terrace",
"CityGnomeragon - Gnomeragon 01",
"CityGnomeragon - Gnomeragon 02",
"CityIronforge - IronForge Intro",
"CityIronforge - IronForge Walking 01",
"CityIronforge - IronForge Walking 02",
"CityIronforge - Ironforge Walking 03 (Glenn)",
"CityIronforge - Ironforge Walking 04",
"CityIronforge - TinkerTownIntro moment",
"CityOrgrimmar - Orgrimmar Intro-moment",
"CityOrgrimmar - Orgrimmar01-moment",
"CityOrgrimmar - Orgrimmar01",
"CityOrgrimmar - Orgrimmar02-moment",
"CityOrgrimmar - Orgrimmar02",
"CityStormwind - Stormwind HighSeas-moment",
"CityStormwind - Stormwind Intro-moment",
"CityStormwind - Stormwind01-moment",
"CityStormwind - Stormwind02-moment",
"CityStormwind - Stormwind03-moment",
"CityStormwind - Stormwind04",
"CityStormwind - Stormwind05",
"CityStormwind - Stormwind06",
"CityStormwind - Stormwind07",
"CityStormwind - Stormwind08",
"CityThunderbluff - Thunderbluff Intro",
"CityThunderbluff - Thunderbluff Walking 01",
"CityThunderbluff - Thunderbluff Walking 02",
"CityThunderbluff - Thunderbluff Walking 03",
"CityUndercity - Undercity01",
"CityUndercity - Undercity02",
"CityUndercity - Undercity03",
"CityUndercity - UndercityIntro-moment",
"Event - Gnomeregan Event B",
"Event - Gnomeregan Event C",
"Event - Gnomeregan Event complete",
"Event - Gnomeregan Event D",
"Event - Gnomeregan Event E",
"Event - Gnomeregan Event intro",
"Event - ZFBigBattle13",
"Event - ZFBigBattle14",
"Event - ZFBigBattle16",
"Event - ZFMagic17",
"Event - ZFMagic18",
"Event - ZFMedBattle3",
"Event - ZFMedBattle4",
"Event - ZFMedBattle5",
"Event - ZFMedBattle6",
"Event - ZFQuiet1",
"Event - ZFQuiet2",
"Event - ZFQuiet7",
"Event - ZFQuietShort8",
"Event - ZFRally9",
"Event - ZFStinger10",
"Event - ZFStinger11",
"Event - ZFStinger12",
"Event - ZFStinger15",
"GlueScreen - BC main theme",
"GlueScreen - BC Credits - Lament of the Highborne",
"GlueScreen - WotLK main title",
"GlueScreen - wow main theme",
"SoundTest Music01",
"SoundTest Music02",
"SoundTest Music03",
"Musical Moments - Angelic - Angelic01",
"Musical Moments - Battle - Battle01",
"Musical Moments - Battle - Battle02",
"Musical Moments - Battle - Battle03",
"Musical Moments - Battle - Battle04",
"Musical Moments - Battle - Battle05",
"Musical Moments - Battle - Battle06",
"Musical Moments - Gloomy - Gloomy01",
"Musical Moments - Gloomy - Gloomy02",
"Musical Moments - GuldansEntranceTheme",
"Musical Moments - Haunted - Haunted01",
"Musical Moments - Haunted - Haunted02",
"Musical Moments - Magic - Magic01-moment",
"Musical Moments - Magic - Magic01-1",
"Musical Moments - Magic - Magic01-2",
"Musical Moments - Mystery - AhnQirajIntro1",
"Musical Moments - Mystery - Mystery01",
"Musical Moments - Mystery - Mystery02",
"Musical Moments - Mystery - Mystery03",
"Musical Moments - Mystery - Mystery04",
"Musical Moments - Mystery - Mystery05",
"Musical Moments - Mystery - Mystery06",
"Musical Moments - Mystery - Mystery07",
"Musical Moments - Mystery - Mystery08",
"Musical Moments - Mystery - Mystery09",
"Musical Moments - Mystery - Mystery10",
"Musical Moments - Sacred - Sacred01",
"Musical Moments - Sacred - sacred02",
"Musical Moments - SP TempleOfStormsActionUni01",
"Musical Moments - Spooky - Spooky01-moment",
"Musical Moments - Swamp - Swamp01",
"Musical Moments - ZulGurubVooDoo",
"Pandaria - FlyBy 52 MoguBridge MX SFX",
"Pandaria - FlyBy 52 MoguSecret MX SFX",
"Pandaria - AugustCelestials 01",
"Pandaria - AugustCelestials 02",
"Pandaria - AugustCelestials 03",
"Pandaria - AugustCelestials 04",
"Pandaria - AugustCelestials 05",
"Pandaria - AugustCelestials Hero 01",
"Pandaria - BalloonRide Hero 01",
"Pandaria - Bamboo 01",
"Pandaria - Bamboo 02",
"Pandaria - Bamboo 03",
"Pandaria - Bamboo 04",
"Pandaria - Bamboo Hero 01",
"Pandaria - Bamboo Night 01",
"Pandaria - Bamboo Night Hero 01",
"Pandaria - BattleforPandaria Hero 01",
"Pandaria - BattleforPandaria Hero 02",
"Pandaria - BottomsUp 01",
"Pandaria - BottomsUp Hero 01",
"Pandaria - Darkbrew 01",
"Pandaria - Darkbrew Hero 01",
"Pandaria - DreadWastes A Hero 01",
"Pandaria - DreadWastes A Hero 02",
"Pandaria - GateoftheSettingSun A Hero 01",
"Pandaria - GateoftheSettingSun A Hero 02",
"Pandaria - GateoftheSettingSun A Hero 03",
"Pandaria - GateoftheSettingSun A Hero 04",
"Pandaria - GateoftheSettingSun B 01",
"Pandaria - GateoftheSettingSun B Hero 01",
"Pandaria - GateoftheSettingSun B Hero 02",
"Pandaria - HeartofPandaria 01",
"Pandaria - Hozen A 01",
"Pandaria - Hozen A 02",
"Pandaria - Hozen A 03",
"Pandaria - Hozen A 04",
"Pandaria - Hozen A 05",
"Pandaria - Hozen A 06",
"Pandaria - Hozen A 07",
"Pandaria - Hozen A 08",
"Pandaria - Hozen A 09",
"Pandaria - Hozen A 10",
"Pandaria - Hozen A 11",
"Pandaria - Hozen A 12",
"Pandaria - Hozen A 13",
"Pandaria - Hozen A Hero 01",
"Pandaria - Hozen B 01",
"Pandaria - Hozen B 02",
"Pandaria - Hozen B 03",
"Pandaria - Hozen B Hero 01",
"Pandaria - Hozen Walk 01",
"Pandaria - Jinyu A Hero 01",
"Pandaria - Jinyu A Hero 02",
"Pandaria - Jinyu A Hero 03",
"Pandaria - Jinyu A Hero 04",
"Pandaria - Jinyu B 01",
"Pandaria - Jinyu B 02",
"Pandaria - Jinyu B Hero 01",
"Pandaria - Jinyu C 01",
"Pandaria - Jinyu C Hero 01",
"Pandaria - Jinyu C Hero 02",
"Pandaria - Jinyu D 01",
"Pandaria - Jinyu D Hero 01",
"Pandaria - Jinyu D Hero 02",
"Pandaria - Jinyu D Night 01",
"Pandaria - Jinyu D Night Hero 01",
"Pandaria - Jinyu D Night Hero 02",
"Pandaria - KrasarangWilds A Hero 01",
"Pandaria - KrasarangWilds A Hero 02",
"Pandaria - KrasarangWilds B Hero 01",
"Pandaria - KrasarangWilds B Hero 02",
"Pandaria - KrasarangWilds B Hero 03",
"Pandaria - KunLaiSummit A Hero 01",
"Pandaria - KunLaiSummit A Hero 02",
"Pandaria - KunLaiSummit A Hero 03",
"Pandaria - KunLaiSummit A Hero 04",
"Pandaria - KunLaiSummit B Hero 01",
"Pandaria - KunLaiSummit C Hero 01",
"Pandaria - KunLaiSummit C Hero 02",
"Pandaria - Mantid A 01",
"Pandaria - Mantid A 02",
"Pandaria - Mantid A 03",
"Pandaria - Mantid A Hero 01",
"Pandaria - Mogu A Hero 01",
"Pandaria - Mogu A Hero 02",
"Pandaria - Mogu B 01",
"Pandaria - Mogu B 02",
"Pandaria - Mogu B 03",
"Pandaria - Mogu B 04",
"Pandaria - Mogu B 05",
"Pandaria - Mogu B 06",
"Pandaria - Mogu B Hero 01",
"Pandaria - Monk Brewmaster A 01",
"Pandaria - Monk Brewmaster A Hero 01",
"Pandaria - Monk Mistweaver A 01",
"Pandaria - Monk Mistweaver A 02",
"Pandaria - Monk Mistweaver A 03",
"Pandaria - Monk Mistweaver A Hero 01",
"Pandaria - Monk Mistweaver A Hero 02",
"Pandaria - Monk Mistweaver A Walk 01",
"Pandaria - Monk Mistweaver A Walk 02",
"Pandaria - Monk Mistweaver B 01",
"Pandaria - Monk Mistweaver B 02",
"Pandaria - Monk Mistweaver B 03",
"Pandaria - Monk Mistweaver B 04",
"Pandaria - Monk Mistweaver B Hero 01",
"Pandaria - Monk Windwalker A 01",
"Pandaria - Monk Windwalker A 02",
"Pandaria - Monk Windwalker A 03",
"Pandaria - Monk Windwalker A Hero 01",
"Pandaria - Monk Windwalker A Hero 02",
"Pandaria - Monk Windwalker A Walk 01",
"Pandaria - Monk Windwalker A Walk 02",
"Pandaria - Monk Windwalker A Walk 03",
"Pandaria - Monk Windwalker A Walk 04",
"Pandaria - Pandaria A 01",
"Pandaria - Pandaria A 02",
"Pandaria - Pandaria A 03",
"Pandaria - Pandaria A Choir 01",
"Pandaria - Pandaria A Hero 01",
"Pandaria - Pandaria B 01",
"Pandaria - Pandaria B Hero 01",
"Pandaria - Pandaria B Hero 02",
"Pandaria - Pandaria C Hero 01",
"Pandaria - Pandaria C Hero 02",
"Pandaria - Pandaria C Hero 03",
"Pandaria - Pandaria C Walk 01",
"Pandaria - Pandaria C Walk 02",
"Pandaria - Pandaria C Walk 03",
"Pandaria - Pandaria D 01",
"Pandaria - Pandaria D 02",
"Pandaria - Pandaria D 03",
"Pandaria - Pandaria D Hero 01",
"Pandaria - PandariaPVP Hero 01",
"Pandaria - PandariaPVP Hero 02",
"Pandaria - ScarletMonastery A Hero 01",
"Pandaria - ScarletMonastery A Hero 02",
"Pandaria - ScarletMonastery A Hero 03",
"Pandaria - Scholomance A 01",
"Pandaria - Scholomance A 02",
"Pandaria - Scholomance A 03",
"Pandaria - Scholomance A 04",
"Pandaria - Scholomance A 05",
"Pandaria - Scholomance A 06",
"Pandaria - Scholomance A 07",
"Pandaria - Scholomance A 08",
"Pandaria - Scholomance A 09",
"Pandaria - Scholomance A 10",
"Pandaria - Scholomance A 11",
"Pandaria - Scholomance A 12",
"Pandaria - SerpentRiders 01",
"Pandaria - SerpentRiders Hero 01",
"Pandaria - SerpentRiders SerpentRace",
"Pandaria - SerpentRiders Victory Stinger",
"Pandaria - SerpentsHeart Hero 01",
"Pandaria - SerpentsHeart Hero 02",
"Pandaria - SerpentsHeart Hero 03",
"Pandaria - SerpentsHeart Night Hero 01",
"Pandaria - SerpentsHeart Night Hero 02",
"Pandaria - SerpentsHeart Night Walk 01",
"Pandaria - SerpentsHeart Night Walk 02",
"Pandaria - SerpentsHeart Night Walk 03",
"Pandaria - Sha 01",
"Pandaria - Sha 02",
"Pandaria - Sha Hero 01",
"Pandaria - Sha Stinger Heavy 01",
"Pandaria - Sha Stinger Heavy 02",
"Pandaria - Sha Stinger Heavy 03",
"Pandaria - Sha Stinger Lite 01",
"Pandaria - Sha Stinger Lite 02",
"Pandaria - Sha Stinger Lite 03",
"Pandaria - Sha Stinger Lite 04",
"Pandaria - Sha Stinger Med 01",
"Pandaria - Sha Stinger Med 02",
"Pandaria - ShadoPan A Hero 01",
"Pandaria - ShadoPan A Hero 02",
"Pandaria - ShadoPan A Hero 03",
"Pandaria - ShadoPan A Walk 01",
"Pandaria - ShadoPan A Walk 02",
"Pandaria - ShadoPan B Hero 01",
"Pandaria - ShadoPan B Hero 02",
"Pandaria - ShaWalk Hero 01",
"Pandaria - ShaWalk Hero 02",
"Pandaria - ShaWalk Hero 03",
"Pandaria - ShaWalk Hero 04",
"Pandaria - ShenZinSu 01",
"Pandaria - ShenZinSu 02",
"Pandaria - ShenZinSu 03",
"Pandaria - ShenZinSu Hero 01",
"Pandaria - ShenZinSu Hero 02",
"Pandaria - ShoSha A 01",
"Pandaria - ShoSha A 02",
"Pandaria - ShoSha A 03",
"Pandaria - ShoSha A 04",
"Pandaria - ShoSha A 05",
"Pandaria - ShoSha B 01",
"Pandaria - ShoSha B 02",
"Pandaria - ShoSha B 03",
"Pandaria - ShoSha B 04",
"Pandaria - ShoSha B 05",
"Pandaria - ShoSha B 06",
"Pandaria - SiegeofNiuzaoTemple Hero 01",
"Pandaria - SiegeofNiuzaoTemple Hero 02",
"Pandaria - SiegeofNiuzaoTemple Hero 03",
"Pandaria - SongofLiulang Inst 01",
"Pandaria - SongofLiulang Inst 02",
"Pandaria - SongofLiulang Inst 03",
"Pandaria - SongofLiulang Inst 04",
"Pandaria - SongofLiulang Inst 05",
"Pandaria - SongofLiulang Inst 06",
"Pandaria - SongofLiulang Inst 07",
"Pandaria - SongofLiulang Inst Hero 01",
"Pandaria - SongofLiulang VOX Hero 01",
"Pandaria - SongofLiulang VOX Lite 01",
"Pandaria - SpiritCave 01",
"Pandaria - SpiritCave 02",
"Pandaria - SpiritCave 03",
"Pandaria - SpiritCave 04",
"Pandaria - SpiritCave 05",
"Pandaria - SpiritCave 06",
"Pandaria - SpiritCave Hero 01",
"Pandaria - SpiritPath 01",
"Pandaria - SpiritPath 02",
"Pandaria - SpiritPath 03",
"Pandaria - SpiritPath 04",
"Pandaria - SpiritPath Hero 01",
"Pandaria - Spirits A 01",
"Pandaria - Spirits A 02",
"Pandaria - Spirits A 03",
"Pandaria - Spirits A 04",
"Pandaria - SpiritsB 01",
"Pandaria - SpiritsB 02",
"Pandaria - TempleoftheFiveDawns 01",
"Pandaria - TempleoftheFiveDawns 02",
"Pandaria - TempleoftheFiveDawns 03",
"Pandaria - TempleoftheFiveDawns 04",
"Pandaria - TempleoftheFiveDawns 05",
"Pandaria - TempleoftheFiveDawns 06",
"Pandaria - TempleoftheFiveDawns 07",
"Pandaria - TempleoftheFiveDawns 08",
"Pandaria - TempleoftheFiveDawns 09",
"Pandaria - TempleoftheFiveDawns 10",
"Pandaria - TempleoftheFiveDawns 11",
"Pandaria - TempleoftheFiveDawns 12",
"Pandaria - TempleoftheFiveDawns Hero 01",
"Pandaria - TempleoftheJadeSerpent Hero 01",
"Pandaria - TempleoftheJadeSerpent Hero 02",
"Pandaria - TempleoftheJadeSerpent Hero 03",
"Pandaria - TheHeartland Hero 01",
"Pandaria - TheHeartland Hero 02",
"Pandaria - TheHeartland Hero 03",
"Pandaria - TheHeartland Hero 04",
"Pandaria - TheRiver 01",
"Pandaria - TheRiver 02",
"Pandaria - TheRiver 03",
"Pandaria - TheRiver 04",
"Pandaria - TheRiver 05",
"Pandaria - TheRiver 06",
"Pandaria - TheRiver 07",
"Pandaria - TheRiver Hero 01",
"Pandaria - Toast A 01",
"Pandaria - Toast A Hero 01",
"Pandaria - Toast B 02",
"Pandaria - Toast B 03",
"Pandaria - Toast B 04",
"Pandaria - Toast B Hero 01",
"Pandaria - TownlongSteppes A Hero 01",
"Pandaria - TownlongSteppes A Hero 02",
"Pandaria - TownlongSteppes B 01",
"Pandaria - TownlongSteppes B 02",
"Pandaria - TownlongSteppes B Hero 01",
"Pandaria - TownlongSteppes C Hero 01",
"Pandaria - TownlongSteppes C Hero 02",
"Pandaria - TownlongSteppes C Hero 03",
"Pandaria - TownlongSteppes C Night Hero 01",
"Pandaria - TownlongSteppes C Night Hero 02",
"Pandaria - TownlongSteppes C Night Hero 03",
"Pandaria - TownlongSteppes D 01",
"Pandaria - TownlongSteppes D Hero 01",
"Pandaria - TownlongSteppes D Hero 02",
"Pandaria - VEB A 01",
"Pandaria - VEB A 02",
"Pandaria - VEB A 03",
"Pandaria - VEB A 04",
"Pandaria - VEB A 05",
"Pandaria - VEB A 06",
"Pandaria - VEB A Hero 01",
"Pandaria - VEB B 01",
"Pandaria - VEB B 02",
"Pandaria - VEB B 03",
"Pandaria - VEB B Hero 01",
"Pandaria - VEB B Night 01",
"Pandaria - VEB B Night 02",
"Pandaria - VEB B Night 03",
"Pandaria - VEB B Night 04",
"Pandaria - VEB B Night 05",
"Pandaria - VEB B Night 06",
"Pandaria - VEB C Hero 01",
"Pandaria - VEB C Hero 02",
"Pandaria - VEB D Hero 01",
"Pandaria - VEB D Hero 02",
"Pandaria - VEB D Hero 03",
"Pandaria - VEB D Hero 04",
"Pandaria - VFW A 01",
"Pandaria - VFW A 02",
"Pandaria - VFW A 03",
"Pandaria - VFW A 04",
"Pandaria - VFW A 05",
"Pandaria - VFW A 06",
"Pandaria - VFW A 07",
"Pandaria - VFW A 08",
"Pandaria - VFW A Hero 01",
"Pandaria - VFW A Hero 02",
"Pandaria - Windspire 01",
"Pandaria - Windspire 02",
"Pandaria - Windspire 03",
"Pandaria - Windspire Hero 01",
"Pandaria - WoodofStaves Hero 01",
"Pandaria - WoodofStaves Hero 02",
"Pandaria - WoodofStaves Hero 03",
"Pandaria - AllianceBattleMarch 01",
"Pandaria - AllianceBattleMarch 02",
"Pandaria - AllianceBattleMarch Hero 01",
"Pandaria - ForTheAlliance 01",
"Pandaria - ForTheAlliance 02",
"Pandaria - ForTheAlliance 03",
"Pandaria - ForTheAlliance 04",
"Pandaria - ForTheAlliance 05",
"Pandaria - ForTheAlliance Hero 01",
"Pandaria - GarroshTheme A 01",
"Pandaria - GarroshTheme A 02",
"Pandaria - GarroshTheme A Hero 01",
"Pandaria - GarroshTheme B 01",
"Pandaria - GarroshTheme B 02",
"Pandaria - GarroshTheme B Hero 01",
"Pandaria - GarroshTheme Big DivineBellFinale",
"Pandaria - JainaHomeland Lyrical 01",
"Pandaria - JainaHomeland Lyrical 02",
"Pandaria - JainaHomeland Lyrical Hero 01",
"Pandaria - JainaHomeland Military 01",
"Pandaria - JainaHomeland Military 02",
"Pandaria - JainaHomeland Military 03",
"Pandaria - JainaHomeland Military Hero 01",
"Pandaria - Sunreavers 01",
"Pandaria - Sunreavers 02",
"Pandaria - Sunreavers 03",
"Pandaria - Sunreavers 04",
"Pandaria - Sunreavers 05",
"Pandaria - Sunreavers 06",
"Pandaria - Sunreavers 07",
"Pandaria - Sunreavers 08",
"Pandaria - Sunreavers 09",
"Pandaria - Sunreavers 10",
"Pandaria - Sunreavers 11",
"Pandaria - Sunreavers 12",
"Pandaria - Sunreavers 13",
"Pandaria - Sunreavers 14",
"Pandaria - Sunreavers 15",
"Pandaria - Sunreavers 16",
"Pandaria - Sunreavers 17",
"Pandaria - Sunreavers 18",
"Pandaria - Sunreavers 19",
"Pandaria - Sunreavers Hero 01",
"Pandaria - Theramores Fall Scene 01",
"Pandaria - AncientMogu A 01",
"Pandaria - AncientMogu A 02",
"Pandaria - AncientMogu A 03",
"Pandaria - AncientMogu A 04",
"Pandaria - AncientMogu A Hero 01",
"Pandaria - AncientMogu B 01",
"Pandaria - AncientMogu B Hero 01",
"Pandaria - AncientMogu B Stinger 01",
"Pandaria - AncientMogu C 01",
"Pandaria - AncientMogu C 02",
"Pandaria - AncientMogu C 03",
"Pandaria - AncientMogu C 04",
"Pandaria - AncientMogu C 05",
"Pandaria - AncientMogu C 06",
"Pandaria - AncientMogu C Hero 01",
"Pandaria - AncientMogu C Stinger 01",
"Pandaria - AncientMogu C Stinger 02",
"Pandaria - AncientMogu D 01",
"Pandaria - AncientMogu D 02",
"Pandaria - AncientMogu D Hero 01",
"Pandaria - AncientPandaria A 01",
"Pandaria - AncientPandaria Hero 01",
"Pandaria - GodsAndMonster 01",
"Pandaria - ItIsDone A 01",
"Pandaria - ItIsDone A 02",
"Pandaria - ItIsDone A 03",
"Pandaria - ItIsDone A 04",
"Pandaria - ItIsDone A 05",
"Pandaria - Mysterioso A 01",
"Pandaria - Mysterioso A 02",
"Pandaria - Mysterioso Hero 01",
"Pandaria - ThunderIsle A 01",
"Pandaria - ThunderIsle A 02",
"Pandaria - ThunderIsle A 03",
"Pandaria - ThunderIsle A 04",
"Pandaria - ThunderIsle A 05",
"Pandaria - ThunderIsle A 06",
"Pandaria - ThunderIsle A 07",
"Pandaria - ThunderIsle A Hero 01",
"Pandaria - ThunderIsle A Stinger 01",
"Pandaria - ThunderIsle A Stinger 02",
"Pandaria - ThunderIsle A Stinger 03",
"Pandaria - ThunderIsle A Stinger 04",
"Pandaria - ThunderIsle B 01",
"Pandaria - ThunderIsle B 02",
"Pandaria - ThunderIsle B 03",
"Pandaria - ThunderIsle B 04",
"Pandaria - ThunderIsle B 05",
"Pandaria - ThunderIsle B Hero 01",
"Pandaria - ThunderIsle C 01",
"Pandaria - ThunderIsle C 02",
"Pandaria - ThunderIsle C 03",
"Pandaria - ThunderIsle C 04",
"Pandaria - ThunderIsle C Hero 01",
"Pandaria - ThunderIsle C Stinger 01",
"Pandaria - ThunderIsle C Stinger 02",
"Pandaria - ThunderIsle C Stinger 03",
"Pandaria - ThunderKing A 01",
"Pandaria - ThunderKing A 02",
"Pandaria - ThunderKing A 03",
"Pandaria - ThunderKing A Hero 01",
"Pandaria - ThunderKing A Stinger 01",
"Pandaria - ThunderKing A Stinger 02",
"Pandaria - ThunderKing A Stinger 03",
"Pandaria - ThunderKing A Stinger 04",
"Pandaria - ThunderKing A Stinger 05",
"Pandaria - ThunderKing A Stinger 06",
"Pandaria - ThunderKing A Stinger 07",
"Pandaria - ThunderKing B 01",
"Pandaria - ThunderKing B Hero 01",
"Pandaria - ThunderKing C Stinger 01",
"Pandaria - TrollBattle A 01",
"Pandaria - TrollBattle A 02",
"Pandaria - TrollBattle A 03",
"Pandaria - TrollBattle B 01",
"Pandaria - TrollBattle B 02",
"Pandaria - TrollBattle B 03",
"Pandaria - TrovesOfTheThunderKing 01",
"Pandaria - Wrathion A 02",
"Pandaria - Wrathion A 03",
"Pandaria - Wrathion A Hero 01",
"Pandaria - Wrathion B 01",
"Pandaria - Wrathion B 02",
"Pandaria - Wrathion B 03",
"Pandaria - Zandalari 1 A 01",
"Pandaria - Zandalari 1 A 02",
"Pandaria - Zandalari 1 A 03",
"Pandaria - Zandalari 1 B 01",
"Pandaria - Zandalari 1 B 02",
"Pandaria - Zandalari 1 B 03",
"Pandaria - Zandalari 1 C 01",
"Pandaria - Zandalari 1 C 02",
"Pandaria - Zandalari 2 A 01",
"Pandaria - Zandalari 2 A 02",
"Pandaria - Zandalari 2 A 03",
"Pandaria - Zandalari 2 A 04",
"Pandaria - Zandalari 2 A 05",
"Pandaria - Zandalari 2 B 01",
"Pandaria - Zandalari 2 B 02",
"Pandaria - Zandalari 2 B 03",
"Pandaria - Zandalari 2 C 01",
"Pandaria - Zandalari 2 C 02",
"Pandaria - Zandalari 2 C 03",
"Pandaria - ZandalariProphecy 01",
"Pandaria - EmperorRevealed",
"Pandaria - Wrathion C 01",
"Pandaria - Wrathion C 02",
"Pandaria - CorruptedVale Day 01",
"Pandaria - CorruptedVale Day 02",
"Pandaria - CorruptedVale Day 03",
"Pandaria - CorruptedVale Day 04",
"Pandaria - CorruptedVale Day Hero",
"Pandaria - CorruptedVale Night 01",
"Pandaria - CorruptedVale Night 02",
"Pandaria - CorruptedVale Night 03",
"Pandaria - CorruptedVale Night 04",
"Pandaria - CorruptedVale Night 05",
"Pandaria - CorruptedVale Night Hero",
"Pandaria - Doomhammer 01",
"Pandaria - Doomhammer 02",
"Pandaria - Doomhammer 03",
"Pandaria - Doomhammer 04",
"Pandaria - Doomhammer 05",
"Pandaria - Doomhammer Hero",
"Pandaria - ForThePandarenAlliance A 01",
"Pandaria - ForThePandarenAlliance A 02",
"Pandaria - ForThePandarenAlliance B 01",
"Pandaria - ForThePandarenAlliance B 02",
"Pandaria - GoodMourning Hero",
"Pandaria - Legendary 01",
"Pandaria - Legendary 02",
"Pandaria - Legendary 03",
"Pandaria - Legendary 04",
"Pandaria - Legendary 05",
"Pandaria - Legendary 06",
"Pandaria - Legendary 07",
"Pandaria - Legendary 08",
"Pandaria - Legendary 09",
"Pandaria - Legendary 10",
"Pandaria - Legendary Hero",
"Pandaria - Mok-Rah 01",
"Pandaria - Mok-Rah 02",
"Pandaria - Mok-Rah 03",
"Pandaria - Mok-Rah 04",
"Pandaria - Mok-Rah 05",
"Pandaria - Mok-Rah 06",
"Pandaria - Mok-Rah 07",
"Pandaria - Mok-Rah 08",
"Pandaria - Mok-Rah Hero",
"Pandaria - NoQuarter 01",
"Pandaria - NoQuarter 02",
"Pandaria - NoQuarter 03",
"Pandaria - NoQuarter 04",
"Pandaria - NoQuarter Hero",
"Pandaria - Overlord 01",
"Pandaria - Overlord 02",
"Pandaria - Overlord 03",
"Pandaria - Overlord Hero",
"Pandaria - ShaAmbient 01",
"Pandaria - ShaAmbient 02",
"Pandaria - ShaAmbient 03",
"Pandaria - ShaAmbient 04",
"Pandaria - ShaAmbient Hero",
"Pandaria - ShaAngry 01",
"Pandaria - ShaAngry 02",
"Pandaria - ShaAngry Hero",
"Pandaria - ShaDescendant 01",
"Pandaria - ShaDescendant 02",
"Pandaria - ShaDescendant 03",
"Pandaria - ShaDescendant Hero",
"Pandaria - ShaVocaline 01",
"Pandaria - ShaVocaline 02",
"Pandaria - ShaVocaline 03",
"Pandaria - ShaVocaline Hero",
"Pandaria - ValeHealing",
"PetBattles - ToyTrumpet",
"PetBattles - W2 Human1",
"PetBattles - W2 Human2",
"PetBattles - W2 Human3",
"PetBattles - W2 Human4",
"PetBattles - W2 HumanVictory",
"PetBattles - W2 HumanWarRoom",
"PetBattles - W2 Orc1",
"PetBattles - W2 Orc2",
"PetBattles - W2 Orc3",
"PetBattles - W2 Orc4",
"PetBattles - W2 OrcVictory",
"PetBattles - W2 OrcWarRoom",
"WorldEvents - AllianceFirepole",
"WorldEvents - DarkMoonFaire 1",
"WorldEvents - DarkMoonFaire 2",
"WorldEvents - DarkMoonFaire 3",
"WorldEvents - DarkMoonFaire 4",
"WorldEvents - HordeFirepole",
"AhnQiraj - AhnQirajExteriorWalking1",
"AhnQiraj - AhnQirajExteriorWalking2",
"AhnQiraj - AhnQirajExteriorWalking3",
"AhnQiraj - AhnQirajExteriorWalking4",
"AhnQiraj - AhnQirajInterior1",
"AhnQiraj - AhnQirajInterior2",
"AhnQiraj - AhnQirajInterior3",
"AhnQiraj - AhnQirajInteriorCenterRoom1",
"AhnQiraj - AhnQirajInteriorIntroMain",
"AhnQiraj - AhnQirajKingRoom",
"AhnQiraj - AhnQirajTriangleRoom1",
"AhnQiraj - AhnQirajTriangleRoom2",
"AhnQiraj - AhnQirajTriangleRoom3",
"AhnQiraj - AhnQirajTriangleRoom4",
"AhnQiraj - AhnQirajTriangleRoom5",
"AhnQiraj - AhnQirajTriangleRoom6",
"AhnQiraj - AhnQirajTriangleRoom7",
"ArgentColiseum - CR TourneyBattle01UniWalk",
"ArgentColiseum - CR TourneyBattle02UniWalk",
"ArgentColiseum - CR TourneyBattle03UniWalk",
"ArgentColiseum - CR TourneyBattle04UniWalk",
"ArgentColiseum - CR TourneyBattle05UniWalk",
"ArgentColiseum - CR TourneyBattle06UniWalk",
"ArgentTournament - AT HeraldEvent",
"ArgentTournament - AT JoustEvent",
"ArgentTournament - AT Tourney01NightWalk",
"ArgentTournament - AT Tourney02DayWalk",
"ArgentTournament - AT Tourney03NightWalkUniWalk",
"ArgentTournament - AT Tourney05NightWalk",
"ArgentTournament - AT Tourney06DayWalk",
"ArgentTournament - AT Tourney07NightWalk",
"ArgentTournament - AT Tourney08NightWalk",
"ArgentTournament - AT Tourney09DayWalk",
"ArgentTournament - AT Tourney10DayWalk",
"AzjolNerub - AN GeneralIntro 01",
"AzjolNerub - AN GeneralIntro 02",
"AzjolNerub - AN GeneralIntro 03",
"AzjolNerub - AN GeneralIntro 04",
"AzjolNerub - AN GeneralIntro 05",
"AzjolNerub - AN GeneralIntro 06",
"AzjolNerub - AN GeneralIntro 07",
"AzjolNerub - AN GeneralIntro 08",
"AzjolNerub - AN GeneralWalk 01",
"AzjolNerub - AN GeneralWalk 02",
"AzjolNerub - AN GeneralWalk 03",
"AzjolNerub - AN GeneralWalk 04",
"AzjolNerub - AN GeneralWalk 05",
"AzjolNerub - AN GeneralWalk 06",
"AzjolNerub - AN GeneralWalk 07",
"AzjolNerub - AN GeneralWalk 08",
"AzjolNerub - AN GeneralWalk 09",
"AzjolNerub - AN GeneralWalk 10",
"AzjolNerub - AN GeneralWalk 11",
"AzjolNerub - AN GeneralWalk 12",
"AzjolNerub - AN GeneralWalk 13",
"AzjolNerub - AN GeneralWalk 14",
"AzjolNerub - AN GeneralWalk 15",
"AzjolNerub - AN GeneralWalk 16",
"Azuremyst - AI DraeneiWalkUni05",
"Azuremyst - AI DraeneiWalkUni06",
"Azuremyst - AI DraeneiWalkUni07r",
"Azuremyst - AI DraeneiWalkUni08r",
"Azuremyst - AI ExodarIntro01",
"Azuremyst - AI ExodarWalkUni01",
"Azuremyst - AI ExodarWalkUni02",
"Azuremyst - AI ExodarWalkUni03",
"Azuremyst - AI NagaWalkUni01",
"Azuremyst - AI NagaWalkUni02",
"Azuremyst - AI NagaWalkUni03",
"Azuremyst - AI NagaWalkUni04",
"Azuremyst - AI NagaWalkUni05",
"Azuremyst - AI OwlkinWalkUni01",
"Azuremyst - AI OwlkinWalkUni02",
"Azuremyst - AV DraeneiWalkUni01",
"Azuremyst - AV DraeneiWalkUni02",
"Azuremyst - AV DraeneiWalkUni02r",
"Azuremyst - AV DraeneiWalkUni03",
"Azuremyst - AV DraeneiWalkUni03r",
"Azuremyst - AV DraeneiWalkUni04",
"BarrenDry - DayBarrenDry01",
"BarrenDry - DayBarrenDry02",
"BarrenDry - DayBarrenDry03",
"BarrenDry - NightBarrenDry01",
"BarrenDry - NightBarrenDry02",
"BarrenDry - NightBarrenDry03",
"BlackTemple - BT ArrivalWalkHero01",
"BlackTemple - BT ArrivalWalkUni02",
"BlackTemple - BT ArrivalWalkUni03",
"BlackTemple - BT ArrivalWalkUni04",
"BlackTemple - BT IllidariWalkHero09",
"BlackTemple - BT IllidariWalkUni01",
"BlackTemple - BT IllidariWalkUni02",
"BlackTemple - BT IllidariWalkUni03",
"BlackTemple - BT IllidariWalkUni04",
"BlackTemple - BT IllidariWalkUni05",
"BlackTemple - BT IllidariWalkUni06",
"BlackTemple - BT IllidariWalkUni07",
"BlackTemple - BT IllidariWalkUni08",
"BlackTemple - BT IllidariWalkUni10",
"BlackTemple - BT IllidariWalkUni11",
"BlackTemple - BT KaraborWalkUni01",
"BlackTemple - BT KaraborWalkUni02",
"BlackTemple - BT KaraborWalkUni03",
"BlackTemple - BT KaraborWalkUni04",
"BlackTemple - BT PreludeEvent01",
"BlackTemple - BT ReliquaryWalkHero01",
"BlackTemple - BT ReliquaryWalkUni02",
"BlackTemple - BT ReliquaryWalkUni03",
"BlackTemple - BT ReliquaryWalkUni04",
"BlackTemple - BT ReliquaryWalkUni05",
"BlackTemple - BT ReliquaryWalkUni06",
"BlackTemple - BT ReliquaryWalkUni07",
"BlackTemple - BT ReliquaryWalkUni08",
"BlackTemple - BT SanctuaryWalkHero01",
"BlackTemple - BT SanctuaryWalkUni02",
"BlackTemple - BT SanctuaryWalkUni03",
"BlackTemple - BT SanctuaryWalkUni04",
"BlackTemple - BT SanctuaryWalkUni05",
"BlackTemple - BT SanctuaryWalkUni06",
"BlackTemple - BT SanctuaryWalkUni07",
"BlackTemple - BT SanctuaryWalkUni08",
"BlackTemple - BT StormWalkHero02",
"BlackTemple - BT StormWalkUni01",
"BlackTemple - BT StormWalkUni03",
"BlackTemple - BT StormWalkUni04",
"BlackTemple - BT SummitWalkUni01",
"BlackTemple - BT SummitWalkUni02",
"BlackTemple - BT SummitWalkUni03",
"BlackTemple - BT SummitWalkUni04",
"BlackTemple - BT SummitWalkUni05",
"BladesEdge - BL DryForestWalkUni01",
"BladesEdge - BL DryForestWalkUni02",
"BladesEdge - BL DryForestWalkUni03",
"BladesEdge - BL GeneralWalkUni01",
"BladesEdge - BL GeneralWalkUni02",
"BladesEdge - BL GeneralWalkUni03",
"BladesEdge - BL GeneralWalkUni04",
"BladesEdge - BL GeneralWalkUni05",
"BladesEdge - BL OgreWalkUni01",
"BladesEdge - BL OgreWalkUni02",
"Bloodmyst - BI NagaIntro01",
"Bloodmyst - BI NagaIntro01r",
"Bloodmyst - BI SatyrWalkUni01r",
"Bloodmyst - BI SatyrWalkUni02",
"Bloodmyst - BI SatyrWalkUni03",
"Bloodmyst - BI SatyrWalkUni04",
"Bloodmyst - BI SatyrWalkUni05",
"BoreanTundra - BO ColdarraWalkUni01",
"BoreanTundra - BO ColdarraWalkUni02",
"BoreanTundra - BO ColdarraWalkUni03",
"BoreanTundra - BO GeneralWalk Day01",
"BoreanTundra - BO GeneralWalk Day02",
"BoreanTundra - BO GeneralWalk Day03",
"BoreanTundra - BO GeneralWalk Day04",
"BoreanTundra - BO GeneralWalk Day05",
"BoreanTundra - BO GeneralWalk Day06",
"BoreanTundra - BO GeneralWalk Day07",
"BoreanTundra - BO GeneralWalk Day08",
"BoreanTundra - BO GeneralWalk Night01",
"BoreanTundra - BO GeneralWalk Night02",
"BoreanTundra - BO GeneralWalk Night03",
"BoreanTundra - BO GeneralWalk Night04",
"BoreanTundra - BO GeneralWalk Night05",
"BoreanTundra - BO GeneralWalk Night06",
"BoreanTundra - BO GeneralWalk Night07",
"BoreanTundra - BO GeneralWalk Night08",
"BoreanTundra - BO GeyserField General01",
"BoreanTundra - BO GeyserField General02",
"BoreanTundra - BO GeyserField General03",
"BoreanTundra - BO Riplash Day01",
"BoreanTundra - BO Riplash Day02",
"BoreanTundra - BO Riplash Day03",
"BoreanTundra - BO Riplash Intro01",
"BoreanTundra - BO Riplash Intro02",
"BoreanTundra - BO Riplash Night01",
"BoreanTundra - BO Riplash Night02",
"BoreanTundra - BO Riplash Night03",
"BoreanTundra - BO Riplash Night04",
"BoreanTundra - BO Tusk KaskalaDay01",
"BoreanTundra - BO Tusk KaskalaDay02",
"BoreanTundra - BO Tusk KaskalaNight01",
"BoreanTundra - BO Tusk KaskalaNight02",
"Brewfest - BF Dwarves1",
"Brewfest - BF Dwarves2",
"Brewfest - BF Dwarves3",
"Brewfest - BF Goblins1",
"Brewfest - BF Goblins2",
"Brewfest - BF Goblins3",
"CavernsOfTime - CT BrazensFlightIntroUni",
"CavernsOfTime - CT CavernsWalk1Uni",
"CavernsOfTime - CT CavernsWalk2Uni",
"CavernsOfTime - CT CavernsWalk3Uni",
"CavernsOfTime - CT CavernsWalk4Uni",
"CavernsOfTime - CT CavernsWalk5Uni",
"CavernsOfTime - CT CavernsWalk6Uni",
"CavernsOfTime - CT CavernsWalk7Uni",
"CavernsOfTime - CT CavernsWalk8Uni",
"CavernsOfTime - CT CavernsWalk9Uni",
"CavernsOfTime - CT DurnholdeCellarWalk1Uni",
"CavernsOfTime - CT DurnholdeCellarWalk2Uni",
"CavernsOfTime - CT DurnholdeCellarWalk3Uni",
"CavernsOfTime - CT DurnholdeKeepExtWalk1Uni",
"CavernsOfTime - CT DurnholdeKeepExtWalk2Uni",
"CavernsOfTime - CT DurnholdeKeepExtWalk3Uni",
"CavernsOfTime - CT DurnholdeKeepExtWalk4Uni",
"CavernsOfTime - CT DurnholdeKeepExtWalk5Uni",
"CavernsOfTime - CT DurnholdeKeepExtWalk6Uni",
"CavernsOfTime - CT DurnholdeKeepIntWalk1Uni",
"CavernsOfTime - CT DurnholdeKeepIntWalk2Uni",
"CavernsOfTime - CT DurnholdeKeepIntWalk3Uni",
"CavernsOfTime - CT EscapeDurnIntroUni",
"CavernsOfTime - CT HillsbradExtWalk1Uni",
"CavernsOfTime - CT HillsbradExtWalk2Uni",
"CavernsOfTime - CT HyjalExtWalk7Uni",
"CavernsOfTime - CT HyjalExtWalk8Uni",
"CavernsOfTime - CT HyjalExtWalk9Uni",
"CavernsOfTime - CT HyjalExtWalkUni01",
"CavernsOfTime - CT HyjalExtWalkUni02",
"CavernsOfTime - CT HyjalExtWalkUni03",
"CavernsOfTime - CT HyjalExtWalkUni04",
"CavernsOfTime - CT HyjalExtWalkUni05",
"CavernsOfTime - CT HyjalExtWalkUni06",
"CavernsOfTime - CT HyjalExtWalkUni10",
"CavernsOfTime - CT HyjalExtWalkUni11",
"CavernsOfTime - CT HyjalExtWalkUni12",
"CavernsOfTime - CT MorassPortalIntro01",
"CavernsOfTime - CT MorassWalkUni01",
"CavernsOfTime - CT MorassWalkUni02",
"CavernsOfTime - CT MorassWalkUni03",
"CavernsOfTime - CT MorassWalkUni04",
"CavernsOfTime - CT MorassWalkUni05",
"CavernsOfTime - CT TarrenMillExtWalk1Uni",
"CavernsOfTime - CT TarrenMillExtWalk2Uni",
"CavernsOfTime - CT TarrenMillExtWalk3Uni",
"CavernsOfTime - CT ThrallEscapeIntroUni",
"ChamberOfTheAspects - CA AspectsGeneralWalkADay01",
"ChamberOfTheAspects - CA AspectsGeneralWalkADay02",
"ChamberOfTheAspects - CA AspectsGeneralWalkADay03",
"ChamberOfTheAspects - CA AspectsGeneralWalkADay04",
"ChamberOfTheAspects - CA AspectsGeneralWalkANight01",
"ChamberOfTheAspects - CA AspectsGeneralWalkANight02",
"ChamberOfTheAspects - CA AspectsGeneralWalkANight03",
"ChamberOfTheAspects - CA AspectsGeneralWalkANight04",
"ChamberOfTheAspects - CA AspectsGeneralWalkAUni01",
"ChamberOfTheAspects - CA AspectsGeneralWalkAUni02",
"ChamberOfTheAspects - CA AspectsIntroADay01",
"ChamberOfTheAspects - CA AspectsIntroANight01",
"Crystalsong - CS CrystalsongWalkUni01",
"Crystalsong - CS CrystalsongWalkUni02",
"Crystalsong - CS CrystalsongWalkUni03",
"Crystalsong - CS CrystalsongWalkUni04",
"Crystalsong - CS CrystalsongWalkUni05",
"CursedLand - CursedLand01",
"CursedLand - CursedLand02",
"CursedLand - CursedLand03",
"CursedLand - CursedLand04",
"CursedLand - CursedLand05",
"CursedLand - CursedLand06",
"Dalaran - DC GeneralWalkUni01",
"Dalaran - DC GeneralWalkUni02",
"Dalaran - DC GeneralWalkUni03",
"Dalaran - DC GeneralWalkUni04",
"Dalaran - DC IntroUni01",
"Dalaran - DC SewerWalkUni01",
"Dalaran - DC SewerWalkUni02",
"Dalaran - DC SewerWalkUni03",
"Dalaran - DC SewerWalkUni04",
"Dalaran - DC SpireWalkUni01",
"DarkmoonFaire - DarkmoonFaireA Hero 01",
"DarkmoonFaire - DarkmoonFaireA 01",
"DarkmoonFaire - DarkmoonFaireB Hero 01",
"DarkmoonFaire - DarkmoonFaireB 01",
"DarkmoonFaire - DarkmoonFaireB 02",
"DarkmoonFaire - DarkmoonFaireC 02",
"DarkmoonFaire - DarkmoonFaireD 01",
"DarkmoonFaire - DarkmoonFaireD 02",
"DarkmoonFaire - DarkmoonFaire MerryGoRound 01",
"Desert - DayDesert01",
"Desert - DayDesert02",
"Desert - DayDesert03",
"Desert - NightDesert01",
"Desert - NightDesert02",
"Desert - NightDesert03",
"DMF L70ETC01",
"Dragonblight - DB GeneralIntro 01",
"Dragonblight - DB GeneralIntro 02",
"Dragonblight - DB GeneralIntro 03",
"Dragonblight - DB GeneralIntro 04",
"Dragonblight - DB GeneralWalk Day01",
"Dragonblight - DB GeneralWalk Day02",
"Dragonblight - DB GeneralWalk Day03",
"Dragonblight - DB GeneralWalk Day04",
"Dragonblight - DB GeneralWalk Day05",
"Dragonblight - DB GeneralWalk Day06",
"Dragonblight - DB GeneralWalk Day07",
"Dragonblight - DB GeneralWalk Day08",
"Dragonblight - DB GeneralWalk Night01",
"Dragonblight - DB GeneralWalk Night02",
"Dragonblight - DB GeneralWalk Night03",
"Dragonblight - DB GeneralWalk Night04",
"Dragonblight - DB GeneralWalk Night05",
"Dragonblight - DB GeneralWalk Night06",
"Dragonblight - DB GeneralWalk Night07",
"Dragonblight - DB GeneralWalk Night08",
"Dragonblight - DB Tusk Indule Day01",
"Dragonblight - DB Tusk Indule Day02",
"Dragonblight - DB Tusk InduleDay01",
"Dragonblight - DB Tusk InduleDay02",
"Dragonblight - DB Tusk InduleDay03",
"Dragonblight - DB Tusk InduleNight01",
"Dragonblight - DB Tusk InduleNight02",
"Dragonblight - DB Tusk InduleNight03",
"Ebon Hold - EH AssaultUni01",
"Ebon Hold - EH AssaultUni02",
"Ebon Hold - EH AssaultUni03",
"Ebon Hold - EH AssaultUni04",
"Ebon Hold - EH AssaultUni05",
"Ebon Hold - EH AssaultUni06",
"Ebon Hold - EH AssaultUni07",
"Ebon Hold - EH GeneralWalkUni01",
"Ebon Hold - EH GeneralWalkUni02",
"Ebon Hold - EH GeneralWalkUni03",
"EnchantedForest - EnchantedForest01",
"EnchantedForest - EnchantedForest02",
"EnchantedForest - EnchantedForest03",
"EnchantedForest - EnchantedForest04",
"EnchantedForest - EnchantedForest05",
"Eversong - ES BuildingWalkDay01",
"Eversong - ES BuildingWalkDay02",
"Eversong - ES BuildingWalkNight01",
"Eversong - ES BuildingWalkNight02",
"Eversong - ES RuinsWalkDay01",
"Eversong - ES RuinsWalkDay02",
"Eversong - ES RuinsWalkDay03",
"Eversong - ES RuinsWalkNight01",
"Eversong - ES RuinsWalkNight02",
"Eversong - ES RuinsWalkNight03",
"Eversong - ES ScenicIntroNight01",
"Eversong - ES ScortchedWalkDay01",
"Eversong - ES ScortchedWalkDay02",
"Eversong - ES ScortchedWalkNight01",
"Eversong - ES ScortchedWalkNight02",
"Eversong - ES SilvermoonIntro01",
"Eversong - ES SilvermoonWalkDay01",
"Eversong - ES SilvermoonWalkDay02",
"Eversong - ES SilvermoonWalkDay03",
"Eversong - ES SilvermoonWalkNight01",
"Eversong - ES SilvermoonWalkNight02",
"Eversong - ES SilvermoonWalkNight03",
"Eversong - ES SunstriderWalkDay01",
"Eversong - ES SunstriderWalkDay02",
"Eversong - ES SunstriderWalkDay03",
"Eversong - ES SunstriderWalkNight01",
"Eversong - ES SunstriderWalkNight02",
"Eversong - ES SunstriderWalkNight03",
"EvilForest - DayEvilForest01",
"EvilForest - DayEvilForest02",
"EvilForest - DayEvilForest03",
"EvilForest - NightEvilForest01",
"EvilForest - NightEvilForest02",
"EvilForest - NightEvilForest03",
"Forest - DayForest01",
"Forest - DayForest02",
"Forest - DayForest03",
"Forest - NightForest01",
"Forest - NightForest02",
"Forest - NightForest03",
"Forest - NightForest04",
"Ghostlands - GL EversongDarkWalkUni01",
"Ghostlands - GL EversongDarkWalkUni02",
"Ghostlands - GL EversongDarkWalkUni03",
"Ghostlands - GL EversongDarkWalkUni04",
"Ghostlands - GL Forest1WalkDay01",
"Ghostlands - GL Forest1WalkDay02",
"Ghostlands - GL Forest1WalkNight01",
"Ghostlands - GL Forest2WalkDay01",
"Ghostlands - GL Forest2WalkNight01",
"Ghostlands - GL Forest2WalkNight02",
"Ghostlands - GL Forest3WalkDay01",
"Ghostlands - GL Forest3WalkNight01",
"Ghostlands - GL Forest3WalkNight02",
"Ghostlands - GL Forest3WalkNight03",
"Ghostlands - GL ScenicWalkUni01",
"Ghostlands - GL ScenicWalkUni02",
"Ghostlands - GL ScenicWalkUni03",
"Ghostlands - GL ShalandisWalkUni01",
"Ghostlands - GL ShalandisWalkUni02",
"Ghostlands - GL ShalandisWalkUni03",
"GhostGhostMusic03",
"GrizzlyHills - GH GeneralWalk A Day01",
"GrizzlyHills - GH GeneralWalk A Day02",
"GrizzlyHills - GH GeneralWalk A Day03",
"GrizzlyHills - GH GeneralWalk A Day04",
"GrizzlyHills - GH GeneralWalk A Night01",
"GrizzlyHills - GH GeneralWalk A Night02",
"GrizzlyHills - GH GeneralWalk B Day01",
"GrizzlyHills - GH GeneralWalk B Day02",
"GrizzlyHills - GH GeneralWalk B Night01",
"GrizzlyHills - GH GeneralWalk B Night02",
"GrizzlyHills - GH Intro1Uni01",
"GrizzlyHills - GH Intro2Uni01",
"GrizzlyHills - GH WalkDay01",
"GrizzlyHills - GH WalkDay02",
"GrizzlyHills - GH WalkDay03",
"GrizzlyHills - GH WalkDay04",
"GrizzlyHills - GH WalkDay05",
"GrizzlyHills - GH WalkDay06",
"GrizzlyHills - GH WalkDay07",
"GrizzlyHills - GH WalkDay08",
"GrizzlyHills - GH WalkDay09",
"GrizzlyHills - GH WalkNight01",
"GrizzlyHills - GH WalkNight02",
"GrizzlyHills - GH WalkNight03",
"GrizzlyHills - GH WalkNight04",
"GrizzlyHills - GH WalkNight05",
"GrizzlyHills - GH WalkNight06",
"HellfirePeninsula - BL HE OgreWalkUni01",
"HellfirePeninsula - BL HE OgreWalkUni02",
"HellfirePeninsula - HE ArmouryIntroUni01",
"HellfirePeninsula - HE CitadelDemonWalkUni01",
"HellfirePeninsula - HE CitadelDemonWalkUni02",
"HellfirePeninsula - HE CitadelIntroUni01",
"HellfirePeninsula - HE GeneralWalkUni01",
"HellfirePeninsula - HE GeneralWalkUni02",
"HellfirePeninsula - HE GeneralWalkUni03",
"HellfirePeninsula - HE GeneralWalkUni04",
"HellfirePeninsula - HE GeneralWalkUni05",
"HellfirePeninsula - HE PathOfGloryIntroUni01",
"HellfirePeninsula - HE RampartsWalkUni01",
"HellfirePeninsula - HE RampartsWalkUni02",
"HellfirePeninsula - HE StairsIntroUni01",
"HellfirePeninsula - HE WistfulIntroUni01",
"HellfirePeninsula - HE WistfulIntroUni02",
"HowlingFjord - HF DistWalkUni01",
"HowlingFjord - HF DistWalkUni02",
"HowlingFjord - HF DistWalkUni03",
"HowlingFjord - HF DistWalkUni04",
"HowlingFjord - HF DistWalkUni05",
"HowlingFjord - HF DistWalkUni06",
"HowlingFjord - HF DistWalkUni07",
"HowlingFjord - HF GeneralWalk Day01",
"HowlingFjord - HF GeneralWalk Day02",
"HowlingFjord - HF GeneralWalk Day03",
"HowlingFjord - HF GeneralWalk Day04",
"HowlingFjord - HF GeneralWalk Day05",
"HowlingFjord - HF GeneralWalk Day06",
"HowlingFjord - HF GeneralWalk Day07",
"HowlingFjord - HF GeneralWalk Night01",
"HowlingFjord - HF GeneralWalk Night02",
"HowlingFjord - HF GeneralWalk Night03",
"HowlingFjord - HF GeneralWalk Night04",
"HowlingFjord - HF Tusk KamaguaDay01",
"HowlingFjord - HF Tusk KamaguaDay02",
"HowlingFjord - HF Tusk KamaguaNight01",
"HowlingFjord - HF Tusk KamaguaNight02",
"IcecrownGlacier - IC GeneralIntro 01",
"IcecrownGlacier - IC GeneralIntro 02",
"IcecrownGlacier - IC GeneralIntro 03",
"IcecrownGlacier - IC GeneralWalk Day01",
"IcecrownGlacier - IC GeneralWalk Day02",
"IcecrownGlacier - IC GeneralWalk Day03",
"IcecrownGlacier - IC GeneralWalk Day04",
"IcecrownGlacier - IC GeneralWalk Night01",
"IcecrownGlacier - IC GeneralWalk Night02",
"IcecrownGlacier - IC GeneralWalk Night03",
"IcecrownGlacier - IC GeneralWalk Night04",
"IcecrownGlacier - IC GeneralWalk Night05",
"IcecrownRaid - IR BronzeJam",
"IcecrownRaid - IR CrimsonHall1",
"IcecrownRaid - IR CrimsonHall2",
"IcecrownRaid - IR CrimsonHall3",
"IcecrownRaid - IR CrimsonHall4",
"IcecrownRaid - IR ForgeofSouls1",
"IcecrownRaid - IR ForgeofSouls2",
"IcecrownRaid - IR ForgeofSouls3",
"IcecrownRaid - IR ForgeofSouls4",
"IcecrownRaid - IR Frostmourne1",
"IcecrownRaid - IR Frostmourne2",
"IcecrownRaid - IR Frostmourne3",
"IcecrownRaid - IR FrozenThrone 01",
"IcecrownRaid - IR FrozenThrone 02",
"IcecrownRaid - IR FrozenThrone 03",
"IcecrownRaid - IR FrozenThrone 04",
"IcecrownRaid - IR FrozenThrone 05",
"IcecrownRaid - IR FrozenThrone 06",
"IcecrownRaid - IR FrozenThrone 07",
"IcecrownRaid - IR Gunships",
"IcecrownRaid - IR GunStrings",
"IcecrownRaid - IR HallsofChase",
"IcecrownRaid - IR HallsofReflection",
"IcecrownRaid - IR IceFortress",
"IcecrownRaid - IR IceFortress1",
"IcecrownRaid - IR IceFortress2",
"IcecrownRaid - IR IceFortress3",
"IcecrownRaid - IR IceFortress4",
"IcecrownRaid - IR LadyortheLich",
"IcecrownRaid - IR LetHimPass",
"IcecrownRaid - IR LightsHammer1",
"IcecrownRaid - IR LightsHammer2",
"IcecrownRaid - IR LightsHammer3",
"IcecrownRaid - IR LightsHammer4",
"IcecrownRaid - IR LightsHammer5",
"IcecrownRaid - IR LightsHammer6",
"IcecrownRaid - IR ReflectedHalls1",
"IcecrownRaid - IR ReflectedHalls2",
"IcecrownRaid - IR ReflectedHalls3",
"IcecrownRaid - IR ReflectedHalls4",
"IcecrownRaid - IR ReflectedHalls5",
"IcecrownRaid - IR RunK 01",
"IcecrownRaid - IR RunK 02",
"IcecrownRaid - IR RunK 03",
"IcecrownRaid - IR RunL 01",
"IcecrownRaid - IR RunL 02",
"IcecrownRaid - IR Sindragosa",
"IcecrownRaid - IR SindraStrings",
"IcecrownRaid - IR StingH 01",
"IcecrownRaid - IR StingH 02",
"IcecrownRaid - IR StingH 03",
"IcecrownRaid - IR StingH 04",
"IcecrownRaid - IR StingH 05",
"IcecrownRaid - IR StingH 06",
"IcecrownRaid - IR Summit1",
"IcecrownRaid - IR Summit2",
"IcecrownRaid - IR Summit3",
"IcecrownRaid - IR Summit4",
"IcecrownRaid - IR Summit5",
"IcecrownRaid - IR WalkA 01",
"IcecrownRaid - IR WalkA 02",
"IcecrownRaid - IR WalkA 03",
"IcecrownRaid - IR WalkA 04",
"IcecrownRaid - IR WalkA 05",
"IcecrownRaid - IR WalkA 06",
"IcecrownRaid - IR WalkB 01",
"IcecrownRaid - IR WalkD 01",
"IcecrownRaid - IR WalkD 02",
"IcecrownRaid - IR WalkD 03",
"IcecrownRaid - IR WalkD 04",
"IcecrownRaid - IR WalkD 05",
"IcecrownRaid - IR WalkD 06",
"IcecrownRaid - IR WalkE 01",
"IcecrownRaid - IR WalkE 02",
"IcecrownRaid - IR WalkE 03",
"IcecrownRaid - IR WalkE 04",
"IcecrownRaid - IR WalkE 05",
"IcecrownRaid - IR WalkF 01",
"IcecrownRaid - IR WalkF 02",
"IcecrownRaid - IR WalkF 03",
"IcecrownRaid - IR WalkF 04",
"IcecrownRaid - IR WalkF 05",
"IcecrownRaid - IR WalkF 06",
"IcecrownRaid - IR WalkF 07",
"IcecrownRaid - IR WalkF 08",
"IcecrownRaid - IR WalkG 01",
"IcecrownRaid - IR WalkG 02",
"IcecrownRaid - IR WalkG 03",
"IcecrownRaid - IR WalkG 04",
"IcecrownRaid - IR WalkG 05",
"IcecrownRaid - IR WalkG 06",
"IcecrownRaid - IR WalkJ 01",
"IcecrownRaid - IR WalkJ 02",
"IcecrownRaid - IR WalkJ 03",
"IcecrownRaid - IR WalkJ 04",
"IcecrownRaid - IR WalkJ 05",
"IcecrownRaid - IR WalkJ 06",
"IcecrownRaid - IR WalkM 01",
"IcecrownRaid - IR WalkZ 01",
"IcecrownRaid - IR WalkZ 02",
"Jungle - DayJungle01",
"Jungle - DayJungle02",
"Jungle - DayJungle03",
"Jungle - NightJungle01",
"Jungle - NightJungle02",
"Jungle - NightJungle03",
"Karazhan - KA BackstageWalkUni01",
"Karazhan - KA BackstageWalkUni02",
"Karazhan - KA FoyerIntroUni01",
"Karazhan - KA FoyerWalkUni01",
"Karazhan - KA FoyerWalkUni02",
"Karazhan - KA FoyerWalkUni03",
"Karazhan - KA FoyerWalkUni04",
"Karazhan - KA GeneralWalkUni01",
"Karazhan - KA GeneralWalkUni02",
"Karazhan - KA GeneralWalkUni03",
"Karazhan - KA GeneralWalkUni04",
"Karazhan - KA GeneralWalkUni05",
"Karazhan - KA GeneralWalkUni06",
"Karazhan - KA GeneralWalkUni07",
"Karazhan - KA LibraryWalkUni01",
"Karazhan - KA LibraryWalkUni02",
"Karazhan - KA LibraryWalkUni03",
"Karazhan - KA LibraryWalkUni04",
"Karazhan - KA MalchezarWalkUni01",
"Karazhan - KA MalchezarWalkUni02",
"Karazhan - KA MalchezarWalkUni03",
"Karazhan - KA OperaHarpsiWalkUni01",
"Karazhan - KA OperaOrganWalkUni01",
"Karazhan - KA StableIntroUni01",
"Karazhan - KA StableWalkUni01",
"Karazhan - KA StableWalkUni02",
"Karazhan - KA StableWalkUni03",
"Karazhan - KA TowerWalkUni01",
"Karazhan - KA TowerWalkUni02",
"Karazhan - KA TowerWalkUni03",
"LakeWintergrasp - WG Contested 01",
"LakeWintergrasp - WG Contested 02",
"LakeWintergrasp - WG Contested 03",
"LakeWintergrasp - WG GeneralWalk 01",
"LakeWintergrasp - WG GeneralWalk 02",
"LakeWintergrasp - WG GeneralWalk 03",
"LakeWintergrasp - WG GeneralWalk 04",
"LakeWintergrasp - WG GeneralWalk 05",
"Mountain - DayMountain01",
"Mountain - DayMountain02",
"Mountain - DayMountain03",
"Mountain - NightMountain01",
"Mountain - NightMountain02",
"Mountain - NightMountain03",
"Mountain - NightMountain04",
"Nagrand - NA DiamondIntroUni01",
"Nagrand - NA GeneralWalkDay01",
"Nagrand - NA GeneralWalkDay02",
"Nagrand - NA GeneralWalkDay03",
"Nagrand - NA GeneralWalkNight01",
"Nagrand - NA GeneralWalkNight02",
"Nagrand - NA GeneralWalkNight03",
"Naxxramas - NaxxramasAbominationBoss1",
"Naxxramas - NaxxramasAbominationBoss2",
"Naxxramas - NaxxramasAbominationWing1",
"Naxxramas - NaxxramasAbominationWing2",
"Naxxramas - NaxxramasAbominationWing3",
"Naxxramas - NaxxramasFrostwyrm1",
"Naxxramas - NaxxramasFrostwyrm2",
"Naxxramas - NaxxramasFrostwyrm3",
"Naxxramas - NaxxramasFrostwyrm4",
"Naxxramas - NaxxramasHubBase1",
"Naxxramas - NaxxramasHubBase2",
"Naxxramas - NaxxramasKelThuzad1",
"Naxxramas - NaxxramasKelThuzad2",
"Naxxramas - NaxxramasKelThuzad3",
"Naxxramas - NaxxramasPlagueBoss1",
"Naxxramas - NaxxramasPlagueWing1",
"Naxxramas - NaxxramasPlagueWing2",
"Naxxramas - NaxxramasPlagueWing3",
"Naxxramas - NaxxramasSpiderBoss1",
"Naxxramas - NaxxramasSpiderBoss2",
"Naxxramas - NaxxramasSpiderWing1",
"Naxxramas - NaxxramasSpiderWing2",
"Naxxramas - NaxxramasSpiderWing3",
"Naxxramas - NaxxramasWalking1",
"Naxxramas - NaxxramasWalking2",
"Naxxramas - NaxxramasWalking3",
"Naxxramas - NaxxramasWalking4",
"Naxxramas - NaxxramasWalking5",
"Naxxramas - NaxxramasWalking6",
"Netherstorm - NS GeneralWalkUni01",
"Netherstorm - NS GeneralWalkUni02",
"Netherstorm - NS GeneralWalkUni03",
"Netherstorm - NS GeneralWalkUni04",
"Netherstorm - NS GeneralWalkUni05",
"Netherstorm - NS GeneralWalkUni06",
"Netherstorm - NS GeneralWalkUni07",
"Netherstorm - NS GeneralWalkUni08",
"Netherstorm - NS GeneralWalkUni09",
"Netherstorm - NS GeneralWalkUni10",
"Netherstorm - NS MushroomIntroUni01",
"Netherstorm - NS MushroomIntroUni02",
"Netherstorm - NS MushroomIntroUni03",
"Netherstorm - NS NetherplantIntroUni01",
"Netherstorm - NS NetherplantIntroUni02",
"Netherstorm - NS NetherplantIntroUni03",
"Netherstorm - NS NetherplantIntroUni04",
"Nexus - NZ NexusActionWalkUni01",
"Nexus - NZ NexusActionWalkUni02",
"Nexus - NZ NexusActionWalkUni03",
"Nexus - NZ NexusActionWalkUni04",
"Nexus - NZ NexusActionWalkUni05",
"Nexus - NZ NexusHailWalkUni01",
"Nexus - NZ NexusHailWalkUni02",
"Nexus - NZ NexusPulseWalkUni01",
"Nexus - NZ NexusPulseWalkUni02",
"Nexus - NZ NexusQuietWalkUni01",
"Nexus - NZ NexusQuietWalkUni02",
"Nexus - NZ NexusQuietWalkUni03",
"Nexus - NZ NexusQuietWalkUni04",
"Northrend - IronDwarf - NR Dwarf GeneralWalkA Day01",
"Northrend - IronDwarf - NR Dwarf GeneralWalkA Night01",
"Northrend - IronDwarf - NR Dwarf GeneralWalkADark Uni01",
"Northrend - IronDwarf - NR Dwarf GeneralWalkB Day02",
"Northrend - IronDwarf - NR Dwarf GeneralWalkB Night02",
"Northrend - IronDwarf - NR Dwarf GeneralWalkB Uni02",
"Northrend - IronDwarf - NR Dwarf GeneralWalkC Day03",
"Northrend - IronDwarf - NR Dwarf GeneralWalkC Night03",
"Northrend - IronDwarf - NR Dwarf GeneralWalkC Uni03",
"Northrend - IronDwarf - NR Dwarf GeneralWalkCDark Uni04",
"Northrend - IronDwarf - NR Dwarf GeneralWalkD Day04",
"Northrend - IronDwarf - NR Dwarf GeneralWalkD Night04",
"Northrend - IronDwarf - NR Dwarf GeneralWalkDDark Uni05",
"Northrend - NorthrendTransport - NR NorthrendTransportGeneralDay",
"Northrend - NorthrendTransport - NR NorthrendTransportGeneralNight",
"Northrend - Orc - NR Orc General Intro01",
"Northrend - Orc - NR Orc GeneralWalk Day01",
"Northrend - Orc - NR Orc GeneralWalk Day02",
"Northrend - Orc - NR Orc GeneralWalk Day03",
"Northrend - Orc - NR Orc GeneralWalk Day04",
"Northrend - Orc - NR Orc GeneralWalk Night01",
"Northrend - Orc - NR Orc GeneralWalk Night02",
"Northrend - Orc - NR Orc GeneralWalk Night03",
"Northrend - Taunka - NR Taunka GeneralWalkA Day01",
"Northrend - Taunka - NR Taunka GeneralWalkA Night01",
"Northrend - Taunka - NR Taunka GeneralWalkA Uni01",
"Northrend - Taunka - NR Taunka GeneralWalkB Day02",
"Northrend - Taunka - NR Taunka GeneralWalkB Night02",
"Northrend - Taunka - NR Taunka GeneralWalkC Day03",
"Northrend - Taunka - NR Taunka GeneralWalkC Night03",
"Northrend - Taunka - NR Taunka GeneralWalkD Day04",
"Northrend - Taunka - NR Taunka GeneralWalkD Night04",
"Northrend - Taunka - NR Taunka GeneralWalkD Uni02",
"Northrend - Taunka - NR Taunka GeneralWalkE Uni03",
"Northrend - Troll - NR Troll General01",
"Northrend - Troll - NR Troll General02",
"Northrend - Troll - NR Troll General03",
"Northrend - Troll - NR Troll General04",
"OS1",
"OS2",
"OS3",
"OS4",
"OS5",
"OutlandGeneral - OL ActionWalkUni01",
"OutlandGeneral - OL AllianceBaseWalkUni01",
"OutlandGeneral - OL AllianceBaseWalkUni02",
"OutlandGeneral - OL ArakkoaIntroUni01",
"OutlandGeneral - OL ArakkoaIntroUni02",
"OutlandGeneral - OL BloodElfBaseWalkUni01",
"OutlandGeneral - OL BloodElfBaseWalkUni02",
"OutlandGeneral - OL BurningLegionIntroUni01",
"OutlandGeneral - OL BurningLegionIntroUni02",
"OutlandGeneral - OL CenarionIntroUni01",
"OutlandGeneral - OL CenarionIntroUni02",
"OutlandGeneral - OL CenarionIntroUni03",
"OutlandGeneral - OL Corrupt01",
"OutlandGeneral - OL Corrupt02",
"OutlandGeneral - OL Corrupt03",
"OutlandGeneral - OL Corrupt04",
"OutlandGeneral - OL Corrupt05",
"OutlandGeneral - OL Corrupt06",
"OutlandGeneral - OL Corrupt07",
"OutlandGeneral - OL CorruptIntro",
"OutlandGeneral - OL CrystalIntroUni01",
"OutlandGeneral - OL CrystalIntroUni02",
"OutlandGeneral - OL CrystalIntroUni03",
"OutlandGeneral - OL DemonIntroUni01",
"OutlandGeneral - OL DraeneiBaseWalkUni01",
"OutlandGeneral - OL DraeneiBaseWalkUni02r",
"OutlandGeneral - OL FelOrcIntroUni01",
"OutlandGeneral - OL FelOrcIntroUni02",
"OutlandGeneral - OL HistoricIntroUni01",
"OutlandGeneral - OL HordeBaseWalkUni01",
"OutlandGeneral - OL HordeBaseWalkUni02",
"OutlandGeneral - OL HordeBaseWalkUni03",
"OutlandGeneral - OL HordeBaseWalkUni04",
"OutlandGeneral - OL IllidansArmyIntroUni01",
"OutlandGeneral - OL OgreIntroUni01",
"OutlandGeneral - OL OgreIntroUni02",
"OutlandGeneral - OL OrcIntroUni01",
"OutlandGeneral - OL OrcIntroUni02",
"OutlandGeneral - OL OrcIntroUni03",
"OutlandGeneral - OL OrcIntroUni04",
"OutlandGeneral - OL ScenicIntroUni01",
"OutlandGeneral - OL ShamanIntroUni01",
"OutlandGeneral - OL ShamanIntroUni02",
"Plains - DayPlains01",
"Plains - DayPlains02",
"Plains - NightPlains01",
"Plains - NightPlains02",
"PVP - PVP6 01",
"PVP - PVP6 02",
"PVP - PVP7 01",
"PVP - PVP7 02",
"PVP - PVP7Moment1 01",
"PVP - PVP7Moment1 02",
"PVP - PVP7Moment2 01",
"PVP - PVP7Moment2 02",
"PVP - PVP7Moment3 01",
"PVP - PVP7StingerEnd 01",
"PVP - PVP7StingerIntro 01",
"PVP - PvP1",
"PVP - PvP2",
"PVP - PvP3",
"PVP - PvP4",
"PVP - PvP5",
"ShadowmoonValley - SV GeneralWalkUni01",
"ShadowmoonValley - SV GeneralWalkUni02",
"ShadowmoonValley - SV GeneralWalkUni03",
"ShadowmoonValley - SV GeneralWalkUni04",
"ShadowmoonValley - SV GeneralWalkUni05",
"ShadowmoonValley - SV GeneralWalkUni06",
"SholazarBasin - SB CrystalsWalkUni01",
"SholazarBasin - SB CrystalsWalkUni02",
"SholazarBasin - SB FireWalkUni01",
"SholazarBasin - SB FireWalkUni02",
"SholazarBasin - SB FireWalkUni03",
"SholazarBasin - SB FireWalkUni04",
"SholazarBasin - SB LifebloodCaveWalkUni01",
"SholazarBasin - SB LifebloodCaveWalkUni02",
"SholazarBasin - SB LifebloodCaveWalkUni03",
"SholazarBasin - SB MakersTerraceWalkUni01",
"SholazarBasin - SB MakersTerraceWalkUni02",
"SholazarBasin - SB PathofLifeWardenWalkUni01",
"SholazarBasin - SB PathofLifeWardenWalkUni02",
"SholazarBasin - SB SholazarWalkDay01",
"SholazarBasin - SB SholazarWalkDay02",
"SholazarBasin - SB SholazarWalkDay03",
"SholazarBasin - SB SholazarWalkDay04",
"SholazarBasin - SB SholazarWalkDay05",
"SholazarBasin - SB SholazarWalkDay06",
"SholazarBasin - SB SholazarWalkNight01",
"SholazarBasin - SB SholazarWalkNight02",
"SholazarBasin - SB SholazarWalkNight03",
"SholazarBasin - SB SholazarWalkNight04",
"SholazarBasin - SB SholazarWalkNight05",
"StormPeaks - SP GeneralWalkA Day01",
"StormPeaks - SP GeneralWalkA Night01",
"StormPeaks - SP GeneralWalkADark Uni01",
"StormPeaks - SP GeneralWalkB Day02",
"StormPeaks - SP GeneralWalkB Night02",
"StormPeaks - SP GeneralWalkB Uni02",
"StormPeaks - SP GeneralWalkC Day03",
"StormPeaks - SP GeneralWalkC Night03",
"StormPeaks - SP GeneralWalkC Uni03",
"StormPeaks - SP GeneralWalkD Day04",
"StormPeaks - SP GeneralWalkD Night04",
"StormPeaks - SP GeneralWalkD Uni04",
"StormPeaks - SP GeneralWalkE Day05",
"StormPeaks - SP GeneralWalkE Night05",
"StormPeaks - SP GeneralWalkE Uni05",
"StratholmePast - CT StratholmePastAlleyEnd",
"StratholmePast - CT StratholmePastAlleyIntro",
"StratholmePast - CT StratholmePastBattleWalk01",
"StratholmePast - CT StratholmePastBattleWalk02",
"StratholmePast - CT StratholmePastBattleWalk03",
"StratholmePast - CT StratholmePastEndStinger",
"StratholmePast - CT StratholmePastIndoorsIntro",
"StratholmePast - CT StratholmePastIntro",
"StratholmePast - CT StratholmePastMalGanis",
"StratholmePast - CT StratholmePastOutdoorsIntro",
"StratholmePast - CT StratholmePastOutdoorsWalkANight",
"StratholmePast - CT StratholmePastOutdoorsWalkAUni",
"StratholmePast - CT StratholmePastOutdoorsWalkBNight",
"StratholmePast - CT StratholmePastOutdoorsWalkBUni",
"StratholmePast - CT StratholmePastWalkUni",
"Sunwell - SW AssemblyChamberWalkUni01",
"Sunwell - SW AssemblyChamberWalkUni02",
"Sunwell - SW FelEnergyWalkUni01",
"Sunwell - SW IsleDarkWalkUni01",
"Sunwell - SW IsleDarkWalkUni02",
"Sunwell - SW IsleDarkWalkUni03",
"Sunwell - SW IsleLightWalkUni01",
"Sunwell - SW IsleLightWalkUni02",
"Sunwell - SW IsleLightWalkUni03",
"Sunwell - SW IsleMedWalkUni01",
"Sunwell - SW IsleMedWalkUni02",
"Sunwell - SW IsleMedWalkUni03",
"Sunwell - SW MagistersArrivalWalkUni01",
"Sunwell - SW MagistersAsylumWalkUni01",
"Sunwell - SW MagistersAsylumWalkUni02",
"Sunwell - SW MagistersAsylumWalkUni03",
"Sunwell - SW MagistersTerraceWalkUni01",
"Sunwell - SW MagistersTerraceWalkUni02",
"Sunwell - SW MagistersTerraceWalkUni03",
"Sunwell - SW MagistersTerraceWalkUni04",
"Sunwell - SW MagistersTerraceWalkUni05",
"Sunwell - SW PlateauSunwellArrivalWalkUni01",
"Sunwell - SW PlateauSunwellWalkUni01",
"Sunwell - SW PlateauSunwellWalkUni02",
"Sunwell - SW PlateauSunwellWalkUni03",
"Sunwell - SW PlateauSunwellWalkUni04",
"Sunwell - SW PlateauSunwellWalkUni05",
"Sunwell - SW PlateauSunwellWalkUni06",
"Sunwell - SW QuelDanasWalkUni01",
"Sunwell - SW QuelDanasWalkUni02",
"Sunwell - SW SanctumWalkUni01",
"Sunwell - SW ShorelAranWalkUni01",
"Sunwell - SW SunwellBombingRunUni01",
"Sunwell - SW SunwellFlybyUni01",
"Sunwell - SW TheWellWalkUni01",
"Sunwell - SW TheWellWalkUni02",
"Sunwell - SW TheWellWalkUni03",
"TavernAlliance - TavernAlliance01",
"TavernAlliance - TavernAlliance02",
"TavernDwarf - RA DwarfTavern1A",
"TavernDwarf - RA DwarfTavern1B",
"TavernDwarf - RA DwarfTavern2A",
"TavernDwarf - RA DwarfTavern2B",
"TavernDwarf - RA DwarfTavern3",
"TavernHorde - TavernHorde01",
"TavernHorde - TavernHorde02",
"TavernHorde - TavernHorde03",
"TavernHorde - undead dance",
"TavernHuman - RA HumanTavern1A",
"TavernHuman - RA HumanTavern1B",
"TavernHuman - RA HumanTavern2A",
"TavernHuman - RA HumanTavern2B",
"TavernHuman - RA Tavern1 RevisitedA",
"TavernHuman - RA Tavern1 RevisitedB",
"TavernNightElf - RA TempleOfTheMoonA",
"TavernNightElf - RA TempleOfTheMoonB",
"TavernOrc - RA OrcRestArea1A",
"TavernOrc - RA OrcRestArea1B",
"TavernOrc - RA OrcRestArea2A",
"TavernOrc - RA OrcRestArea2B",
"TavernOrc - RA OrcRestArea3A",
"TavernOrc - RA OrcRestArea3B",
"TavernPirate - RA PirateTavern1A",
"TavernPirate - RA PirateTavern1B",
"TavernPirate - RA PirateTavern2A",
"TavernPirate - RA PirateTavern2B",
"TavernPirate - RA PirateTavern3A",
"TavernPirate - RA PirateTavern3B",
"TavernTauren - RA TaurenRestArea1A",
"TavernTauren - RA TaurenRestArea1B",
"TavernTauren - RA TaurenRestArea2A",
"TavernTauren - RA TaurenRestArea2B",
"TavernTauren - RA TaurenRestArea3A",
"TavernTauren - RA TaurenRestArea3B",
"TavernUndead - RA UndeadTavern1A",
"TavernUndead - RA UndeadTavern1B",
"TavernUndead - RA UndeadTavern2",
"TavernUndead - RA UndeadTavern3A",
"TavernUndead - RA UndeadTavern3B",
"TempestKeep - TK TempestKeep AMB 11",
"TempestKeep - TK TempestKeep AMB 12",
"TempestKeep - TK TempestKeep AMB 13",
"TempestKeep - TK TempestKeep AMB 14",
"TempestKeep - TK TempestKeep AMB 16",
"TempestKeep - TK TempestKeep AMB 17",
"TempestKeep - TK TempestKeep AMB 18",
"TempestKeep - TK TempestKeep AMB 19",
"TempestKeep - TK TempestKeep AMB 20",
"TempestKeep - TK TempestKeep AMB 22",
"TempestKeep - TK TempestKeep AMB 23",
"TempestKeep - TK TempestKeep BTL10",
"TempestKeep - TK TempestKeep BTL11",
"TempestKeep - TK TempestKeep BTL13",
"TempestKeep - TK TempestKeep STG14",
"TempestKeep - TK TempestKeep STG15",
"TempestKeep - TK TempestKeep STG16",
"Terokkar - TF AuchindounWalkUni01",
"Terokkar - TF AuchindounWalkUni02",
"Terokkar - TF AuchindounWalkUni03",
"Terokkar - TF BoneWalkUni01",
"Terokkar - TF BoneWalkUni02",
"Terokkar - TF BoneWalkUni03",
"Terokkar - TF BoneWalkUni04",
"Terokkar - TF ForestWalkUni01",
"Terokkar - TF ForestWalkUni02",
"Terokkar - TF ForestWalkUni03",
"Terokkar - TF ShattrathWalkUni01",
"Terokkar - TF ShattrathWalkUni02",
"Terokkar - TF ShattrathWalkUni03",
"Terokkar - TF ShattrathWalkUni04",
"Terokkar - TF ShattrathWalkUni05",
"Terokkar - TF ShattrathWalkUni06",
"Ulduar - UL LightningBattleWalk",
"Ulduar - UL LightningGeneralWalk01",
"Ulduar - UL LightningGeneralWalk02",
"Ulduar - UL LightningGeneralWalk03",
"Ulduar - UL LightningIntro",
"Ulduar - UL StoneBattleWalk",
"Ulduar - UL StoneGeneralWalk01",
"Ulduar - UL StoneGeneralWalk02",
"Ulduar - UL StoneGeneralWalk03",
"Ulduar - UL StoneIntro",
"UlduarRaidExt - UR UlduarRaidExtAction01",
"UlduarRaidExt - UR UlduarRaidExtAction02",
"UlduarRaidExt - UR UlduarRaidExtAction03",
"UlduarRaidExt - UR UlduarRaidExtAction04",
"UlduarRaidExt - UR UlduarRaidExtAction05",
"UlduarRaidExt - UR UlduarRaidExtAction06",
"UlduarRaidExt - UR UlduarRaidExtAction07",
"UlduarRaidExt - UR UlduarRaidExtAction08",
"UlduarRaidExt - UR UlduarRaidExtAction09",
"UlduarRaidExt - UR UlduarRaidExtAction10",
"UlduarRaidExt - UR UlduarRaidExtAction11",
"UlduarRaidExt - UR UlduarRaidExtAction12",
"UlduarRaidExt - UR UlduarRaidExtAction13",
"UlduarRaidExt - UR UlduarRaidExtAction14",
"UlduarRaidExt - UR UlduarRaidExtAction15",
"UlduarRaidExt - UR UlduarRaidExtAction16",
"UlduarRaidExt - UR UlduarRaidExtIntro01",
"UlduarRaidExt - UR UlduarRaidExtIntro02",
"UlduarRaidExt - UR UlduarRaidExtIntro03",
"UlduarRaidExt - UR UlduarRaidExtIntro04",
"UlduarRaidExt - UR UlduarRaidExtIntro05",
"UlduarRaidExt - UR UlduarRaidExtIntro06",
"UlduarRaidExt - UR UlduarRaidExtIntro07",
"UlduarRaidExt - UR UlduarRaidExtIntro08",
"UlduarRaidExt - UR UlduarRaidExtIntro09",
"UlduarRaidExt - UR UlduarRaidExtWalk01",
"UlduarRaidExt - UR UlduarRaidExtWalk02",
"UlduarRaidExt - UR UlduarRaidExtWalk03",
"UlduarRaidExt - UR UlduarRaidExtWalk04",
"UlduarRaidExt - UR UlduarRaidExtWalk05",
"UlduarRaidExt - UR UlduarRaidExtWalk06",
"UlduarRaidExt - UR UlduarRaidExtWalk07",
"UlduarRaidExt - UR UlduarRaidExtWalk08",
"UlduarRaidExt - UR UlduarRaidExtWalk09",
"UlduarRaidExt - UR UlduarRaidExtWalk10",
"UlduarRaidExt - UR UlduarRaidExtWalk11",
"UlduarRaidInt - UR AlgalonBattle01Walk",
"UlduarRaidInt - UR AlgalonBattle02Walk",
"UlduarRaidInt - UR AlgalonHeroIntro",
"UlduarRaidInt - UR AlgalonPlanetaryHallWalk",
"UlduarRaidInt - UR AlgalonVoicesWalk",
"UlduarRaidInt - UR FourSigilsHallWalk",
"UlduarRaidInt - UR FourSigilsHeroIntro",
"UlduarRaidInt - UR HallsInstrumentalWalk",
"UlduarRaidInt - UR HallsofIronHeroEvent",
"UlduarRaidInt - UR HallsPastWalk",
"UlduarRaidInt - UR MimironBWalk",
"UlduarRaidInt - UR MimironCWalk",
"UlduarRaidInt - UR MimironDWalk",
"UlduarRaidInt - UR MimironEWalk",
"UlduarRaidInt - UR MimironFWalk",
"UlduarRaidInt - UR MimironGhostsWalk",
"UlduarRaidInt - UR MimironHeroIntro",
"UlduarRaidInt - UR SigilGhostsWalk",
"UlduarRaidInt - UR TitanGhostsWalk",
"UlduarRaidInt - UR TitanHallsHeroWalk",
"UlduarRaidInt - UR TitanMechWalk",
"UlduarRaidInt - UR TitanOrchestraIntro",
"UlduarRaidInt - UR TitanSigilsWalk",
"UlduarRaidInt - UR UlduarToneWalk",
"Utgarde Keep - UK GeneralWalkUni01",
"Utgarde Keep - UK GeneralWalkUni02",
"Utgarde Keep - UK GeneralWalkUni03",
"Utgarde Keep - UK GeneralWalkUni04",
"Utgarde Keep - UK GeneralWalkUni05",
"Utgarde Keep - UK QuietWalkUni01",
"Utgarde Keep - UK QuietWalkUni02",
"VioletHold - VH GeneralWalkUni01",
"VioletHold - VH GeneralWalkUni02",
"VioletHold - VH GeneralWalkUni03",
"Volcanic - DayVolcanic01",
"Volcanic - DayVolcanic02",
"Volcanic - NightVolcanic01",
"Volcanic - NightVolcanic02",
"WanderingIsle - WanderingIsleA Hero 01",
"WanderingIsle - WanderingIsleA 01",
"WanderingIsle - WanderingIsleA 02",
"WanderingIsle - WanderingIsleA 03",
"WanderingIsle - WanderingIsleA 04",
"WanderingIsle - WanderingIsleA 05",
"WanderingIsle - WanderingIsleB Hero 01",
"WanderingIsle - WanderingIsleB 01",
"WanderingIsle - WanderingIsleC Hero 01",
"WanderingIsle - WanderingIsleC 01",
"WanderingIsle - WanderingIsleC 02",
"WanderingIsle - WanderingIsleC 03",
"WanderingIsle - WanderingIsleC 04",
"ZangarMarsh - ZA CoilfangWalkUni01",
"ZangarMarsh - ZA CoilfangWalkUni02",
"ZangarMarsh - ZA CoilfangWalkUni03",
"ZangarMarsh - ZA GeneralWalkUni01",
"ZangarMarsh - ZA GeneralWalkUni02",
"ZangarMarsh - ZA GeneralWalkUni03",
"ZangarMarsh - ZA GeneralWalkUni04",
"ZangarMarsh - ZA GeneralWalkUni05",
"ZangarMarsh - ZA GeneralWalkUni06",
"Zulaman - ZA zulaman AMB10",
"Zulaman - ZA zulaman AMB11",
"Zulaman - ZA zulaman AMB12",
"Zulaman - ZA zulaman AMB13",
"Zulaman - ZA zulaman AMB14",
"Zulaman - ZA zulaman AMB15",
"Zulaman - ZA zulaman BTL11",
"Zulaman - ZA zulaman BTL12",
"Zulaman - ZA zulaman BTL13",
"Zulaman - ZA zulaman BTL14",
"Zulaman - ZA zulaman BTL15",
"Zulaman - ZA zulaman VCT10",
"ZulDrak - ZD GeneralIntro 01",
"ZulDrak - ZD GeneralIntro 02",
"ZulDrak - ZD GeneralIntro 03",
"ZulDrak - ZD GeneralIntro 04",
"ZulDrak - ZD GeneralIntro 05",
"ZulDrak - ZD GeneralIntro 06",
"ZulDrak - ZD GeneralWalk Day01",
"ZulDrak - ZD GeneralWalk Day02",
"ZulDrak - ZD GeneralWalk Day03",
"ZulDrak - ZD GeneralWalk Day04",
"ZulDrak - ZD GeneralWalk Night01",
"ZulDrak - ZD GeneralWalk Night02",
"ZulDrak - ZD GeneralWalk Night03",
"ZulDrak - ZD GeneralWalk Night04",
"ZulDrak - ZD HarKoa Intro01",
"ZulDrak - ZD HarKoa Intro02",
"ZulDrak - ZD MamToth Intro01",
"ZulDrak - ZD MamToth Intro02",
"ZulDrak - ZD QuetzLun Intro01",
"ZulDrak - ZD QuetzLun Intro02",
"ZulDrak - ZD Rhunok Intro01",
"ZulDrak - ZD Rhunok Intro02",
"ZulDrak - ZD Sseratus Intro01",
"ZulDrak - ZD Sseratus Intro02",
"Draenor - AHerosSacrifice V1",
"Draenor - AHerosSacrifice V2",
"Draenor - AHerosSacrifice V3a",
"Draenor - AHerosSacrifice V3b",
"Draenor - AHerosSacrifice V4",
"Draenor - AHerosSacrifice V5",
"Draenor - ALightInTheDarkness V1",
"Draenor - ALightInTheDarkness V2",
"Draenor - ALightInTheDarkness V3",
"Draenor - ALightInTheDarkness V3a",
"Draenor - ASiegeOfWorlds MainTitle",
"Draenor - Arak2 H",
"Draenor - ArmyLife H",
"Draenor - Army A",
"Draenor - Army Stinger1",
"Draenor - Army Stinger2",
"Draenor - BFreedom H1",
"Draenor - BFreedon H2",
"Draenor - Blackrock A",
"Draenor - Blackrock B",
"Draenor - Blackrock C",
"Draenor - Blackrock D",
"Draenor - Blackrock E",
"Draenor - Blackrock H",
"Draenor - CallOfTheWarrior A",
"Draenor - CallOfTheWarrior C",
"Draenor - CallOfTheWarrior H",
"Draenor - CavernsOfLife H",
"Draenor - ChieftansGather H",
"Draenor - ColdMountain Duet H",
"Draenor - EagleOfDraenor H",
"Draenor - Eagle A",
"Draenor - Eagle B",
"Draenor - Eagle C",
"Draenor - Eagle D",
"Draenor - ElunesShadow A",
"Draenor - ElunesShadow B",
"Draenor - ElunesShadow C",
"Draenor - ElunesShadow H",
"Draenor - EternalNight H",
"Draenor - EtherealEmbers C",
"Draenor - EtherealEmbers D",
"Draenor - EtherealEmbers E",
"Draenor - EtherealEmbers F",
"Draenor - EtherealEmbers H",
"Draenor - EtherealEssence H1",
"Draenor - EtherealEssence H2",
"Draenor - FelWasteland A",
"Draenor - FelWasteland B",
"Draenor - FelWasteland C",
"Draenor - FelWasteland H",
"Draenor - Foreshadowing H",
"Draenor - Forsaken A",
"Draenor - Forsaken H",
"Draenor - GardensOfKarabor A",
"Draenor - GardensOfKarabor B",
"Draenor - GardensOfKarabor H",
"Draenor - GarrisonBuildingComplete",
"Draenor - GarrisonBuildingComplete2",
"Draenor - Grinspiration A",
"Draenor - Grinspiration B",
"Draenor - Grinspiration C",
"Draenor - Grinspiration H1",
"Draenor - Grinspiration H2",
"Draenor - GrommashHellscream V1",
"Draenor - GrommashHellscream V2a",
"Draenor - GrommashHellscream V2b",
"Draenor - GrommashHellscream V3",
"Draenor - HerdingClans H",
"Draenor - IronDawn V1",
"Draenor - IronDawn V2",
"Draenor - IronDawn V3a",
"Draenor - IronDawn V3b",
"Draenor - IronDawn V4",
"Draenor - KeepersOfTheTemple H",
"Draenor - KhadgarsPlan V1",
"Draenor - KhadgarsPlan V2",
"Draenor - KhadgarsPlan V3",
"Draenor - KhadgarsPlan V4",
"Draenor - LaboriousMisery A",
"Draenor - LaboriousMisery H",
"Draenor - MagnificentDesolation2 A2",
"Draenor - MagnificentDesolation2 H",
"Draenor - MagnificentDesolation2 H1",
"Draenor - MagnificentDesolation2 H2",
"Draenor - MagnificentDesolation A",
"Draenor - MagnificentDesolation B",
"Draenor - MagnificentDesolation H",
"Draenor - MagnificentDesolation Piano",
"Draenor - Malach H1",
"Draenor - Malach H2",
"Draenor - Malach H3",
"Draenor - Malach H4",
"Draenor - MalevolentMystique A",
"Draenor - MalevolentMystique B1",
"Draenor - MalevolentMystique B2",
"Draenor - MalevolentMystique C",
"Draenor - MalevolentMystique H",
"Draenor - MalevolentPrescience B",
"Draenor - MalevolentPrescience H",
"Draenor - ManDown A1",
"Draenor - ManDown A2",
"Draenor - ManDown A3",
"Draenor - ManDown B",
"Draenor - ManDown C",
"Draenor - ManDown D",
"Draenor - ManDown E",
"Draenor - ManDown F",
"Draenor - ManDown H1",
"Draenor - Mobilize A",
"Draenor - Mobilize B1",
"Draenor - Mobilize B2",
"Draenor - Mobilize C1",
"Draenor - Mobilize C2",
"Draenor - Mobilize D",
"Draenor - Mobilize E Stinger",
"Draenor - Mobilize H",
"Draenor - MountainsIntro A1",
"Draenor - MountainsIntro A2",
"Draenor - MountainsOfNagrand A1",
"Draenor - MountainsOfNagrand A2",
"Draenor - MountainsOfNagrand B",
"Draenor - MountainsOfNagrand H",
"Draenor - Mountains Ambient2",
"Draenor - Mountains Ambient3",
"Draenor - Mountains Stinger1",
"Draenor - Mystic A1",
"Draenor - Mystic A2",
"Draenor - Mystic B1",
"Draenor - Mystic B2",
"Draenor - Mystic C",
"Draenor - Mystic C2",
"Draenor - Mystic D1",
"Draenor - Mystic D2",
"Draenor - Mystic E",
"Draenor - Mystic F",
"Draenor - Mystic G",
"Draenor - Mystic H",
"Draenor - Nagrand V1",
"Draenor - Nagrand V2",
"Draenor - Nagrand V3a",
"Draenor - Nagrand V3b",
"Draenor - Nagrand V4",
"Draenor - Nagrand V5",
"Draenor - Nagrand V6",
"Draenor - Nagrand V7",
"Draenor - NightSpires V1",
"Draenor - NightSpires V2",
"Draenor - NightSpires V3",
"Draenor - NightSpires V4",
"Draenor - OgreMines A1",
"Draenor - OgreMines A2",
"Draenor - OgreMines B",
"Draenor - OgreMines H1",
"Draenor - OgreMines H2",
"Draenor - PatiencePoint A1",
"Draenor - PatiencePoint A2",
"Draenor - PatiencePoint B1",
"Draenor - PatiencePoint B2",
"Draenor - PatiencePoint H",
"Draenor - PlightOfTheOgres H1",
"Draenor - PlightOfTheOgres H2",
"Draenor - Premonition H",
"Draenor - PrevalentConfliction A",
"Draenor - ProtectTheThrone H1",
"Draenor - ProtectTheThrone H2",
"Draenor - ProtectTheThrone H3",
"Draenor - Proudmoore H",
"Draenor - QuietHeart A",
"Draenor - QuietHeart A1",
"Draenor - QuietHeart A2",
"Draenor - QuietHeart H",
"Draenor - QuietHeart H1",
"Draenor - QuietHeart H2",
"Draenor - RiseToTheDark H1",
"Draenor - RiseToTheDark H2",
"Draenor - Sacrifice 2a",
"Draenor - Sacrifice 2h",
"Draenor - Sacrifice B",
"Draenor - ShadowmoonPt1 A",
"Draenor - ShadowmoonPt1 H",
"Draenor - ShadowmoonRising H",
"Draenor - ShadowmoonSunsetIntro H",
"Draenor - ShadowmoonSunsetReprise H",
"Draenor - Shadowmoon V1",
"Draenor - Shadowmoon V2",
"Draenor - Shadowmoon V3",
"Draenor - Shadowmoon V4",
"Draenor - Shadowmoon V5",
"Draenor - Shakedown A",
"Draenor - Shakedown B",
"Draenor - Shakedown C",
"Draenor - SmackTheGiant H1",
"Draenor - SmackTheGiant H2",
"Draenor - SmackTheGiant H3",
"Draenor - SmackTheGiant H4",
"Draenor - SpiresOfArak V1",
"Draenor - SpiresOfArak V2",
"Draenor - SpiresOfArak V4",
"Draenor - StormlordsOnTheMarch H1",
"Draenor - StormlordsOnTheMarch H2",
"Draenor - StormlordsOnTheMarch H3",
"Draenor - TheClansJoin A",
"Draenor - TheClansJoin B",
"Draenor - TheClansJoin H",
"Draenor - Tome A",
"Draenor - Tome B",
"Draenor - Tome H",
"Draenor - TraversingTheSpires A",
"Draenor - TraversingTheSpires B",
"Draenor - TraversingTheSpires C",
"Draenor - TraversingTheSpires H1",
"Draenor - TraversingTheSpires H2",
"Draenor - TsHaveIt A",
"Draenor - TsHaveIt B",
"Draenor - TsHaveIt C",
"Draenor - TsHaveIt H",
"Draenor - Village A",
"Draenor - Village B",
"Draenor - Village C1",
"Draenor - Village C2",
"Draenor - Village D",
"Draenor - Village F",
"Draenor - Village H",
"Draenor - Voce C",
"Draenor - Vows A1",
"Draenor - Vows A2",
"Draenor - Vows A3",
"Draenor - Vows B",
"Draenor - Vows C1",
"Draenor - Vows C2",
"Draenor - Vows C3",
"Draenor - Vows D1",
"Draenor - Vows D2",
"Draenor - Vows H1",
"Draenor - Vows H2",
"Draenor - Vows H3",
"Draenor - Vows H4",
"Draenor - Vows H5",
"Draenor - WarriorsJourney A",
"Draenor - WarriorsJourney B1",
"Draenor - WarriorsJourney B2",
"Draenor - WarriorsJourney B3",
"Draenor - WarriorsJourney C",
"Draenor - WarriorsJourney D",
"Draenor - WarriorsJourney E",
"Draenor - WarriorsJourney H1",
"Draenor - WarriorsJourney H2",
"Draenor - WarriorsJourney H3",
"Draenor - WarriorsJourney H4",
"Draenor - Warsong V1",
"Draenor - Warsong V2",
"Draenor - Warsong V3a",
"Draenor - Warsong V3b",
"Draenor - Warsong V4",
"Draenor - WolfAtTheGates A",
"Draenor - WolfAtTheGates B",
"Draenor - WolfAtTheGates H",
"Draenor - Wonder A1",
"Draenor - Wonder A2",
"Draenor - Wonder H",
"Draenor - WorldExpo A1",
"Draenor - WorldExpo A2",
"Draenor - WorldExpo A3",
"Draenor - WorldExpo B",
"Draenor - WorldExpo C",
"Draenor - WorldExpo D",
"Draenor - WorldExpo E1",
"Draenor - WorldExpo E2",
"Draenor - WorldExpo F1",
"Draenor - WorldExpo F2",
"Draenor - WorldExpo F3",
"Draenor - WorldExpo G",
"Draenor - WorldExpo H",
"Draenor - Hellfire Citadel - Falling 1A",
"Draenor - Hellfire Citadel - Falling 1B",
"Draenor - Hellfire Citadel - Falling 2H",
"Draenor - Hellfire Citadel - FelEssence A",
"Draenor - Hellfire Citadel - FelEssence B",
"Draenor - Hellfire Citadel - FelEssence C",
"Draenor - Hellfire Citadel - FelEssence D",
"Draenor - Hellfire Citadel - FelEssence H",
"Draenor - Hellfire Citadel - FeuDeLEnfer A",
"Draenor - Hellfire Citadel - FeuDeLEnfer H",
"Draenor - Hellfire Citadel - LostMoon A",
"Draenor - Hellfire Citadel - LostMoon B",
"Draenor - Hellfire Citadel - LostMoon H",
"Draenor - Hellfire Citadel - MortalNight A",
"Draenor - Hellfire Citadel - MortalNight B",
"Draenor - Hellfire Citadel - MortalNight C",
"Draenor - Hellfire Citadel - MortalNight H",
"Draenor - Hellfire Citadel - TanaanGloom A",
"Draenor - Hellfire Citadel - TanaanGloom B",
"Draenor - Hellfire Citadel - TanaanGloom C",
"Draenor - Hellfire Citadel - TanaanGloom H",
"Draenor - Hellfire Citadel - Tanaander A",
"Draenor - Hellfire Citadel - Tanaander B",
"Draenor - Hellfire Citadel - Tanaander C",
"Draenor - Hellfire Citadel - Tanaander H",
"Draenor - Hellfire Citadel - TheWanderer A",
"Draenor - Hellfire Citadel - TheWanderer B",
"Draenor - Hellfire Citadel - TheWanderer H",
"Draenor - Hellfire Citadel - Undaunted A",
"Draenor - Hellfire Citadel - Undaunted B",
"Draenor - Hellfire Citadel - Undaunted H"
}
