SoundFiles_Names = {
"Cinematics - DSI Act1",
"Cinematics - DSI Act2",
"Cinematics - DSI Act3",
"Cinematics - DSI Act4",
"Cinematics - Goblin",
"Cinematics - Logo",
"Cinematics - MOP ASL",
"Cinematics - MOP BR",
"Cinematics - MOP GSE",
"Cinematics - MOP HSL",
"Cinematics - MOP JADE CRASH",
"Cinematics - MOP JADE",
"Cinematics - MOP WRA",
"Cinematics - MOP WRH",
"Cinematics - ORO Alliance",
"Cinematics - ORO Horde",
"Cinematics - Worgen",
"Cinematics - WOW FotLK",
"Cinematics - WOW Intro BC",
"Cinematics - WoW Intro LK",
"Cinematics - WoW Intro MOP",
"Cinematics - WOW Intro",
"Cinematics - WOW Wrathgate",
"Cinematics - WoW3X Intro",
"Cinematic Voices - BloodElfNarration",
"Cinematic Voices - DeathKnightNarration",
"Cinematic Voices - DraeneiNarration",
"Cinematic Voices - DwarfNarration",
"Cinematic Voices - GnomeNarration",
"Cinematic Voices - GoblinNarration",
"Cinematic Voices - HumanNarration",
"Cinematic Voices - MaelstromNarration",
"Cinematic Voices - NightElfNarration",
"Cinematic Voices - OrcNarration",
"Cinematic Voices - PANDARENNARRATION",
"Cinematic Voices - TaurenNarration",
"Cinematic Voices - TrollNarration",
"Cinematic Voices - UndeadNarration",
"Cinematic Voices - WorgenNarration",
"Cataclysm - faeriedragon 01",
"Cataclysm - ZA altarbloodgod 01",
"Cataclysm - ZA altarbloodgod 02",
"Cataclysm - ZA altarbloodgod 03",
"Cataclysm - ZA bethekk 01",
"Cataclysm - ZA bethekk 02",
"Cataclysm - ZA cacheofmadness 01",
"Cataclysm - ZA cacheofmadness 02",
"Cataclysm - ZA devilsterrace 01",
"Cataclysm - ZA devilsterrace 02",
"Cataclysm - ZA mandokir 01",
"Cataclysm - ZA mandokir 02",
"Cataclysm - ZA templebethek 01",
"Cataclysm - ZA templebethek 02",
"Cataclysm - ZA terracedevils 01",
"Cataclysm - ZA terracedevils 02",
"Cataclysm - ZA thecoil 01",
"Cataclysm - ZA thecoil 02",
"Cataclysm - DruidsoftheFlameA Hero 01",
"Cataclysm - DruidsoftheFlameA 01",
"Cataclysm - DruidsoftheFlameA 02",
"Cataclysm - DruidsoftheFlameA 03",
"Cataclysm - DruidsoftheFlameB Hero 01",
"Cataclysm - DruidsoftheFlameB 01",
"Cataclysm - DruidsoftheFlameB 02",
"Cataclysm - DruidsoftheFlameB 03",
"Cataclysm - Elemental AirA 01",
"Cataclysm - Elemental AirA 02",
"Cataclysm - Elemental AirB 01",
"Cataclysm - Elemental AirB 02",
"Cataclysm - Elemental AirC 01",
"Cataclysm - Elemental AirD 01",
"Cataclysm - Elemental AirD 02",
"Cataclysm - Elemental EarthA 01",
"Cataclysm - Elemental EarthA 02",
"Cataclysm - Elemental EarthA 03",
"Cataclysm - Elemental EarthA 04",
"Cataclysm - Elemental Water Ambient 01",
"Cataclysm - Elemental WaterA UD01",
"Cataclysm - Elemental WaterA UN01",
"Cataclysm - Elemental WaterB UD01",
"Cataclysm - Elemental WaterB UN01",
"Cataclysm - Elemental WaterC UD01",
"Cataclysm - Elemental WaterC UN01",
"Cataclysm - ElementalBondsA 01",
"Cataclysm - ElementalBondsA 02",
"Cataclysm - ElementalBondsA 03",
"Cataclysm - ElementalBondsB 01",
"Cataclysm - ElementalBondsB 02",
"Cataclysm - FirelandsA Hero 01",
"Cataclysm - FirelandsA 01",
"Cataclysm - FirelandsA 02",
"Cataclysm - FirelandsA 03",
"Cataclysm - FirelandsB Hero 01",
"Cataclysm - FirelandsB 01",
"Cataclysm - FirelandsB 02",
"Cataclysm - FirelandsB 03",
"Cataclysm - FirelandsB 04",
"Cataclysm - ThrallAggraA ED01",
"Cataclysm - ThrallAggraA EN01",
"Cataclysm - ThrallAggraB ED01",
"Cataclysm - ThrallAggraB EN01",
"Cataclysm - ThrallAggraC EU01",
"Cataclysm - ThrallAggraC EU02",
"Cataclysm - CorruptedDragonblight 01",
"Cataclysm - CorruptedDragonblight 02",
"Cataclysm - CorruptedDragonblight 03",
"Cataclysm - DeathwingCorruption 01",
"Cataclysm - DeathwingCorruption 02",
"Cataclysm - DeathwingCorruption 03",
"Cataclysm - DeathwingCorruption 04",
"Cataclysm - DeathwingCorruption 05",
"Cataclysm - DeathwingCorruption 06",
"Cataclysm - DeathwingCorruption 07",
"Cataclysm - DeathwingOutro 01",
"Cataclysm - DeathwingsFall Hero 01",
"Cataclysm - DeathwingsFall 01",
"Cataclysm - DeathwingsFall 02",
"Cataclysm - DragonSoulA Hero 01",
"Cataclysm - DragonSoulA Moment 01",
"Cataclysm - DragonSoulA Moment 02",
"Cataclysm - DragonSoulA Moment 03",
"Cataclysm - DragonSoulA Moment 04",
"Cataclysm - DragonSoulB 01",
"Cataclysm - DragonSoulB 02",
"Cataclysm - DragonSoulB 03",
"Cataclysm - FangsOfTheFatherA Hero 01",
"Cataclysm - FangsOfTheFatherA 01",
"Cataclysm - FangsOfTheFatherA 02",
"Cataclysm - FangsOfTheFatherA 03",
"Cataclysm - FangsOfTheFatherB 01",
"Cataclysm - FangsOfTheFatherB 02",
"Cataclysm - FangsOfTheFatherB 03",
"Cataclysm - FangsOfTheFatherC Hero 01",
"Cataclysm - FangsOfTheFatherC 02",
"Cataclysm - FangsOfTheFatherC 03",
"Cataclysm - FangsOfTheFatherC 04",
"Cataclysm - Gunships Hero 01",
"Cataclysm - Gunships Stinger 01",
"Cataclysm - Gunships Stinger 02",
"Cataclysm - Gunships Stinger 03",
"Cataclysm - Gunships Stinger 04",
"Cataclysm - Gunships 01",
"Cataclysm - Gunships 02",
"Cataclysm - Gunships 03",
"Cataclysm - Gunships 04",
"Cataclysm - Night 01",
"Cataclysm - Night 02",
"Cataclysm - Night 03",
"Cataclysm - Night 04",
"Cataclysm - ThrallEarthWarder 01",
"Cataclysm - ThrallEarthWarder 02",
"Cataclysm - ThrallEarthWarder 03",
"Cataclysm - ThrallEarthWarder 04",
"Cataclysm - TwilightsHammer 01",
"Cataclysm - TwilightsHammer 02",
"Cataclysm - Warships Hero 01",
"Cataclysm - Warships 01",
"Cataclysm - Warships 02",
"Cataclysm - WellOfEternity Hero 01",
"Cataclysm - WellOfEternity 01",
"Cataclysm - WellOfEternity 02",
"Cataclysm - WellOfEternity 03",
"Cataclysm - WellOfEternity 04",
"Cataclysm - WellOfEternity 05",
"Cataclysm - WellOfEternity 06",
"Cataclysm - ZinAzshari Hero 01",
"Cataclysm - ZinAzshari 01",
"Cataclysm - ZinAzshari 02",
"Cataclysm - ZinAzshari 03",
"Cataclysm - ZinAzshari 04",
"Cataclysm - ZinAzshari 05",
"Cataclysm - ZinAzshari 06",
"Cataclysm - AdventureA Hero 01",
"Cataclysm - AdventureA Moment 01",
"Cataclysm - AdventureA Moment 02",
"Cataclysm - AdventureA Moment 03",
"Cataclysm - AdventureA Moment 04",
"Cataclysm - AdventureA 01",
"Cataclysm - AdventureA 03",
"Cataclysm - AdventureA 04",
"Cataclysm - AdventureA 05",
"Cataclysm - AdventureA 06",
"Cataclysm - Aftermath 01",
"Cataclysm - Aftermath 02",
"Cataclysm - Aftermath 03",
"Cataclysm - Aftermath 04",
"Cataclysm - AllianceHero 01",
"Cataclysm - ArathiHighlandsA GD01",
"Cataclysm - ArathiHighlandsA GN01",
"Cataclysm - ArathiHighlandsA GN02",
"Cataclysm - ArathiHighlandsB GD01",
"Cataclysm - ArathiHighlandsB GN01",
"Cataclysm - ArathiHighlandsB GN02",
"Cataclysm - ArathiHighlandsC GD01",
"Cataclysm - ArathiHighlandsC GN01",
"Cataclysm - ArathiHighlandsC GN02",
"Cataclysm - Azshara GD01",
"Cataclysm - Azshara GN01",
"Cataclysm - BarrowDens GU01",
"Cataclysm - BarrowDens GU02",
"Cataclysm - BarrowDens GU03",
"Cataclysm - BarrowDens GU04",
"Cataclysm - BarrowDens GU05",
"Cataclysm - BurningSteppes GU01",
"Cataclysm - BurningSteppes GU02",
"Cataclysm - BurningSteppes GU03",
"Cataclysm - BurningSteppes GU04",
"Cataclysm - Cataclysm UD07",
"Cataclysm - Cataclysm UN08",
"Cataclysm - Cataclysm UN09",
"Cataclysm - Cataclysm 01",
"Cataclysm - Cataclysm 02",
"Cataclysm - Cataclysm 03",
"Cataclysm - Cataclysm 04",
"Cataclysm - Cataclysm 05",
"Cataclysm - Cataclysm 06",
"Cataclysm - ChoGall E01",
"Cataclysm - ChoGall E02",
"Cataclysm - ChoGall E03",
"Cataclysm - ChoGall E04",
"Cataclysm - ColdMountain GU01",
"Cataclysm - ColdMountain GU02",
"Cataclysm - ColdMountain GU03",
"Cataclysm - ColdMountain GU04",
"Cataclysm - ColdMountain GU05",
"Cataclysm - ColdMountain GU06",
"Cataclysm - ColdMountain GU07",
"Cataclysm - ColdMountain GU08",
"Cataclysm - Crypt 01",
"Cataclysm - Cursed 01",
"Cataclysm - Cursed 02",
"Cataclysm - Cursed 03",
"Cataclysm - Cursed 04",
"Cataclysm - Cursed 05",
"Cataclysm - Cursed 06",
"Cataclysm - Cursed 07",
"Cataclysm - Cursed 08",
"Cataclysm - Cursed 09",
"Cataclysm - Cursed 10",
"Cataclysm - Cursed 11",
"Cataclysm - Cursed 12",
"Cataclysm - DarkEvent E01",
"Cataclysm - DarkIronforge GU01",
"Cataclysm - DarkIronforge GU02",
"Cataclysm - DarkIronforge GU03",
"Cataclysm - DarkIronforge GU04",
"Cataclysm - DarkIronforge GU05",
"Cataclysm - DarkIronforge GU06",
"Cataclysm - DarkIronforge GU07",
"Cataclysm - DarkwhisperGorge GU01",
"Cataclysm - DarkwhisperGorge GU02",
"Cataclysm - Darnassus GI01",
"Cataclysm - Darnassus GI02",
"Cataclysm - Deepholm GU01",
"Cataclysm - Deepholm GU02",
"Cataclysm - DeepholmEvent E01",
"Cataclysm - DeepholmEvent E02",
"Cataclysm - DurotarA GU01",
"Cataclysm - DurotarA GU02",
"Cataclysm - DurotarA GU03",
"Cataclysm - DurotarB GU01",
"Cataclysm - DurotarB GU02",
"Cataclysm - DurotarB GU03",
"Cataclysm - DurotarB GU04",
"Cataclysm - DurotarC GU01",
"Cataclysm - DurotarC GU02",
"Cataclysm - DurotarC GU03",
"Cataclysm - DurotarC GU04",
"Cataclysm - DurotarD GU01",
"Cataclysm - DurotarD GU02",
"Cataclysm - Elemental 01",
"Cataclysm - Elemental 02",
"Cataclysm - Elemental 03",
"Cataclysm - Elemental 04",
"Cataclysm - Elemental 05",
"Cataclysm - Elemental 06",
"Cataclysm - Elemental 07",
"Cataclysm - EyeOfTheVortex GU01",
"Cataclysm - EyeOfTheVortex GU02",
"Cataclysm - EyeOfTheVortex GU03",
"Cataclysm - Feralas GU01",
"Cataclysm - Feralas GU02",
"Cataclysm - Feralas GU03",
"Cataclysm - Feralas GU04",
"Cataclysm - Feralas GU05",
"Cataclysm - Feralas GU06",
"Cataclysm - Feralas GU07",
"Cataclysm - Feralas GU08",
"Cataclysm - Fire 01",
"Cataclysm - Fire 02",
"Cataclysm - Firelands GU01",
"Cataclysm - FlowerAura EU 01",
"Cataclysm - Ghosts 01",
"Cataclysm - Ghosts 02",
"Cataclysm - Ghosts 03",
"Cataclysm - GilneasEvent E01",
"Cataclysm - GilneasEvent E02",
"Cataclysm - GilneasEvent E03",
"Cataclysm - GilneasEvent E04",
"Cataclysm - Goblin 01",
"Cataclysm - Goblin 02",
"Cataclysm - Goblin 03",
"Cataclysm - Goblin 04",
"Cataclysm - Goblin 05",
"Cataclysm - Goblin 06",
"Cataclysm - Goblin 07",
"Cataclysm - Goblin 08",
"Cataclysm - Goblin 09",
"Cataclysm - Goblin 10",
"Cataclysm - Goblin 11",
"Cataclysm - Goblin 12",
"Cataclysm - Goblin 13",
"Cataclysm - Goblin 14",
"Cataclysm - Goblin 15",
"Cataclysm - Goblin 16",
"Cataclysm - Goblin 17",
"Cataclysm - Goblin 18",
"Cataclysm - Goblin 19",
"Cataclysm - Goblin 20",
"Cataclysm - Goblin 21",
"Cataclysm - Goblin 22",
"Cataclysm - Goblin 23",
"Cataclysm - Goblin 24",
"Cataclysm - Goblin 25",
"Cataclysm - Goblin 26",
"Cataclysm - Goblin 27",
"Cataclysm - Goblin 28",
"Cataclysm - Goblin 29",
"Cataclysm - Goblin 30",
"Cataclysm - Goblin 31",
"Cataclysm - Goblin 32",
"Cataclysm - Goblin 33",
"Cataclysm - Goblin 34",
"Cataclysm - Goblin 35",
"Cataclysm - Goblin 36",
"Cataclysm - Goblin 37",
"Cataclysm - Goblin 38",
"Cataclysm - Goblin 39",
"Cataclysm - Goblin 40",
"Cataclysm - Goblin 41",
"Cataclysm - Goblin 42",
"Cataclysm - Goblin 43",
"Cataclysm - Goblin 44",
"Cataclysm - Goblin 45",
"Cataclysm - Goblin 46",
"Cataclysm - Goblin 47",
"Cataclysm - GoblinHotRodRadioLoop EU01",
"Cataclysm - Grimtotem 01",
"Cataclysm - Grimtotem 02",
"Cataclysm - Grimtotem 03",
"Cataclysm - Grimtotem 04",
"Cataclysm - GroveOfTheAncients GU01",
"Cataclysm - GroveOfTheAncients GU02",
"Cataclysm - GroveOfTheAncients GU03",
"Cataclysm - GroveOfTheAncients GU04",
"Cataclysm - GuardiansofHyjal GU01",
"Cataclysm - GuardiansofHyjal GU02",
"Cataclysm - GuardiansofHyjal GU03",
"Cataclysm - GuardiansofHyjal GU04",
"Cataclysm - Haunted 01",
"Cataclysm - Haunted 02",
"Cataclysm - Haunted 03",
"Cataclysm - Hyjal GU01",
"Cataclysm - Hyjal GU02",
"Cataclysm - Hyjal GU03",
"Cataclysm - Hyjal GU04",
"Cataclysm - LandWillWeep 01",
"Cataclysm - LandWillWeep 02",
"Cataclysm - LIRescue EU01",
"Cataclysm - LIRescue EU02",
"Cataclysm - LIRescue EU03",
"Cataclysm - LIRescue EU04",
"Cataclysm - LostCity GU01",
"Cataclysm - LostCity GU02",
"Cataclysm - LostCity GU03",
"Cataclysm - LostCity GU04",
"Cataclysm - LostCity GU05",
"Cataclysm - Marsh 01",
"Cataclysm - Marsh 02",
"Cataclysm - Marsh 03",
"Cataclysm - Marsh 04",
"Cataclysm - Marsh 05",
"Cataclysm - Marsh 06",
"Cataclysm - Marsh 07",
"Cataclysm - Marsh 08",
"Cataclysm - Moonglade GU01",
"Cataclysm - Moonglade GU02",
"Cataclysm - Moonglade GU03",
"Cataclysm - Moonglade GU04",
"Cataclysm - Moonglade GU05",
"Cataclysm - Moonglade GU06",
"Cataclysm - Moonglade GU07",
"Cataclysm - Mulgore GU01",
"Cataclysm - Mulgore GU02",
"Cataclysm - Mulgore GU03",
"Cataclysm - MulgorePlains GU01",
"Cataclysm - MulgorePlains GU02",
"Cataclysm - Mysterious 01",
"Cataclysm - NightElves GU01",
"Cataclysm - NightElves GU02",
"Cataclysm - NightElves GU03",
"Cataclysm - NightElves GU04",
"Cataclysm - NightElves GU05",
"Cataclysm - Nordrassil GU01",
"Cataclysm - Nordrassil GU02",
"Cataclysm - Nordrassil GU03",
"Cataclysm - Orgrimmar GU01",
"Cataclysm - OrgrimmarLegacy GU01",
"Cataclysm - PiratesSurrender 01",
"Cataclysm - Rift 01",
"Cataclysm - Rift 02",
"Cataclysm - Rift 03",
"Cataclysm - Rift 04",
"Cataclysm - RuinsOfAuberdine GU01",
"Cataclysm - RuinsOfAuberdine GU02",
"Cataclysm - RuinsOfAuberdine GU03",
"Cataclysm - RuinsOfAuberdine GU04",
"Cataclysm - RuinsOfAuberdine GU05",
"Cataclysm - Scarred 01",
"Cataclysm - Scarred 02",
"Cataclysm - Scarred 03",
"Cataclysm - Scarred 04",
"Cataclysm - Shadowglen GU01",
"Cataclysm - Shadowglen GU02",
"Cataclysm - Shadowglen GU03",
"Cataclysm - Shadows 01",
"Cataclysm - Shadows 02",
"Cataclysm - Shadows 03",
"Cataclysm - Shadows 04",
"Cataclysm - Shadows 05",
"Cataclysm - Shattering 01",
"Cataclysm - Silithus GU01",
"Cataclysm - Silithus GU02",
"Cataclysm - Silithus GU03",
"Cataclysm - Silithus GU04",
"Cataclysm - Silithus GU05",
"Cataclysm - Silithus GU06",
"Cataclysm - SirenQuest EU01",
"Cataclysm - Skywall GU01",
"Cataclysm - Skywall GU02",
"Cataclysm - Skywall GU03",
"Cataclysm - Skywall GU04",
"Cataclysm - Skywall GU05",
"Cataclysm - Skywall GU06",
"Cataclysm - Skywall GU07",
"Cataclysm - Skywall GU08",
"Cataclysm - Skywall GU09",
"Cataclysm - Skywall GU10",
"Cataclysm - SouthernBarrens GU01",
"Cataclysm - SouthernBarrens GU02",
"Cataclysm - SouthernBarrens GU03",
"Cataclysm - SouthernBarrens GU04",
"Cataclysm - SouthernBarrens GU05",
"Cataclysm - SouthernBarrens GU06",
"Cataclysm - Stonetalon GU01",
"Cataclysm - Stonetalon GU02",
"Cataclysm - Stonetalon GU03",
"Cataclysm - Stonetalon GU04",
"Cataclysm - Stormwind GU01",
"Cataclysm - Stormwind GU02",
"Cataclysm - Stormwind GU03",
"Cataclysm - Stormwind GU04",
"Cataclysm - Stranglethorn GU01",
"Cataclysm - Stranglethorn GU02",
"Cataclysm - Stranglethorn GU03",
"Cataclysm - Stranglethorn GU04",
"Cataclysm - StranglethornVale GU01",
"Cataclysm - StranglethornVale GU02",
"Cataclysm - StranglethornVale GU03",
"Cataclysm - StranglethornVale GU04",
"Cataclysm - Tanaris GU01",
"Cataclysm - Tanaris GU02",
"Cataclysm - Tanaris GU03",
"Cataclysm - Tanaris GU04",
"Cataclysm - Tanaris GU05",
"Cataclysm - Tanaris GU06",
"Cataclysm - Tanaris GU07",
"Cataclysm - Tanaris GU08",
"Cataclysm - Tanaris GU09",
"Cataclysm - Tanaris GU10",
"Cataclysm - Tauren 01",
"Cataclysm - Tauren 02",
"Cataclysm - ThunderBluff GU01",
"Cataclysm - ThunderBluff GU02",
"Cataclysm - ThunderBluff GU03",
"Cataclysm - Treasure 01",
"Cataclysm - Treasure 02",
"Cataclysm - Treasure 03",
"Cataclysm - Treasure 04",
"Cataclysm - Treasure 05",
"Cataclysm - Treasure 06",
"Cataclysm - TwilightHighlands GU01",
"Cataclysm - TwilightHighlands GU02",
"Cataclysm - TwilightHighlands GU03",
"Cataclysm - TwilightHighlands GU04",
"Cataclysm - TwilightHighlands GU05",
"Cataclysm - TwilightsHammer 01",
"Cataclysm - TwilightsHammer 02",
"Cataclysm - TwilightsHammer 03",
"Cataclysm - TwilightVale GU01",
"Cataclysm - TwilightVale GU02",
"Cataclysm - TwilightVale GU03",
"Cataclysm - TwilightVale GU04",
"Cataclysm - TwilightVale GU05",
"Cataclysm - UldumA GU01",
"Cataclysm - UldumA GU02",
"Cataclysm - UldumA GU03",
"Cataclysm - UldumA GU04",
"Cataclysm - UldumA GU05",
"Cataclysm - UldumB GU01",
"Cataclysm - UldumB GU02",
"Cataclysm - UldumB GU03",
"Cataclysm - UldumB GU04",
"Cataclysm - UldumB GU05",
"Cataclysm - UldumB GU06",
"Cataclysm - UldumEvent E01",
"Cataclysm - Undead 01",
"Cataclysm - Undead 02",
"Cataclysm - Undead 03",
"Cataclysm - Undead 04",
"Cataclysm - Undead 05",
"Cataclysm - Vashjir GU01",
"Cataclysm - Vashjir GU02",
"Cataclysm - Vashjir GU03",
"Cataclysm - Vashjir GU04",
"Cataclysm - Vashjir GU05",
"Cataclysm - Vashjir GU06",
"Cataclysm - Vashjir GU07",
"Cataclysm - Vashjir GU08",
"Cataclysm - Vashjir GU09",
"Cataclysm - VashjirNaga GU01",
"Cataclysm - VashjirNaga GU02",
"Cataclysm - VashjirNaga GU03",
"Cataclysm - VashjirNaga GU04",
"Cataclysm - VashjirNaga GU05",
"Cataclysm - VashjirNaga GU06",
"Cataclysm - VashjirNagaThrone GU01",
"Cataclysm - VashjirNagaThrone GU02",
"Cataclysm - VashjirNagaThrone GU03",
"Cataclysm - VashjirNagaThrone GU04",
"Cataclysm - VashjirNagaThrone GU05",
"Cataclysm - VashjirNagaThrone GU06",
"Cataclysm - WarMarch 01",
"Cataclysm - Westfall GU01",
"Cataclysm - Westfall GU02",
"Cataclysm - Westfall GU03",
"Cataclysm - Westfall GU04",
"Cataclysm - Westfall GU05",
"Cataclysm - WestPlagueA GD01",
"Cataclysm - WestPlagueA GN01",
"Cataclysm - WestPlagueA GN02",
"Cataclysm - WestPlagueB GD01",
"Cataclysm - WestPlagueB GN01",
"Cataclysm - WestPlagueB GN02",
"Cataclysm - WestPlagueB GN03",
"Cataclysm - WestPlagueC GD01",
"Cataclysm - WestPlagueC GN01",
"Cataclysm - WestPlagueC GN02",
"Cataclysm - Winterspring GU01",
"Cataclysm - Winterspring GU02",
"Cataclysm - Winterspring GU03",
"Cataclysm - Winterspring GU04",
"Cataclysm - Winterspring GU05",
"Cataclysm - WordsAndMusicByEvent E01",
"CityDarnassus - Darnassus Intro",
"CityDarnassus - Darnassus 1",
"CityDarnassus - Darnassus 2",
"CityDarnassus - Darnassus 3",
"CityDarnassus - Druid Grove",
"CityDarnassus - Warrior Terrace",
"CityGnomeragon - Gnomeragon 01",
"CityGnomeragon - Gnomeragon 02",
"CityIronforge - IronForge Intro",
"CityIronforge - IronForge 01",
"CityIronforge - IronForge 02",
"CityIronforge - Ironforge 03 (Glenn)",
"CityIronforge - Ironforge 04",
"CityIronforge - TinkerTownIntro moment",
"CityOrgrimmar - Orgrimmar Intro",
"CityOrgrimmar - Orgrimmar01",
"CityOrgrimmar - Orgrimmar01",
"CityOrgrimmar - Orgrimmar02",
"CityOrgrimmar - Orgrimmar02",
"CityStormwind - Stormwind HighSeas",
"CityStormwind - Stormwind Intro",
"CityStormwind - Stormwind01",
"CityStormwind - Stormwind02",
"CityStormwind - Stormwind03",
"CityStormwind - Stormwind04",
"CityStormwind - Stormwind05",
"CityStormwind - Stormwind06",
"CityStormwind - Stormwind07",
"CityStormwind - Stormwind08",
"CityThunderbluff - Thunderbluff Intro",
"CityThunderbluff - Thunderbluff 01",
"CityThunderbluff - Thunderbluff 02",
"CityThunderbluff - Thunderbluff 03",
"CityUndercity - Undercity01",
"CityUndercity - Undercity02",
"CityUndercity - Undercity03",
"CityUndercity - UndercityIntro",
"Event - Gnomeregan Event B",
"Event - Gnomeregan Event C",
"Event - Gnomeregan Event complete",
"Event - Gnomeregan Event D",
"Event - Gnomeregan Event E",
"Event - Gnomeregan Event intro",
"Event - ZFBigBattle13",
"Event - ZFBigBattle14",
"Event - ZFBigBattle16",
"Event - ZFMagic17",
"Event - ZFMagic18",
"Event - ZFMedBattle3",
"Event - ZFMedBattle4",
"Event - ZFMedBattle5",
"Event - ZFMedBattle6",
"Event - ZFQuiet1",
"Event - ZFQuiet2",
"Event - ZFQuiet7",
"Event - ZFQuietShort8",
"Event - ZFRally9",
"Event - ZFStinger10",
"Event - ZFStinger11",
"Event - ZFStinger12",
"Event - ZFStinger15",
"GlueScreen - BC - Main Theme",
"GlueScreen - BC - Lament of the Highborne",
"GlueScreen - WotLK - Main Title",
"GlueScreen - WoW - Main Theme",
"SoundTest Music01",
"SoundTest Music02",
"SoundTest Music03",
"Musical - Angelic - Angelic01",
"Musical - Battle - Battle01",
"Musical - Battle - Battle02",
"Musical - Battle - Battle03",
"Musical - Battle - Battle04",
"Musical - Battle - Battle05",
"Musical - Battle - Battle06",
"Musical - Gloomy - Gloomy01",
"Musical - Gloomy - Gloomy02",
"Musical - GuldansEntranceTheme",
"Musical - Haunted - Haunted01",
"Musical - Haunted - Haunted02",
"Musical - Magic - Magic01",
"Musical - Magic - Magic01-1",
"Musical - Magic - Magic01-2",
"Musical - Mystery - AhnQirajIntro1",
"Musical - Mystery - Mystery01",
"Musical - Mystery - Mystery02",
"Musical - Mystery - Mystery03",
"Musical - Mystery - Mystery04",
"Musical - Mystery - Mystery05",
"Musical - Mystery - Mystery06",
"Musical - Mystery - Mystery07",
"Musical - Mystery - Mystery08",
"Musical - Mystery - Mystery09",
"Musical - Mystery - Mystery10",
"Musical - Sacred - Sacred01",
"Musical - Sacred - sacred02",
"Musical - SP TempleOfStormsAction 1",
"Musical - Spooky - Spooky01",
"Musical - Swamp - Swamp01",
"Musical - ZulGurubVooDoo",
"Pandaria - FlyBy 52 MoguBridge MX SFX",
"Pandaria - FlyBy 52 MoguSecret MX SFX",
"Pandaria - AugustCelestials 01",
"Pandaria - AugustCelestials 02",
"Pandaria - AugustCelestials 03",
"Pandaria - AugustCelestials 04",
"Pandaria - AugustCelestials 05",
"Pandaria - AugustCelestials Hero 01",
"Pandaria - BalloonRide Hero 01",
"Pandaria - Bamboo 01",
"Pandaria - Bamboo 02",
"Pandaria - Bamboo 03",
"Pandaria - Bamboo 04",
"Pandaria - Bamboo Hero 01",
"Pandaria - Bamboo Night 01",
"Pandaria - Bamboo Night Hero 01",
"Pandaria - BattleforPandaria Hero 01",
"Pandaria - BattleforPandaria Hero 02",
"Pandaria - BottomsUp 01",
"Pandaria - BottomsUp Hero 01",
"Pandaria - Darkbrew 01",
"Pandaria - Darkbrew Hero 01",
"Pandaria - DreadWastes A Hero 01",
"Pandaria - DreadWastes A Hero 02",
"Pandaria - GateoftheSettingSun A Hero 01",
"Pandaria - GateoftheSettingSun A Hero 02",
"Pandaria - GateoftheSettingSun A Hero 03",
"Pandaria - GateoftheSettingSun A Hero 04",
"Pandaria - GateoftheSettingSun B 01",
"Pandaria - GateoftheSettingSun B Hero 01",
"Pandaria - GateoftheSettingSun B Hero 02",
"Pandaria - HeartofPandaria 01",
"Pandaria - Hozen A 01",
"Pandaria - Hozen A 02",
"Pandaria - Hozen A 03",
"Pandaria - Hozen A 04",
"Pandaria - Hozen A 05",
"Pandaria - Hozen A 06",
"Pandaria - Hozen A 07",
"Pandaria - Hozen A 08",
"Pandaria - Hozen A 09",
"Pandaria - Hozen A 10",
"Pandaria - Hozen A 11",
"Pandaria - Hozen A 12",
"Pandaria - Hozen A 13",
"Pandaria - Hozen A Hero 01",
"Pandaria - Hozen B 01",
"Pandaria - Hozen B 02",
"Pandaria - Hozen B 03",
"Pandaria - Hozen B Hero 01",
"Pandaria - Hozen 01",
"Pandaria - Jinyu A Hero 01",
"Pandaria - Jinyu A Hero 02",
"Pandaria - Jinyu A Hero 03",
"Pandaria - Jinyu A Hero 04",
"Pandaria - Jinyu B 01",
"Pandaria - Jinyu B 02",
"Pandaria - Jinyu B Hero 01",
"Pandaria - Jinyu C 01",
"Pandaria - Jinyu C Hero 01",
"Pandaria - Jinyu C Hero 02",
"Pandaria - Jinyu D 01",
"Pandaria - Jinyu D Hero 01",
"Pandaria - Jinyu D Hero 02",
"Pandaria - Jinyu D Night 01",
"Pandaria - Jinyu D Night Hero 01",
"Pandaria - Jinyu D Night Hero 02",
"Pandaria - KrasarangWilds A Hero 01",
"Pandaria - KrasarangWilds A Hero 02",
"Pandaria - KrasarangWilds B Hero 01",
"Pandaria - KrasarangWilds B Hero 02",
"Pandaria - KrasarangWilds B Hero 03",
"Pandaria - KunLaiSummit A Hero 01",
"Pandaria - KunLaiSummit A Hero 02",
"Pandaria - KunLaiSummit A Hero 03",
"Pandaria - KunLaiSummit A Hero 04",
"Pandaria - KunLaiSummit B Hero 01",
"Pandaria - KunLaiSummit C Hero 01",
"Pandaria - KunLaiSummit C Hero 02",
"Pandaria - Mantid A 01",
"Pandaria - Mantid A 02",
"Pandaria - Mantid A 03",
"Pandaria - Mantid A Hero 01",
"Pandaria - Mogu A Hero 01",
"Pandaria - Mogu A Hero 02",
"Pandaria - Mogu B 01",
"Pandaria - Mogu B 02",
"Pandaria - Mogu B 03",
"Pandaria - Mogu B 04",
"Pandaria - Mogu B 05",
"Pandaria - Mogu B 06",
"Pandaria - Mogu B Hero 01",
"Pandaria - Monk Brewmaster A 01",
"Pandaria - Monk Brewmaster A Hero 01",
"Pandaria - Monk Mistweaver A 01",
"Pandaria - Monk Mistweaver A 02",
"Pandaria - Monk Mistweaver A 03",
"Pandaria - Monk Mistweaver A Hero 01",
"Pandaria - Monk Mistweaver A Hero 02",
"Pandaria - Monk Mistweaver A 01",
"Pandaria - Monk Mistweaver A 02",
"Pandaria - Monk Mistweaver B 01",
"Pandaria - Monk Mistweaver B 02",
"Pandaria - Monk Mistweaver B 03",
"Pandaria - Monk Mistweaver B 04",
"Pandaria - Monk Mistweaver B Hero 01",
"Pandaria - Monk Winder A 01",
"Pandaria - Monk Winder A 02",
"Pandaria - Monk Winder A 03",
"Pandaria - Monk Winder A Hero 01",
"Pandaria - Monk Winder A Hero 02",
"Pandaria - Monk Winder A 01",
"Pandaria - Monk Winder A 02",
"Pandaria - Monk Winder A 03",
"Pandaria - Monk Winder A 04",
"Pandaria - Pandaria A 01",
"Pandaria - Pandaria A 02",
"Pandaria - Pandaria A 03",
"Pandaria - Pandaria A Choir 01",
"Pandaria - Pandaria A Hero 01",
"Pandaria - Pandaria B 01",
"Pandaria - Pandaria B Hero 01",
"Pandaria - Pandaria B Hero 02",
"Pandaria - Pandaria C Hero 01",
"Pandaria - Pandaria C Hero 02",
"Pandaria - Pandaria C Hero 03",
"Pandaria - Pandaria C 01",
"Pandaria - Pandaria C 02",
"Pandaria - Pandaria C 03",
"Pandaria - Pandaria D 01",
"Pandaria - Pandaria D 02",
"Pandaria - Pandaria D 03",
"Pandaria - Pandaria D Hero 01",
"Pandaria - PandariaPVP Hero 01",
"Pandaria - PandariaPVP Hero 02",
"Pandaria - ScarletMonastery A Hero 01",
"Pandaria - ScarletMonastery A Hero 02",
"Pandaria - ScarletMonastery A Hero 03",
"Pandaria - Scholomance A 01",
"Pandaria - Scholomance A 02",
"Pandaria - Scholomance A 03",
"Pandaria - Scholomance A 04",
"Pandaria - Scholomance A 05",
"Pandaria - Scholomance A 06",
"Pandaria - Scholomance A 07",
"Pandaria - Scholomance A 08",
"Pandaria - Scholomance A 09",
"Pandaria - Scholomance A 10",
"Pandaria - Scholomance A 11",
"Pandaria - Scholomance A 12",
"Pandaria - SerpentRiders 01",
"Pandaria - SerpentRiders Hero 01",
"Pandaria - SerpentRiders SerpentRace",
"Pandaria - SerpentRiders Victory Stinger",
"Pandaria - SerpentsHeart Hero 01",
"Pandaria - SerpentsHeart Hero 02",
"Pandaria - SerpentsHeart Hero 03",
"Pandaria - SerpentsHeart Night Hero 01",
"Pandaria - SerpentsHeart Night Hero 02",
"Pandaria - SerpentsHeart Night 01",
"Pandaria - SerpentsHeart Night 02",
"Pandaria - SerpentsHeart Night 03",
"Pandaria - Sha 01",
"Pandaria - Sha 02",
"Pandaria - Sha Hero 01",
"Pandaria - Sha Stinger Heavy 01",
"Pandaria - Sha Stinger Heavy 02",
"Pandaria - Sha Stinger Heavy 03",
"Pandaria - Sha Stinger Lite 01",
"Pandaria - Sha Stinger Lite 02",
"Pandaria - Sha Stinger Lite 03",
"Pandaria - Sha Stinger Lite 04",
"Pandaria - Sha Stinger Med 01",
"Pandaria - Sha Stinger Med 02",
"Pandaria - ShadoPan A Hero 01",
"Pandaria - ShadoPan A Hero 02",
"Pandaria - ShadoPan A Hero 03",
"Pandaria - ShadoPan A 01",
"Pandaria - ShadoPan A 02",
"Pandaria - ShadoPan B Hero 01",
"Pandaria - ShadoPan B Hero 02",
"Pandaria - Sha Hero 01",
"Pandaria - Sha Hero 02",
"Pandaria - Sha Hero 03",
"Pandaria - Sha Hero 04",
"Pandaria - ShenZinSu 01",
"Pandaria - ShenZinSu 02",
"Pandaria - ShenZinSu 03",
"Pandaria - ShenZinSu Hero 01",
"Pandaria - ShenZinSu Hero 02",
"Pandaria - ShoSha A 01",
"Pandaria - ShoSha A 02",
"Pandaria - ShoSha A 03",
"Pandaria - ShoSha A 04",
"Pandaria - ShoSha A 05",
"Pandaria - ShoSha B 01",
"Pandaria - ShoSha B 02",
"Pandaria - ShoSha B 03",
"Pandaria - ShoSha B 04",
"Pandaria - ShoSha B 05",
"Pandaria - ShoSha B 06",
"Pandaria - SiegeofNiuzaoTemple Hero 01",
"Pandaria - SiegeofNiuzaoTemple Hero 02",
"Pandaria - SiegeofNiuzaoTemple Hero 03",
"Pandaria - SongofLiulang Inst 01",
"Pandaria - SongofLiulang Inst 02",
"Pandaria - SongofLiulang Inst 03",
"Pandaria - SongofLiulang Inst 04",
"Pandaria - SongofLiulang Inst 05",
"Pandaria - SongofLiulang Inst 06",
"Pandaria - SongofLiulang Inst 07",
"Pandaria - SongofLiulang Inst Hero 01",
"Pandaria - SongofLiulang VOX Hero 01",
"Pandaria - SongofLiulang VOX Lite 01",
"Pandaria - SpiritCave 01",
"Pandaria - SpiritCave 02",
"Pandaria - SpiritCave 03",
"Pandaria - SpiritCave 04",
"Pandaria - SpiritCave 05",
"Pandaria - SpiritCave 06",
"Pandaria - SpiritCave Hero 01",
"Pandaria - SpiritPath 01",
"Pandaria - SpiritPath 02",
"Pandaria - SpiritPath 03",
"Pandaria - SpiritPath 04",
"Pandaria - SpiritPath Hero 01",
"Pandaria - Spirits A 01",
"Pandaria - Spirits A 02",
"Pandaria - Spirits A 03",
"Pandaria - Spirits A 04",
"Pandaria - SpiritsB 01",
"Pandaria - SpiritsB 02",
"Pandaria - TempleoftheFiveDawns 01",
"Pandaria - TempleoftheFiveDawns 02",
"Pandaria - TempleoftheFiveDawns 03",
"Pandaria - TempleoftheFiveDawns 04",
"Pandaria - TempleoftheFiveDawns 05",
"Pandaria - TempleoftheFiveDawns 06",
"Pandaria - TempleoftheFiveDawns 07",
"Pandaria - TempleoftheFiveDawns 08",
"Pandaria - TempleoftheFiveDawns 09",
"Pandaria - TempleoftheFiveDawns 10",
"Pandaria - TempleoftheFiveDawns 11",
"Pandaria - TempleoftheFiveDawns 12",
"Pandaria - TempleoftheFiveDawns Hero 01",
"Pandaria - TempleoftheJadeSerpent Hero 01",
"Pandaria - TempleoftheJadeSerpent Hero 02",
"Pandaria - TempleoftheJadeSerpent Hero 03",
"Pandaria - TheHeartland Hero 01",
"Pandaria - TheHeartland Hero 02",
"Pandaria - TheHeartland Hero 03",
"Pandaria - TheHeartland Hero 04",
"Pandaria - TheRiver 01",
"Pandaria - TheRiver 02",
"Pandaria - TheRiver 03",
"Pandaria - TheRiver 04",
"Pandaria - TheRiver 05",
"Pandaria - TheRiver 06",
"Pandaria - TheRiver 07",
"Pandaria - TheRiver Hero 01",
"Pandaria - Toast A 01",
"Pandaria - Toast A Hero 01",
"Pandaria - Toast B 02",
"Pandaria - Toast B 03",
"Pandaria - Toast B 04",
"Pandaria - Toast B Hero 01",
"Pandaria - TownlongSteppes A 01",
"Pandaria - TownlongSteppes A 02",
"Pandaria - TownlongSteppes B 01",
"Pandaria - TownlongSteppes B 02",
"Pandaria - TownlongSteppes B 01",
"Pandaria - TownlongSteppes C 01",
"Pandaria - TownlongSteppes C 02",
"Pandaria - TownlongSteppes C 03",
"Pandaria - TownlongSteppes C Night 01",
"Pandaria - TownlongSteppes C Night 02",
"Pandaria - TownlongSteppes C Night 03",
"Pandaria - TownlongSteppes D 01",
"Pandaria - TownlongSteppes D 01",
"Pandaria - TownlongSteppes D 02",
"Pandaria - VEB A 01",
"Pandaria - VEB A 02",
"Pandaria - VEB A 03",
"Pandaria - VEB A 04",
"Pandaria - VEB A 05",
"Pandaria - VEB A 06",
"Pandaria - VEB A Hero 01",
"Pandaria - VEB B 01",
"Pandaria - VEB B 02",
"Pandaria - VEB B 03",
"Pandaria - VEB B Hero 01",
"Pandaria - VEB B Night 01",
"Pandaria - VEB B Night 02",
"Pandaria - VEB B Night 03",
"Pandaria - VEB B Night 04",
"Pandaria - VEB B Night 05",
"Pandaria - VEB B Night 06",
"Pandaria - VEB C Hero 01",
"Pandaria - VEB C Hero 02",
"Pandaria - VEB D Hero 01",
"Pandaria - VEB D Hero 02",
"Pandaria - VEB D Hero 03",
"Pandaria - VEB D Hero 04",
"Pandaria - VFW A 01",
"Pandaria - VFW A 02",
"Pandaria - VFW A 03",
"Pandaria - VFW A 04",
"Pandaria - VFW A 05",
"Pandaria - VFW A 06",
"Pandaria - VFW A 07",
"Pandaria - VFW A 08",
"Pandaria - VFW A Hero 01",
"Pandaria - VFW A Hero 02",
"Pandaria - Windspire 01",
"Pandaria - Windspire 02",
"Pandaria - Windspire 03",
"Pandaria - Windspire Hero 01",
"Pandaria - WoodofStaves Hero 01",
"Pandaria - WoodofStaves Hero 02",
"Pandaria - WoodofStaves Hero 03",
"Pandaria - AllianceBattleMarch 01",
"Pandaria - AllianceBattleMarch 02",
"Pandaria - AllianceBattleMarch Hero 01",
"Pandaria - ForTheAlliance 01",
"Pandaria - ForTheAlliance 02",
"Pandaria - ForTheAlliance 03",
"Pandaria - ForTheAlliance 04",
"Pandaria - ForTheAlliance 05",
"Pandaria - ForTheAlliance Hero 01",
"Pandaria - GarroshTheme A 01",
"Pandaria - GarroshTheme A 02",
"Pandaria - GarroshTheme A Hero 01",
"Pandaria - GarroshTheme B 01",
"Pandaria - GarroshTheme B 02",
"Pandaria - GarroshTheme B Hero 01",
"Pandaria - GarroshTheme DivineBellFinale",
"Pandaria - JainaHomeland Lyrical 01",
"Pandaria - JainaHomeland Lyrical 02",
"Pandaria - JainaHomeland Lyrical Hero 01",
"Pandaria - JainaHomeland Military 01",
"Pandaria - JainaHomeland Military 02",
"Pandaria - JainaHomeland Military 03",
"Pandaria - JainaHomeland Military Hero 01",
"Pandaria - Sunreavers 01",
"Pandaria - Sunreavers 02",
"Pandaria - Sunreavers 03",
"Pandaria - Sunreavers 04",
"Pandaria - Sunreavers 05",
"Pandaria - Sunreavers 06",
"Pandaria - Sunreavers 07",
"Pandaria - Sunreavers 08",
"Pandaria - Sunreavers 09",
"Pandaria - Sunreavers 10",
"Pandaria - Sunreavers 11",
"Pandaria - Sunreavers 12",
"Pandaria - Sunreavers 13",
"Pandaria - Sunreavers 14",
"Pandaria - Sunreavers 15",
"Pandaria - Sunreavers 16",
"Pandaria - Sunreavers 17",
"Pandaria - Sunreavers 18",
"Pandaria - Sunreavers 19",
"Pandaria - Sunreavers Hero 01",
"Pandaria - Theramores Fall Scene 01",
"Pandaria - AncientMogu A 01",
"Pandaria - AncientMogu A 02",
"Pandaria - AncientMogu A 03",
"Pandaria - AncientMogu A 04",
"Pandaria - AncientMogu A Hero 01",
"Pandaria - AncientMogu B 01",
"Pandaria - AncientMogu B Hero 01",
"Pandaria - AncientMogu B Stinger 01",
"Pandaria - AncientMogu C 01",
"Pandaria - AncientMogu C 02",
"Pandaria - AncientMogu C 03",
"Pandaria - AncientMogu C 04",
"Pandaria - AncientMogu C 05",
"Pandaria - AncientMogu C 06",
"Pandaria - AncientMogu C Hero 01",
"Pandaria - AncientMogu C Stinger 01",
"Pandaria - AncientMogu C Stinger 02",
"Pandaria - AncientMogu D 01",
"Pandaria - AncientMogu D 02",
"Pandaria - AncientMogu D Hero 01",
"Pandaria - AncientPandaria A 01",
"Pandaria - AncientPandaria Hero 01",
"Pandaria - GodsAndMonster 01",
"Pandaria - ItIsDone A 01",
"Pandaria - ItIsDone A 02",
"Pandaria - ItIsDone A 03",
"Pandaria - ItIsDone A 04",
"Pandaria - ItIsDone A 05",
"Pandaria - Mysterioso A 01",
"Pandaria - Mysterioso A 02",
"Pandaria - Mysterioso Hero 01",
"Pandaria - ThunderIsle A 01",
"Pandaria - ThunderIsle A 02",
"Pandaria - ThunderIsle A 03",
"Pandaria - ThunderIsle A 04",
"Pandaria - ThunderIsle A 05",
"Pandaria - ThunderIsle A 06",
"Pandaria - ThunderIsle A 07",
"Pandaria - ThunderIsle A Hero 01",
"Pandaria - ThunderIsle A Stinger 01",
"Pandaria - ThunderIsle A Stinger 02",
"Pandaria - ThunderIsle A Stinger 03",
"Pandaria - ThunderIsle A Stinger 04",
"Pandaria - ThunderIsle B 01",
"Pandaria - ThunderIsle B 02",
"Pandaria - ThunderIsle B 03",
"Pandaria - ThunderIsle B 04",
"Pandaria - ThunderIsle B 05",
"Pandaria - ThunderIsle B Hero 01",
"Pandaria - ThunderIsle C 01",
"Pandaria - ThunderIsle C 02",
"Pandaria - ThunderIsle C 03",
"Pandaria - ThunderIsle C 04",
"Pandaria - ThunderIsle C Hero 01",
"Pandaria - ThunderIsle C Stinger 01",
"Pandaria - ThunderIsle C Stinger 02",
"Pandaria - ThunderIsle C Stinger 03",
"Pandaria - ThunderKing A 01",
"Pandaria - ThunderKing A 02",
"Pandaria - ThunderKing A 03",
"Pandaria - ThunderKing A Hero 01",
"Pandaria - ThunderKing A Stinger 01",
"Pandaria - ThunderKing A Stinger 02",
"Pandaria - ThunderKing A Stinger 03",
"Pandaria - ThunderKing A Stinger 04",
"Pandaria - ThunderKing A Stinger 05",
"Pandaria - ThunderKing A Stinger 06",
"Pandaria - ThunderKing A Stinger 07",
"Pandaria - ThunderKing B 01",
"Pandaria - ThunderKing B Hero 01",
"Pandaria - ThunderKing C Stinger 01",
"Pandaria - TrollBattle A 01",
"Pandaria - TrollBattle A 02",
"Pandaria - TrollBattle A 03",
"Pandaria - TrollBattle B 01",
"Pandaria - TrollBattle B 02",
"Pandaria - TrollBattle B 03",
"Pandaria - TrovesOfTheThunderKing 01",
"Pandaria - Wrathion A 02",
"Pandaria - Wrathion A 03",
"Pandaria - Wrathion A Hero 01",
"Pandaria - Wrathion B 01",
"Pandaria - Wrathion B 02",
"Pandaria - Wrathion B 03",
"Pandaria - Zandalari 1 A 01",
"Pandaria - Zandalari 1 A 02",
"Pandaria - Zandalari 1 A 03",
"Pandaria - Zandalari 1 B 01",
"Pandaria - Zandalari 1 B 02",
"Pandaria - Zandalari 1 B 03",
"Pandaria - Zandalari 1 C 01",
"Pandaria - Zandalari 1 C 02",
"Pandaria - Zandalari 2 A 01",
"Pandaria - Zandalari 2 A 02",
"Pandaria - Zandalari 2 A 03",
"Pandaria - Zandalari 2 A 04",
"Pandaria - Zandalari 2 A 05",
"Pandaria - Zandalari 2 B 01",
"Pandaria - Zandalari 2 B 02",
"Pandaria - Zandalari 2 B 03",
"Pandaria - Zandalari 2 C 01",
"Pandaria - Zandalari 2 C 02",
"Pandaria - Zandalari 2 C 03",
"Pandaria - ZandalariProphecy 01",
"Pandaria - EmperorRevealed",
"Pandaria - Wrathion C 01",
"Pandaria - Wrathion C 02",
"Pandaria - CorruptedVale Day 01",
"Pandaria - CorruptedVale Day 02",
"Pandaria - CorruptedVale Day 03",
"Pandaria - CorruptedVale Day 04",
"Pandaria - CorruptedVale Day Hero",
"Pandaria - CorruptedVale Night 01",
"Pandaria - CorruptedVale Night 02",
"Pandaria - CorruptedVale Night 03",
"Pandaria - CorruptedVale Night 04",
"Pandaria - CorruptedVale Night 05",
"Pandaria - CorruptedVale Night Hero",
"Pandaria - Doomhammer 01",
"Pandaria - Doomhammer 02",
"Pandaria - Doomhammer 03",
"Pandaria - Doomhammer 04",
"Pandaria - Doomhammer 05",
"Pandaria - Doomhammer Hero",
"Pandaria - ForThePandarenAlliance A 01",
"Pandaria - ForThePandarenAlliance A 02",
"Pandaria - ForThePandarenAlliance B 01",
"Pandaria - ForThePandarenAlliance B 02",
"Pandaria - GoodMourning Hero",
"Pandaria - Legendary 01",
"Pandaria - Legendary 02",
"Pandaria - Legendary 03",
"Pandaria - Legendary 04",
"Pandaria - Legendary 05",
"Pandaria - Legendary 06",
"Pandaria - Legendary 07",
"Pandaria - Legendary 08",
"Pandaria - Legendary 09",
"Pandaria - Legendary 10",
"Pandaria - Legendary Hero",
"Pandaria - Mok-Rah 01",
"Pandaria - Mok-Rah 02",
"Pandaria - Mok-Rah 03",
"Pandaria - Mok-Rah 04",
"Pandaria - Mok-Rah 05",
"Pandaria - Mok-Rah 06",
"Pandaria - Mok-Rah 07",
"Pandaria - Mok-Rah 08",
"Pandaria - Mok-Rah Hero",
"Pandaria - NoQuarter 01",
"Pandaria - NoQuarter 02",
"Pandaria - NoQuarter 03",
"Pandaria - NoQuarter 04",
"Pandaria - NoQuarter Hero",
"Pandaria - Overlord 01",
"Pandaria - Overlord 02",
"Pandaria - Overlord 03",
"Pandaria - Overlord Hero",
"Pandaria - ShaAmbient 01",
"Pandaria - ShaAmbient 02",
"Pandaria - ShaAmbient 03",
"Pandaria - ShaAmbient 04",
"Pandaria - ShaAmbient Hero",
"Pandaria - ShaAngry 01",
"Pandaria - ShaAngry 02",
"Pandaria - ShaAngry Hero",
"Pandaria - ShaDescendant 01",
"Pandaria - ShaDescendant 02",
"Pandaria - ShaDescendant 03",
"Pandaria - ShaDescendant Hero",
"Pandaria - ShaVocaline 01",
"Pandaria - ShaVocaline 02",
"Pandaria - ShaVocaline 03",
"Pandaria - ShaVocaline Hero",
"Pandaria - ValeHealing",
"PetBattles - ToyTrumpet",
"PetBattles - W2 Human1",
"PetBattles - W2 Human2",
"PetBattles - W2 Human3",
"PetBattles - W2 Human4",
"PetBattles - W2 HumanVictory",
"PetBattles - W2 HumanWarRoom",
"PetBattles - W2 Orc1",
"PetBattles - W2 Orc2",
"PetBattles - W2 Orc3",
"PetBattles - W2 Orc4",
"PetBattles - W2 OrcVictory",
"PetBattles - W2 OrcWarRoom",
"WorldEvents - AllianceFirepole",
"WorldEvents - DarkMoonFaire 1",
"WorldEvents - DarkMoonFaire 2",
"WorldEvents - DarkMoonFaire 3",
"WorldEvents - DarkMoonFaire 4",
"WorldEvents - HordeFirepole",
"AhnQiraj - AhnQirajExterior1",
"AhnQiraj - AhnQirajExterior2",
"AhnQiraj - AhnQirajExterior3",
"AhnQiraj - AhnQirajExterior4",
"AhnQiraj - AhnQirajInterior1",
"AhnQiraj - AhnQirajInterior2",
"AhnQiraj - AhnQirajInterior3",
"AhnQiraj - AhnQirajInteriorCenterRoom1",
"AhnQiraj - AhnQirajInteriorIntroMain",
"AhnQiraj - AhnQirajKingRoom",
"AhnQiraj - AhnQirajTriangleRoom1",
"AhnQiraj - AhnQirajTriangleRoom2",
"AhnQiraj - AhnQirajTriangleRoom3",
"AhnQiraj - AhnQirajTriangleRoom4",
"AhnQiraj - AhnQirajTriangleRoom5",
"AhnQiraj - AhnQirajTriangleRoom6",
"AhnQiraj - AhnQirajTriangleRoom7",
"ArgentColiseum - CR TourneyBattle01",
"ArgentColiseum - CR TourneyBattle02",
"ArgentColiseum - CR TourneyBattle03",
"ArgentColiseum - CR TourneyBattle04",
"ArgentColiseum - CR TourneyBattle05",
"ArgentColiseum - CR TourneyBattle06",
"ArgentTournament - AT HeraldEvent",
"ArgentTournament - AT JoustEvent",
"ArgentTournament - AT Tourney01Night",
"ArgentTournament - AT Tourney02Day",
"ArgentTournament - AT Tourney03Night",
"ArgentTournament - AT Tourney05Night",
"ArgentTournament - AT Tourney06Day",
"ArgentTournament - AT Tourney07Night",
"ArgentTournament - AT Tourney08Night",
"ArgentTournament - AT Tourney09Day",
"ArgentTournament - AT Tourney10Day",
"AzjolNerub - AN GeneralIntro 01",
"AzjolNerub - AN GeneralIntro 02",
"AzjolNerub - AN GeneralIntro 03",
"AzjolNerub - AN GeneralIntro 04",
"AzjolNerub - AN GeneralIntro 05",
"AzjolNerub - AN GeneralIntro 06",
"AzjolNerub - AN GeneralIntro 07",
"AzjolNerub - AN GeneralIntro 08",
"AzjolNerub - AN General 01",
"AzjolNerub - AN General 02",
"AzjolNerub - AN General 03",
"AzjolNerub - AN General 04",
"AzjolNerub - AN General 05",
"AzjolNerub - AN General 06",
"AzjolNerub - AN General 07",
"AzjolNerub - AN General 08",
"AzjolNerub - AN General 09",
"AzjolNerub - AN General 10",
"AzjolNerub - AN General 11",
"AzjolNerub - AN General 12",
"AzjolNerub - AN General 13",
"AzjolNerub - AN General 14",
"AzjolNerub - AN General 15",
"AzjolNerub - AN General 16",
"Azuremyst - AI Draenei 5",
"Azuremyst - AI Draenei 6",
"Azuremyst - AI Draenei 7r",
"Azuremyst - AI Draenei 8r",
"Azuremyst - AI ExodarIntro01",
"Azuremyst - AI Exodar 1",
"Azuremyst - AI Exodar 2",
"Azuremyst - AI Exodar 3",
"Azuremyst - AI Naga 1",
"Azuremyst - AI Naga 2",
"Azuremyst - AI Naga 3",
"Azuremyst - AI Naga 4",
"Azuremyst - AI Naga 5",
"Azuremyst - AI Owlkin 1",
"Azuremyst - AI Owlkin 2",
"Azuremyst - AV Draenei 1",
"Azuremyst - AV Draenei 2",
"Azuremyst - AV Draenei 2r",
"Azuremyst - AV Draenei 3",
"Azuremyst - AV Draenei 3r",
"Azuremyst - AV Draenei 4",
"BarrenDry - DayBarrenDry01",
"BarrenDry - DayBarrenDry02",
"BarrenDry - DayBarrenDry03",
"BarrenDry - NightBarrenDry01",
"BarrenDry - NightBarrenDry02",
"BarrenDry - NightBarrenDry03",
"BlackTemple - BT ArrivalHero01",
"BlackTemple - BT Arrival 2",
"BlackTemple - BT Arrival 3",
"BlackTemple - BT Arrival 4",
"BlackTemple - BT IllidariHero09",
"BlackTemple - BT Illidari 1",
"BlackTemple - BT Illidari 2",
"BlackTemple - BT Illidari 3",
"BlackTemple - BT Illidari 4",
"BlackTemple - BT Illidari 5",
"BlackTemple - BT Illidari 6",
"BlackTemple - BT Illidari 7",
"BlackTemple - BT Illidari 8",
"BlackTemple - BT IllidariUni10",
"BlackTemple - BT IllidariUni11",
"BlackTemple - BT Karabor 1",
"BlackTemple - BT Karabor 2",
"BlackTemple - BT Karabor 3",
"BlackTemple - BT Karabor 4",
"BlackTemple - BT PreludeEvent01",
"BlackTemple - BT ReliquaryHero01",
"BlackTemple - BT Reliquary 2",
"BlackTemple - BT Reliquary 3",
"BlackTemple - BT Reliquary 4",
"BlackTemple - BT Reliquary 5",
"BlackTemple - BT Reliquary 6",
"BlackTemple - BT Reliquary 7",
"BlackTemple - BT Reliquary 8",
"BlackTemple - BT SanctuaryHero01",
"BlackTemple - BT Sanctuary 2",
"BlackTemple - BT Sanctuary 3",
"BlackTemple - BT Sanctuary 4",
"BlackTemple - BT Sanctuary 5",
"BlackTemple - BT Sanctuary 6",
"BlackTemple - BT Sanctuary 7",
"BlackTemple - BT Sanctuary 8",
"BlackTemple - BT StormHero02",
"BlackTemple - BT Storm 1",
"BlackTemple - BT Storm 3",
"BlackTemple - BT Storm 4",
"BlackTemple - BT Summit 1",
"BlackTemple - BT Summit 2",
"BlackTemple - BT Summit 3",
"BlackTemple - BT Summit 4",
"BlackTemple - BT Summit 5",
"BladesEdge - BL DryForest 1",
"BladesEdge - BL DryForest 2",
"BladesEdge - BL DryForest 3",
"BladesEdge - BL General 1",
"BladesEdge - BL General 2",
"BladesEdge - BL General 3",
"BladesEdge - BL General 4",
"BladesEdge - BL General 5",
"BladesEdge - BL Ogre 1",
"BladesEdge - BL Ogre 2",
"Bloodmyst - BI NagaIntro01",
"Bloodmyst - BI NagaIntro01r",
"Bloodmyst - BI Satyr 1r",
"Bloodmyst - BI Satyr 2",
"Bloodmyst - BI Satyr 3",
"Bloodmyst - BI Satyr 4",
"Bloodmyst - BI Satyr 5",
"BoreanTundra - BO Coldarra 1",
"BoreanTundra - BO Coldarra 2",
"BoreanTundra - BO Coldarra 3",
"BoreanTundra - BO General Day01",
"BoreanTundra - BO General Day02",
"BoreanTundra - BO General Day03",
"BoreanTundra - BO General Day04",
"BoreanTundra - BO General Day05",
"BoreanTundra - BO General Day06",
"BoreanTundra - BO General Day07",
"BoreanTundra - BO General Day08",
"BoreanTundra - BO General Night01",
"BoreanTundra - BO General Night02",
"BoreanTundra - BO General Night03",
"BoreanTundra - BO General Night04",
"BoreanTundra - BO General Night05",
"BoreanTundra - BO General Night06",
"BoreanTundra - BO General Night07",
"BoreanTundra - BO General Night08",
"BoreanTundra - BO GeyserField General01",
"BoreanTundra - BO GeyserField General02",
"BoreanTundra - BO GeyserField General03",
"BoreanTundra - BO Riplash Day01",
"BoreanTundra - BO Riplash Day02",
"BoreanTundra - BO Riplash Day03",
"BoreanTundra - BO Riplash Intro01",
"BoreanTundra - BO Riplash Intro02",
"BoreanTundra - BO Riplash Night01",
"BoreanTundra - BO Riplash Night02",
"BoreanTundra - BO Riplash Night03",
"BoreanTundra - BO Riplash Night04",
"BoreanTundra - BO Tusk KaskalaDay01",
"BoreanTundra - BO Tusk KaskalaDay02",
"BoreanTundra - BO Tusk KaskalaNight01",
"BoreanTundra - BO Tusk KaskalaNight02",
"Brewfest - BF Dwarves1",
"Brewfest - BF Dwarves2",
"Brewfest - BF Dwarves3",
"Brewfest - BF Goblins1",
"Brewfest - BF Goblins2",
"Brewfest - BF Goblins3",
"CavernsOfTime - CT BrazensFlightIntro",
"CavernsOfTime - CT Caverns1",
"CavernsOfTime - CT Caverns2",
"CavernsOfTime - CT Caverns3",
"CavernsOfTime - CT Caverns4",
"CavernsOfTime - CT Caverns5",
"CavernsOfTime - CT Caverns6",
"CavernsOfTime - CT Caverns7",
"CavernsOfTime - CT Caverns8",
"CavernsOfTime - CT Caverns9",
"CavernsOfTime - CT DurnholdeCellar1",
"CavernsOfTime - CT DurnholdeCellar2",
"CavernsOfTime - CT DurnholdeCellar3",
"CavernsOfTime - CT DurnholdeKeepExt1",
"CavernsOfTime - CT DurnholdeKeepExt2",
"CavernsOfTime - CT DurnholdeKeepExt3",
"CavernsOfTime - CT DurnholdeKeepExt4",
"CavernsOfTime - CT DurnholdeKeepExt5",
"CavernsOfTime - CT DurnholdeKeepExt6",
"CavernsOfTime - CT DurnholdeKeepInt1",
"CavernsOfTime - CT DurnholdeKeepInt2",
"CavernsOfTime - CT DurnholdeKeepInt3",
"CavernsOfTime - CT EscapeDurnIntro",
"CavernsOfTime - CT HillsbradExt1",
"CavernsOfTime - CT HillsbradExt2",
"CavernsOfTime - CT HyjalExt7",
"CavernsOfTime - CT HyjalExt8",
"CavernsOfTime - CT HyjalExt9",
"CavernsOfTime - CT HyjalExt 1",
"CavernsOfTime - CT HyjalExt 2",
"CavernsOfTime - CT HyjalExt 3",
"CavernsOfTime - CT HyjalExt 4",
"CavernsOfTime - CT HyjalExt 5",
"CavernsOfTime - CT HyjalExt 6",
"CavernsOfTime - CT HyjalExtUni10",
"CavernsOfTime - CT HyjalExtUni11",
"CavernsOfTime - CT HyjalExtUni12",
"CavernsOfTime - CT MorassPortalIntro01",
"CavernsOfTime - CT Morass 1",
"CavernsOfTime - CT Morass 2",
"CavernsOfTime - CT Morass 3",
"CavernsOfTime - CT Morass 4",
"CavernsOfTime - CT Morass 5",
"CavernsOfTime - CT TarrenMillExt1",
"CavernsOfTime - CT TarrenMillExt2",
"CavernsOfTime - CT TarrenMillExt3",
"CavernsOfTime - CT ThrallEscapeIntro",
"ChamberOfTheAspects - CA Day01",
"ChamberOfTheAspects - CA Day02",
"ChamberOfTheAspects - CA Day03",
"ChamberOfTheAspects - CA Day04",
"ChamberOfTheAspects - CA Night01",
"ChamberOfTheAspects - CA Night02",
"ChamberOfTheAspects - CA Night03",
"ChamberOfTheAspects - CA Night04",
"ChamberOfTheAspects - CA 1",
"ChamberOfTheAspects - CA 2",
"ChamberOfTheAspects - CA IntroADay01",
"ChamberOfTheAspects - CA IntroANight01",
"Crystalsong - CS Crystalsong 1",
"Crystalsong - CS Crystalsong 2",
"Crystalsong - CS Crystalsong 3",
"Crystalsong - CS Crystalsong 4",
"Crystalsong - CS Crystalsong 5",
"CursedLand - CursedLand01",
"CursedLand - CursedLand02",
"CursedLand - CursedLand03",
"CursedLand - CursedLand04",
"CursedLand - CursedLand05",
"CursedLand - CursedLand06",
"Dalaran - DC General 1",
"Dalaran - DC General 2",
"Dalaran - DC General 3",
"Dalaran - DC General 4",
"Dalaran - DC Intro 1",
"Dalaran - DC Sewer 1",
"Dalaran - DC Sewer 2",
"Dalaran - DC Sewer 3",
"Dalaran - DC Sewer 4",
"Dalaran - DC Spire 1",
"DarkmoonFaire - A Hero 01",
"DarkmoonFaire - A 01",
"DarkmoonFaire - B Hero 01",
"DarkmoonFaire - B 01",
"DarkmoonFaire - B 02",
"DarkmoonFaire - C 02",
"DarkmoonFaire - D 01",
"DarkmoonFaire - D 02",
"DarkmoonFaire - MerryGoRound 01",
"Desert - DayDesert01",
"Desert - DayDesert02",
"Desert - DayDesert03",
"Desert - NightDesert01",
"Desert - NightDesert02",
"Desert - NightDesert03",
"DMF L70ETC01",
"Dragonblight - DB GeneralIntro 01",
"Dragonblight - DB GeneralIntro 02",
"Dragonblight - DB GeneralIntro 03",
"Dragonblight - DB GeneralIntro 04",
"Dragonblight - DB General Day01",
"Dragonblight - DB General Day02",
"Dragonblight - DB General Day03",
"Dragonblight - DB General Day04",
"Dragonblight - DB General Day05",
"Dragonblight - DB General Day06",
"Dragonblight - DB General Day07",
"Dragonblight - DB General Day08",
"Dragonblight - DB General Night01",
"Dragonblight - DB General Night02",
"Dragonblight - DB General Night03",
"Dragonblight - DB General Night04",
"Dragonblight - DB General Night05",
"Dragonblight - DB General Night06",
"Dragonblight - DB General Night07",
"Dragonblight - DB General Night08",
"Dragonblight - DB Tusk Indule Day01",
"Dragonblight - DB Tusk Indule Day02",
"Dragonblight - DB Tusk InduleDay01",
"Dragonblight - DB Tusk InduleDay02",
"Dragonblight - DB Tusk InduleDay03",
"Dragonblight - DB Tusk InduleNight01",
"Dragonblight - DB Tusk InduleNight02",
"Dragonblight - DB Tusk InduleNight03",
"Ebon Hold - EH Assault 1",
"Ebon Hold - EH Assault 2",
"Ebon Hold - EH Assault 3",
"Ebon Hold - EH Assault 4",
"Ebon Hold - EH Assault 5",
"Ebon Hold - EH Assault 6",
"Ebon Hold - EH Assault 7",
"Ebon Hold - EH General 1",
"Ebon Hold - EH General 2",
"Ebon Hold - EH General 3",
"EnchantedForest - EnchantedForest01",
"EnchantedForest - EnchantedForest02",
"EnchantedForest - EnchantedForest03",
"EnchantedForest - EnchantedForest04",
"EnchantedForest - EnchantedForest05",
"Eversong - ES BuildingDay01",
"Eversong - ES BuildingDay02",
"Eversong - ES BuildingNight01",
"Eversong - ES BuildingNight02",
"Eversong - ES RuinsDay01",
"Eversong - ES RuinsDay02",
"Eversong - ES RuinsDay03",
"Eversong - ES RuinsNight01",
"Eversong - ES RuinsNight02",
"Eversong - ES RuinsNight03",
"Eversong - ES ScenicIntroNight01",
"Eversong - ES ScortchedDay01",
"Eversong - ES ScortchedDay02",
"Eversong - ES ScortchedNight01",
"Eversong - ES ScortchedNight02",
"Eversong - ES SilvermoonIntro01",
"Eversong - ES SilvermoonDay01",
"Eversong - ES SilvermoonDay02",
"Eversong - ES SilvermoonDay03",
"Eversong - ES SilvermoonNight01",
"Eversong - ES SilvermoonNight02",
"Eversong - ES SilvermoonNight03",
"Eversong - ES SunstriderDay01",
"Eversong - ES SunstriderDay02",
"Eversong - ES SunstriderDay03",
"Eversong - ES SunstriderNight01",
"Eversong - ES SunstriderNight02",
"Eversong - ES SunstriderNight03",
"EvilForest - DayEvilForest01",
"EvilForest - DayEvilForest02",
"EvilForest - DayEvilForest03",
"EvilForest - NightEvilForest01",
"EvilForest - NightEvilForest02",
"EvilForest - NightEvilForest03",
"Forest - DayForest01",
"Forest - DayForest02",
"Forest - DayForest03",
"Forest - NightForest01",
"Forest - NightForest02",
"Forest - NightForest03",
"Forest - NightForest04",
"Ghostlands - GL EversongDark 1",
"Ghostlands - GL EversongDark 2",
"Ghostlands - GL EversongDark 3",
"Ghostlands - GL EversongDark 4",
"Ghostlands - GL Forest1Day01",
"Ghostlands - GL Forest1Day02",
"Ghostlands - GL Forest1Night01",
"Ghostlands - GL Forest2Day01",
"Ghostlands - GL Forest2Night01",
"Ghostlands - GL Forest2Night02",
"Ghostlands - GL Forest3Day01",
"Ghostlands - GL Forest3Night01",
"Ghostlands - GL Forest3Night02",
"Ghostlands - GL Forest3Night03",
"Ghostlands - GL Scenic 1",
"Ghostlands - GL Scenic 2",
"Ghostlands - GL Scenic 3",
"Ghostlands - GL Shalandis 1",
"Ghostlands - GL Shalandis 2",
"Ghostlands - GL Shalandis 3",
"GhostGhostMusic03",
"GrizzlyHills - GH General A Day01",
"GrizzlyHills - GH General A Day02",
"GrizzlyHills - GH General A Day03",
"GrizzlyHills - GH General A Day04",
"GrizzlyHills - GH General A Night01",
"GrizzlyHills - GH General A Night02",
"GrizzlyHills - GH General B Day01",
"GrizzlyHills - GH General B Day02",
"GrizzlyHills - GH General B Night01",
"GrizzlyHills - GH General B Night02",
"GrizzlyHills - GH Intro1 1",
"GrizzlyHills - GH Intro2 1",
"GrizzlyHills - GH Day01",
"GrizzlyHills - GH Day02",
"GrizzlyHills - GH Day03",
"GrizzlyHills - GH Day04",
"GrizzlyHills - GH Day05",
"GrizzlyHills - GH Day06",
"GrizzlyHills - GH Day07",
"GrizzlyHills - GH Day08",
"GrizzlyHills - GH Day09",
"GrizzlyHills - GH Night01",
"GrizzlyHills - GH Night02",
"GrizzlyHills - GH Night03",
"GrizzlyHills - GH Night04",
"GrizzlyHills - GH Night05",
"GrizzlyHills - GH Night06",
"HellfirePeninsula - BL HE Ogre 1",
"HellfirePeninsula - BL HE Ogre 2",
"HellfirePeninsula - HE ArmouryIntro 1",
"HellfirePeninsula - HE CitadelDemon 1",
"HellfirePeninsula - HE CitadelDemon 2",
"HellfirePeninsula - HE CitadelIntro 1",
"HellfirePeninsula - HE General 1",
"HellfirePeninsula - HE General 2",
"HellfirePeninsula - HE General 3",
"HellfirePeninsula - HE General 4",
"HellfirePeninsula - HE General 5",
"HellfirePeninsula - HE PathOfGloryIntro 1",
"HellfirePeninsula - HE Ramparts 1",
"HellfirePeninsula - HE Ramparts 2",
"HellfirePeninsula - HE StairsIntro 1",
"HellfirePeninsula - HE WistfulIntro 1",
"HellfirePeninsula - HE WistfulIntro 2",
"HowlingFjord - HF Dist 1",
"HowlingFjord - HF Dist 2",
"HowlingFjord - HF Dist 3",
"HowlingFjord - HF Dist 4",
"HowlingFjord - HF Dist 5",
"HowlingFjord - HF Dist 6",
"HowlingFjord - HF Dist 7",
"HowlingFjord - HF General Day01",
"HowlingFjord - HF General Day02",
"HowlingFjord - HF General Day03",
"HowlingFjord - HF General Day04",
"HowlingFjord - HF General Day05",
"HowlingFjord - HF General Day06",
"HowlingFjord - HF General Day07",
"HowlingFjord - HF General Night01",
"HowlingFjord - HF General Night02",
"HowlingFjord - HF General Night03",
"HowlingFjord - HF General Night04",
"HowlingFjord - HF Tusk KamaguaDay01",
"HowlingFjord - HF Tusk KamaguaDay02",
"HowlingFjord - HF Tusk KamaguaNight01",
"HowlingFjord - HF Tusk KamaguaNight02",
"IcecrownGlacier - IC GeneralIntro 01",
"IcecrownGlacier - IC GeneralIntro 02",
"IcecrownGlacier - IC GeneralIntro 03",
"IcecrownGlacier - IC General Day01",
"IcecrownGlacier - IC General Day02",
"IcecrownGlacier - IC General Day03",
"IcecrownGlacier - IC General Day04",
"IcecrownGlacier - IC General Night01",
"IcecrownGlacier - IC General Night02",
"IcecrownGlacier - IC General Night03",
"IcecrownGlacier - IC General Night04",
"IcecrownGlacier - IC General Night05",
"IcecrownRaid - IR BronzeJam",
"IcecrownRaid - IR CrimsonHall1",
"IcecrownRaid - IR CrimsonHall2",
"IcecrownRaid - IR CrimsonHall3",
"IcecrownRaid - IR CrimsonHall4",
"IcecrownRaid - IR ForgeofSouls1",
"IcecrownRaid - IR ForgeofSouls2",
"IcecrownRaid - IR ForgeofSouls3",
"IcecrownRaid - IR ForgeofSouls4",
"IcecrownRaid - IR Frostmourne1",
"IcecrownRaid - IR Frostmourne2",
"IcecrownRaid - IR Frostmourne3",
"IcecrownRaid - IR FrozenThrone 01",
"IcecrownRaid - IR FrozenThrone 02",
"IcecrownRaid - IR FrozenThrone 03",
"IcecrownRaid - IR FrozenThrone 04",
"IcecrownRaid - IR FrozenThrone 05",
"IcecrownRaid - IR FrozenThrone 06",
"IcecrownRaid - IR FrozenThrone 07",
"IcecrownRaid - IR Gunships",
"IcecrownRaid - IR GunStrings",
"IcecrownRaid - IR HallsofChase",
"IcecrownRaid - IR HallsofReflection",
"IcecrownRaid - IR IceFortress",
"IcecrownRaid - IR IceFortress1",
"IcecrownRaid - IR IceFortress2",
"IcecrownRaid - IR IceFortress3",
"IcecrownRaid - IR IceFortress4",
"IcecrownRaid - IR LadyortheLich",
"IcecrownRaid - IR LetHimPass",
"IcecrownRaid - IR LightsHammer1",
"IcecrownRaid - IR LightsHammer2",
"IcecrownRaid - IR LightsHammer3",
"IcecrownRaid - IR LightsHammer4",
"IcecrownRaid - IR LightsHammer5",
"IcecrownRaid - IR LightsHammer6",
"IcecrownRaid - IR ReflectedHalls1",
"IcecrownRaid - IR ReflectedHalls2",
"IcecrownRaid - IR ReflectedHalls3",
"IcecrownRaid - IR ReflectedHalls4",
"IcecrownRaid - IR ReflectedHalls5",
"IcecrownRaid - IR RunK 01",
"IcecrownRaid - IR RunK 02",
"IcecrownRaid - IR RunK 03",
"IcecrownRaid - IR RunL 01",
"IcecrownRaid - IR RunL 02",
"IcecrownRaid - IR Sindragosa",
"IcecrownRaid - IR SindraStrings",
"IcecrownRaid - IR StingH 01",
"IcecrownRaid - IR StingH 02",
"IcecrownRaid - IR StingH 03",
"IcecrownRaid - IR StingH 04",
"IcecrownRaid - IR StingH 05",
"IcecrownRaid - IR StingH 06",
"IcecrownRaid - IR Summit1",
"IcecrownRaid - IR Summit2",
"IcecrownRaid - IR Summit3",
"IcecrownRaid - IR Summit4",
"IcecrownRaid - IR Summit5",
"IcecrownRaid - IR A 01",
"IcecrownRaid - IR A 02",
"IcecrownRaid - IR A 03",
"IcecrownRaid - IR A 04",
"IcecrownRaid - IR A 05",
"IcecrownRaid - IR A 06",
"IcecrownRaid - IR B 01",
"IcecrownRaid - IR D 01",
"IcecrownRaid - IR D 02",
"IcecrownRaid - IR D 03",
"IcecrownRaid - IR D 04",
"IcecrownRaid - IR D 05",
"IcecrownRaid - IR D 06",
"IcecrownRaid - IR E 01",
"IcecrownRaid - IR E 02",
"IcecrownRaid - IR E 03",
"IcecrownRaid - IR E 04",
"IcecrownRaid - IR E 05",
"IcecrownRaid - IR F 01",
"IcecrownRaid - IR F 02",
"IcecrownRaid - IR F 03",
"IcecrownRaid - IR F 04",
"IcecrownRaid - IR F 05",
"IcecrownRaid - IR F 06",
"IcecrownRaid - IR F 07",
"IcecrownRaid - IR F 08",
"IcecrownRaid - IR G 01",
"IcecrownRaid - IR G 02",
"IcecrownRaid - IR G 03",
"IcecrownRaid - IR G 04",
"IcecrownRaid - IR G 05",
"IcecrownRaid - IR G 06",
"IcecrownRaid - IR J 01",
"IcecrownRaid - IR J 02",
"IcecrownRaid - IR J 03",
"IcecrownRaid - IR J 04",
"IcecrownRaid - IR J 05",
"IcecrownRaid - IR J 06",
"IcecrownRaid - IR M 01",
"IcecrownRaid - IR Z 01",
"IcecrownRaid - IR Z 02",
"Jungle - DayJungle01",
"Jungle - DayJungle02",
"Jungle - DayJungle03",
"Jungle - NightJungle01",
"Jungle - NightJungle02",
"Jungle - NightJungle03",
"Karazhan - KA Backstage 1",
"Karazhan - KA Backstage 2",
"Karazhan - KA FoyerIntro 1",
"Karazhan - KA Foyer 1",
"Karazhan - KA Foyer 2",
"Karazhan - KA Foyer 3",
"Karazhan - KA Foyer 4",
"Karazhan - KA General 1",
"Karazhan - KA General 2",
"Karazhan - KA General 3",
"Karazhan - KA General 4",
"Karazhan - KA General 5",
"Karazhan - KA General 6",
"Karazhan - KA General 7",
"Karazhan - KA Library 1",
"Karazhan - KA Library 2",
"Karazhan - KA Library 3",
"Karazhan - KA Library 4",
"Karazhan - KA Malchezar 1",
"Karazhan - KA Malchezar 2",
"Karazhan - KA Malchezar 3",
"Karazhan - KA OperaHarpsi 1",
"Karazhan - KA OperaOrgan 1",
"Karazhan - KA StableIntro 1",
"Karazhan - KA Stable 1",
"Karazhan - KA Stable 2",
"Karazhan - KA Stable 3",
"Karazhan - KA Tower 1",
"Karazhan - KA Tower 2",
"Karazhan - KA Tower 3",
"LakeWintergrasp - WG Contested 01",
"LakeWintergrasp - WG Contested 02",
"LakeWintergrasp - WG Contested 03",
"LakeWintergrasp - WG General 01",
"LakeWintergrasp - WG General 02",
"LakeWintergrasp - WG General 03",
"LakeWintergrasp - WG General 04",
"LakeWintergrasp - WG General 05",
"Mountain - DayMountain01",
"Mountain - DayMountain02",
"Mountain - DayMountain03",
"Mountain - NightMountain01",
"Mountain - NightMountain02",
"Mountain - NightMountain03",
"Mountain - NightMountain04",
"Nagrand - NA DiamondIntro 1",
"Nagrand - NA GeneralDay01",
"Nagrand - NA GeneralDay02",
"Nagrand - NA GeneralDay03",
"Nagrand - NA GeneralNight01",
"Nagrand - NA GeneralNight02",
"Nagrand - NA GeneralNight03",
"Naxxramas - AbominationBoss1",
"Naxxramas - AbominationBoss2",
"Naxxramas - AbominationWing1",
"Naxxramas - AbominationWing2",
"Naxxramas - AbominationWing3",
"Naxxramas - Frostwyrm1",
"Naxxramas - Frostwyrm2",
"Naxxramas - Frostwyrm3",
"Naxxramas - Frostwyrm4",
"Naxxramas - HubBase1",
"Naxxramas - HubBase2",
"Naxxramas - KelThuzad1",
"Naxxramas - KelThuzad2",
"Naxxramas - KelThuzad3",
"Naxxramas - PlagueBoss1",
"Naxxramas - PlagueWing1",
"Naxxramas - PlagueWing2",
"Naxxramas - PlagueWing3",
"Naxxramas - SpiderBoss1",
"Naxxramas - SpiderBoss2",
"Naxxramas - SpiderWing1",
"Naxxramas - SpiderWing2",
"Naxxramas - SpiderWing3",
"Naxxramas - 1",
"Naxxramas - 2",
"Naxxramas - 3",
"Naxxramas - 4",
"Naxxramas - 5",
"Naxxramas - 6",
"Netherstorm - NS General 1",
"Netherstorm - NS General 2",
"Netherstorm - NS General 3",
"Netherstorm - NS General 4",
"Netherstorm - NS General 5",
"Netherstorm - NS General 6",
"Netherstorm - NS General 7",
"Netherstorm - NS General 8",
"Netherstorm - NS General 9",
"Netherstorm - NS GeneralUni10",
"Netherstorm - NS MushroomIntro 1",
"Netherstorm - NS MushroomIntro 2",
"Netherstorm - NS MushroomIntro 3",
"Netherstorm - NS NetherplantIntro 1",
"Netherstorm - NS NetherplantIntro 2",
"Netherstorm - NS NetherplantIntro 3",
"Netherstorm - NS NetherplantIntro 4",
"Nexus - NZ NexusAction 1",
"Nexus - NZ NexusAction 2",
"Nexus - NZ NexusAction 3",
"Nexus - NZ NexusAction 4",
"Nexus - NZ NexusAction 5",
"Nexus - NZ NexusHail 1",
"Nexus - NZ NexusHail 2",
"Nexus - NZ NexusPulse 1",
"Nexus - NZ NexusPulse 2",
"Nexus - NZ NexusQuiet 1",
"Nexus - NZ NexusQuiet 2",
"Nexus - NZ NexusQuiet 3",
"Nexus - NZ NexusQuiet 4",
"Northrend - IronDwarf - Dwarf A Day01",
"Northrend - IronDwarf - Dwarf A Night01",
"Northrend - IronDwarf - Dwarf ADark 1",
"Northrend - IronDwarf - Dwarf B Day02",
"Northrend - IronDwarf - Dwarf B Night02",
"Northrend - IronDwarf - Dwarf B 2",
"Northrend - IronDwarf - Dwarf C Day03",
"Northrend - IronDwarf - Dwarf C Night03",
"Northrend - IronDwarf - Dwarf C 3",
"Northrend - IronDwarf - Dwarf CDark 4",
"Northrend - IronDwarf - Dwarf D Day04",
"Northrend - IronDwarf - Dwarf D Night04",
"Northrend - IronDwarf - Dwarf DDark 5",
"Northrend - NorthrendTransportDay",
"Northrend - NorthrendTransportNight",
"Northrend - Orc - Orc Intro01",
"Northrend - Orc - Orc Day01",
"Northrend - Orc - Orc Day02",
"Northrend - Orc - Orc Day03",
"Northrend - Orc - Orc Day04",
"Northrend - Orc - Orc Night01",
"Northrend - Orc - Orc Night02",
"Northrend - Orc - Orc Night03",
"Northrend - Taunka - Taunka A Day01",
"Northrend - Taunka - Taunka A Night01",
"Northrend - Taunka - Taunka A 1",
"Northrend - Taunka - Taunka B Day02",
"Northrend - Taunka - Taunka B Night02",
"Northrend - Taunka - Taunka C Day03",
"Northrend - Taunka - Taunka C Night03",
"Northrend - Taunka - Taunka D Day04",
"Northrend - Taunka - Taunka D Night04",
"Northrend - Taunka - Taunka D 2",
"Northrend - Taunka - Taunka E 3",
"Northrend - Troll - Troll 01",
"Northrend - Troll - Troll 02",
"Northrend - Troll - Troll 03",
"Northrend - Troll - Troll 04",
"OS1",
"OS2",
"OS3",
"OS4",
"OS5",
"OutlandGeneral - Action 1",
"OutlandGeneral - AllianceBase 1",
"OutlandGeneral - AllianceBase 2",
"OutlandGeneral - ArakkoaIntro 1",
"OutlandGeneral - ArakkoaIntro 2",
"OutlandGeneral - BloodElfBase 1",
"OutlandGeneral - BloodElfBase 2",
"OutlandGeneral - BurningLegionIntro 1",
"OutlandGeneral - BurningLegionIntro 2",
"OutlandGeneral - CenarionIntro 1",
"OutlandGeneral - CenarionIntro 2",
"OutlandGeneral - CenarionIntro 3",
"OutlandGeneral - Corrupt01",
"OutlandGeneral - Corrupt02",
"OutlandGeneral - Corrupt03",
"OutlandGeneral - Corrupt04",
"OutlandGeneral - Corrupt05",
"OutlandGeneral - Corrupt06",
"OutlandGeneral - Corrupt07",
"OutlandGeneral - CorruptIntro",
"OutlandGeneral - CrystalIntro 1",
"OutlandGeneral - CrystalIntro 2",
"OutlandGeneral - CrystalIntro 3",
"OutlandGeneral - DemonIntro 1",
"OutlandGeneral - DraeneiBase 1",
"OutlandGeneral - DraeneiBase 2r",
"OutlandGeneral - FelOrcIntro 1",
"OutlandGeneral - FelOrcIntro 2",
"OutlandGeneral - HistoricIntro 1",
"OutlandGeneral - HordeBase 1",
"OutlandGeneral - HordeBase 2",
"OutlandGeneral - HordeBase 3",
"OutlandGeneral - HordeBase 4",
"OutlandGeneral - IllidansArmyIntro 1",
"OutlandGeneral - OgreIntro 1",
"OutlandGeneral - OgreIntro 2",
"OutlandGeneral - OrcIntro 1",
"OutlandGeneral - OrcIntro 2",
"OutlandGeneral - OrcIntro 3",
"OutlandGeneral - OrcIntro 4",
"OutlandGeneral - ScenicIntro 1",
"OutlandGeneral - ShamanIntro 1",
"OutlandGeneral - ShamanIntro 2",
"Plains - DayPlains01",
"Plains - DayPlains02",
"Plains - NightPlains01",
"Plains - NightPlains02",
"PVP - PVP6 01",
"PVP - PVP6 02",
"PVP - PVP7 01",
"PVP - PVP7 02",
"PVP - PVP7Moment1 01",
"PVP - PVP7Moment1 02",
"PVP - PVP7Moment2 01",
"PVP - PVP7Moment2 02",
"PVP - PVP7Moment3 01",
"PVP - PVP7StingerEnd 01",
"PVP - PVP7StingerIntro 01",
"PVP - PvP1",
"PVP - PvP2",
"PVP - PvP3",
"PVP - PvP4",
"PVP - PvP5",
"ShadowmoonValley - SV General 1",
"ShadowmoonValley - SV General 2",
"ShadowmoonValley - SV General 3",
"ShadowmoonValley - SV General 4",
"ShadowmoonValley - SV General 5",
"ShadowmoonValley - SV General 6",
"SholazarBasin - SB Crystals 1",
"SholazarBasin - SB Crystals 2",
"SholazarBasin - SB Fire 1",
"SholazarBasin - SB Fire 2",
"SholazarBasin - SB Fire 3",
"SholazarBasin - SB Fire 4",
"SholazarBasin - SB LifebloodCave 1",
"SholazarBasin - SB LifebloodCave 2",
"SholazarBasin - SB LifebloodCave 3",
"SholazarBasin - SB MakersTerrace 1",
"SholazarBasin - SB MakersTerrace 2",
"SholazarBasin - SB PathofLifeWarden 1",
"SholazarBasin - SB PathofLifeWarden 2",
"SholazarBasin - SB SholazarDay01",
"SholazarBasin - SB SholazarDay02",
"SholazarBasin - SB SholazarDay03",
"SholazarBasin - SB SholazarDay04",
"SholazarBasin - SB SholazarDay05",
"SholazarBasin - SB SholazarDay06",
"SholazarBasin - SB SholazarNight01",
"SholazarBasin - SB SholazarNight02",
"SholazarBasin - SB SholazarNight03",
"SholazarBasin - SB SholazarNight04",
"SholazarBasin - SB SholazarNight05",
"StormPeaks - SP GeneralA Day01",
"StormPeaks - SP GeneralA Night01",
"StormPeaks - SP GeneralADark 1",
"StormPeaks - SP GeneralB Day02",
"StormPeaks - SP GeneralB Night02",
"StormPeaks - SP GeneralB 2",
"StormPeaks - SP GeneralC Day03",
"StormPeaks - SP GeneralC Night03",
"StormPeaks - SP GeneralC 3",
"StormPeaks - SP GeneralD Day04",
"StormPeaks - SP GeneralD Night04",
"StormPeaks - SP GeneralD 4",
"StormPeaks - SP GeneralE Day05",
"StormPeaks - SP GeneralE Night05",
"StormPeaks - SP GeneralE 5",
"StratholmePast - CT PastAlleyEnd",
"StratholmePast - CT PastAlleyIntro",
"StratholmePast - CT PastBattle01",
"StratholmePast - CT PastBattle02",
"StratholmePast - CT PastBattle03",
"StratholmePast - CT PastEndStinger",
"StratholmePast - CT PastIndoorsIntro",
"StratholmePast - CT PastIntro",
"StratholmePast - CT PastMalGanis",
"StratholmePast - CT PastOutdoorsIntro",
"StratholmePast - CT PastOutdoorsANight",
"StratholmePast - CT PastOutdoorsA",
"StratholmePast - CT PastOutdoorsBNight",
"StratholmePast - CT PastOutdoorsB",
"StratholmePast - CT Past",
"Sunwell - SW AssemblyChamber 1",
"Sunwell - SW AssemblyChamber 2",
"Sunwell - SW FelEnergy 1",
"Sunwell - SW IsleDark 1",
"Sunwell - SW IsleDark 2",
"Sunwell - SW IsleDark 3",
"Sunwell - SW IsleLight 1",
"Sunwell - SW IsleLight 2",
"Sunwell - SW IsleLight 3",
"Sunwell - SW IsleMed 1",
"Sunwell - SW IsleMed 2",
"Sunwell - SW IsleMed 3",
"Sunwell - SW MagistersArrival 1",
"Sunwell - SW MagistersAsylum 1",
"Sunwell - SW MagistersAsylum 2",
"Sunwell - SW MagistersAsylum 3",
"Sunwell - SW MagistersTerrace 1",
"Sunwell - SW MagistersTerrace 2",
"Sunwell - SW MagistersTerrace 3",
"Sunwell - SW MagistersTerrace 4",
"Sunwell - SW MagistersTerrace 5",
"Sunwell - SW PlateauSunwellArrival 1",
"Sunwell - SW PlateauSunwell 1",
"Sunwell - SW PlateauSunwell 2",
"Sunwell - SW PlateauSunwell 3",
"Sunwell - SW PlateauSunwell 4",
"Sunwell - SW PlateauSunwell 5",
"Sunwell - SW PlateauSunwell 6",
"Sunwell - SW QuelDanas 1",
"Sunwell - SW QuelDanas 2",
"Sunwell - SW Sanctum 1",
"Sunwell - SW ShorelAran 1",
"Sunwell - SW SunwellBombingRun 1",
"Sunwell - SW SunwellFlyby 1",
"Sunwell - SW TheWell 1",
"Sunwell - SW TheWell 2",
"Sunwell - SW TheWell 3",
"TavernAlliance - TavernAlliance01",
"TavernAlliance - TavernAlliance02",
"TavernDwarf - RA DwarfTavern1A",
"TavernDwarf - RA DwarfTavern1B",
"TavernDwarf - RA DwarfTavern2A",
"TavernDwarf - RA DwarfTavern2B",
"TavernDwarf - RA DwarfTavern3",
"TavernHorde - TavernHorde01",
"TavernHorde - TavernHorde02",
"TavernHorde - TavernHorde03",
"TavernHorde - undead dance",
"TavernHuman - RA HumanTavern1A",
"TavernHuman - RA HumanTavern1B",
"TavernHuman - RA HumanTavern2A",
"TavernHuman - RA HumanTavern2B",
"TavernHuman - RA Tavern1 RevisitedA",
"TavernHuman - RA Tavern1 RevisitedB",
"TavernNightElf - RA TempleOfTheMoonA",
"TavernNightElf - RA TempleOfTheMoonB",
"TavernOrc - RA OrcRestArea1A",
"TavernOrc - RA OrcRestArea1B",
"TavernOrc - RA OrcRestArea2A",
"TavernOrc - RA OrcRestArea2B",
"TavernOrc - RA OrcRestArea3A",
"TavernOrc - RA OrcRestArea3B",
"TavernPirate - RA PirateTavern1A",
"TavernPirate - RA PirateTavern1B",
"TavernPirate - RA PirateTavern2A",
"TavernPirate - RA PirateTavern2B",
"TavernPirate - RA PirateTavern3A",
"TavernPirate - RA PirateTavern3B",
"TavernTauren - RA TaurenRestArea1A",
"TavernTauren - RA TaurenRestArea1B",
"TavernTauren - RA TaurenRestArea2A",
"TavernTauren - RA TaurenRestArea2B",
"TavernTauren - RA TaurenRestArea3A",
"TavernTauren - RA TaurenRestArea3B",
"TavernUndead - RA UndeadTavern1A",
"TavernUndead - RA UndeadTavern1B",
"TavernUndead - RA UndeadTavern2",
"TavernUndead - RA UndeadTavern3A",
"TavernUndead - RA UndeadTavern3B",
"TempestKeep - TK TempestKeep AMB 11",
"TempestKeep - TK TempestKeep AMB 12",
"TempestKeep - TK TempestKeep AMB 13",
"TempestKeep - TK TempestKeep AMB 14",
"TempestKeep - TK TempestKeep AMB 16",
"TempestKeep - TK TempestKeep AMB 17",
"TempestKeep - TK TempestKeep AMB 18",
"TempestKeep - TK TempestKeep AMB 19",
"TempestKeep - TK TempestKeep AMB 20",
"TempestKeep - TK TempestKeep AMB 22",
"TempestKeep - TK TempestKeep AMB 23",
"TempestKeep - TK TempestKeep BTL10",
"TempestKeep - TK TempestKeep BTL11",
"TempestKeep - TK TempestKeep BTL13",
"TempestKeep - TK TempestKeep STG14",
"TempestKeep - TK TempestKeep STG15",
"TempestKeep - TK TempestKeep STG16",
"Terokkar - TF Auchindoun 1",
"Terokkar - TF Auchindoun 2",
"Terokkar - TF Auchindoun 3",
"Terokkar - TF Bone 1",
"Terokkar - TF Bone 2",
"Terokkar - TF Bone 3",
"Terokkar - TF Bone 4",
"Terokkar - TF Forest 1",
"Terokkar - TF Forest 2",
"Terokkar - TF Forest 3",
"Terokkar - TF Shattrath 1",
"Terokkar - TF Shattrath 2",
"Terokkar - TF Shattrath 3",
"Terokkar - TF Shattrath 4",
"Terokkar - TF Shattrath 5",
"Terokkar - TF Shattrath 6",
"Ulduar - UL LightningBattle",
"Ulduar - UL LightningGeneral01",
"Ulduar - UL LightningGeneral02",
"Ulduar - UL LightningGeneral03",
"Ulduar - UL LightningIntro",
"Ulduar - UL StoneBattle",
"Ulduar - UL StoneGeneral01",
"Ulduar - UL StoneGeneral02",
"Ulduar - UL StoneGeneral03",
"Ulduar - UL StoneIntro",
"UlduarRaidExt - UR Action01",
"UlduarRaidExt - UR Action02",
"UlduarRaidExt - UR Action03",
"UlduarRaidExt - UR Action04",
"UlduarRaidExt - UR Action05",
"UlduarRaidExt - UR Action06",
"UlduarRaidExt - UR Action07",
"UlduarRaidExt - UR Action08",
"UlduarRaidExt - UR Action09",
"UlduarRaidExt - UR Action10",
"UlduarRaidExt - UR Action11",
"UlduarRaidExt - UR Action12",
"UlduarRaidExt - UR Action13",
"UlduarRaidExt - UR Action14",
"UlduarRaidExt - UR Action15",
"UlduarRaidExt - UR Action16",
"UlduarRaidExt - UR Intro01",
"UlduarRaidExt - UR Intro02",
"UlduarRaidExt - UR Intro03",
"UlduarRaidExt - UR Intro04",
"UlduarRaidExt - UR Intro05",
"UlduarRaidExt - UR Intro06",
"UlduarRaidExt - UR Intro07",
"UlduarRaidExt - UR Intro08",
"UlduarRaidExt - UR Intro09",
"UlduarRaidExt - UR 01",
"UlduarRaidExt - UR 02",
"UlduarRaidExt - UR 03",
"UlduarRaidExt - UR 04",
"UlduarRaidExt - UR 05",
"UlduarRaidExt - UR 06",
"UlduarRaidExt - UR 07",
"UlduarRaidExt - UR 08",
"UlduarRaidExt - UR 09",
"UlduarRaidExt - UR 10",
"UlduarRaidExt - UR 11",
"UlduarRaidInt - UR AlgalonBattle01",
"UlduarRaidInt - UR AlgalonBattle02",
"UlduarRaidInt - UR AlgalonHeroIntro",
"UlduarRaidInt - UR AlgalonPlanetaryHall",
"UlduarRaidInt - UR AlgalonVoices",
"UlduarRaidInt - UR FourSigilsHall",
"UlduarRaidInt - UR FourSigilsHeroIntro",
"UlduarRaidInt - UR HallsInstrumental",
"UlduarRaidInt - UR HallsofIronHeroEvent",
"UlduarRaidInt - UR HallsPast",
"UlduarRaidInt - UR MimironB",
"UlduarRaidInt - UR MimironC",
"UlduarRaidInt - UR MimironD",
"UlduarRaidInt - UR MimironE",
"UlduarRaidInt - UR MimironF",
"UlduarRaidInt - UR MimironGhosts",
"UlduarRaidInt - UR MimironHeroIntro",
"UlduarRaidInt - UR SigilGhosts",
"UlduarRaidInt - UR TitanGhosts",
"UlduarRaidInt - UR TitanHallsHero",
"UlduarRaidInt - UR TitanMech",
"UlduarRaidInt - UR TitanOrchestraIntro",
"UlduarRaidInt - UR TitanSigils",
"UlduarRaidInt - UR UlduarTone",
"Utgarde Keep - UK General 1",
"Utgarde Keep - UK General 2",
"Utgarde Keep - UK General 3",
"Utgarde Keep - UK General 4",
"Utgarde Keep - UK General 5",
"Utgarde Keep - UK Quiet 1",
"Utgarde Keep - UK Quiet 2",
"VioletHold - VH General 1",
"VioletHold - VH General 2",
"VioletHold - VH General 3",
"Volcanic - DayVolcanic01",
"Volcanic - DayVolcanic02",
"Volcanic - NightVolcanic01",
"Volcanic - NightVolcanic02",
"WanderingIsle - WanderingIsleA Hero 01",
"WanderingIsle - WanderingIsleA 01",
"WanderingIsle - WanderingIsleA 02",
"WanderingIsle - WanderingIsleA 03",
"WanderingIsle - WanderingIsleA 04",
"WanderingIsle - WanderingIsleA 05",
"WanderingIsle - WanderingIsleB Hero 01",
"WanderingIsle - WanderingIsleB 01",
"WanderingIsle - WanderingIsleC Hero 01",
"WanderingIsle - WanderingIsleC 01",
"WanderingIsle - WanderingIsleC 02",
"WanderingIsle - WanderingIsleC 03",
"WanderingIsle - WanderingIsleC 04",
"ZangarMarsh - ZA Coilfang 1",
"ZangarMarsh - ZA Coilfang 2",
"ZangarMarsh - ZA Coilfang 3",
"ZangarMarsh - ZA General 1",
"ZangarMarsh - ZA General 2",
"ZangarMarsh - ZA General 3",
"ZangarMarsh - ZA General 4",
"ZangarMarsh - ZA General 5",
"ZangarMarsh - ZA General 6",
"Zulaman - ZA zulaman AMB10",
"Zulaman - ZA zulaman AMB11",
"Zulaman - ZA zulaman AMB12",
"Zulaman - ZA zulaman AMB13",
"Zulaman - ZA zulaman AMB14",
"Zulaman - ZA zulaman AMB15",
"Zulaman - ZA zulaman BTL11",
"Zulaman - ZA zulaman BTL12",
"Zulaman - ZA zulaman BTL13",
"Zulaman - ZA zulaman BTL14",
"Zulaman - ZA zulaman BTL15",
"Zulaman - ZA zulaman VCT10",
"ZulDrak - ZD GeneralIntro 01",
"ZulDrak - ZD GeneralIntro 02",
"ZulDrak - ZD GeneralIntro 03",
"ZulDrak - ZD GeneralIntro 04",
"ZulDrak - ZD GeneralIntro 05",
"ZulDrak - ZD GeneralIntro 06",
"ZulDrak - ZD General Day01",
"ZulDrak - ZD General Day02",
"ZulDrak - ZD General Day03",
"ZulDrak - ZD General Day04",
"ZulDrak - ZD General Night01",
"ZulDrak - ZD General Night02",
"ZulDrak - ZD General Night03",
"ZulDrak - ZD General Night04",
"ZulDrak - ZD HarKoa Intro01",
"ZulDrak - ZD HarKoa Intro02",
"ZulDrak - ZD MamToth Intro01",
"ZulDrak - ZD MamToth Intro02",
"ZulDrak - ZD QuetzLun Intro01",
"ZulDrak - ZD QuetzLun Intro02",
"ZulDrak - ZD Rhunok Intro01",
"ZulDrak - ZD Rhunok Intro02",
"ZulDrak - ZD Sseratus Intro01",
"ZulDrak - ZD Sseratus Intro02",
"Draenor - AHerosSacrifice V1",
"Draenor - AHerosSacrifice V2",
"Draenor - AHerosSacrifice V3a",
"Draenor - AHerosSacrifice V3b",
"Draenor - AHerosSacrifice V4",
"Draenor - AHerosSacrifice V5",
"Draenor - ALightInTheDarkness V1",
"Draenor - ALightInTheDarkness V2",
"Draenor - ALightInTheDarkness V3",
"Draenor - ALightInTheDarkness V3a",
"Draenor - ASiegeOfWorlds MainTitle",
"Draenor - Arak2 H",
"Draenor - ArmyLife H",
"Draenor - Army A",
"Draenor - Army Stinger1",
"Draenor - Army Stinger2",
"Draenor - BFreedom H1",
"Draenor - BFreedon H2",
"Draenor - Blackrock A",
"Draenor - Blackrock B",
"Draenor - Blackrock C",
"Draenor - Blackrock D",
"Draenor - Blackrock E",
"Draenor - Blackrock H",
"Draenor - CallOfTheWarrior A",
"Draenor - CallOfTheWarrior C",
"Draenor - CallOfTheWarrior H",
"Draenor - CavernsOfLife H",
"Draenor - ChieftansGather H",
"Draenor - ColdMountain Duet H",
"Draenor - EagleOfDraenor H",
"Draenor - Eagle A",
"Draenor - Eagle B",
"Draenor - Eagle C",
"Draenor - Eagle D",
"Draenor - ElunesShadow A",
"Draenor - ElunesShadow B",
"Draenor - ElunesShadow C",
"Draenor - ElunesShadow H",
"Draenor - EternalNight H",
"Draenor - EtherealEmbers C",
"Draenor - EtherealEmbers D",
"Draenor - EtherealEmbers E",
"Draenor - EtherealEmbers F",
"Draenor - EtherealEmbers H",
"Draenor - EtherealEssence H1",
"Draenor - EtherealEssence H2",
"Draenor - FelWasteland A",
"Draenor - FelWasteland B",
"Draenor - FelWasteland C",
"Draenor - FelWasteland H",
"Draenor - Foreshadowing H",
"Draenor - Forsaken A",
"Draenor - Forsaken H",
"Draenor - GardensOfKarabor A",
"Draenor - GardensOfKarabor B",
"Draenor - GardensOfKarabor H",
"Draenor - GarrisonBuildingComplete",
"Draenor - GarrisonBuildingComplete2",
"Draenor - Grinspiration A",
"Draenor - Grinspiration B",
"Draenor - Grinspiration C",
"Draenor - Grinspiration H1",
"Draenor - Grinspiration H2",
"Draenor - GrommashHellscream V1",
"Draenor - GrommashHellscream V2a",
"Draenor - GrommashHellscream V2b",
"Draenor - GrommashHellscream V3",
"Draenor - HerdingClans H",
"Draenor - IronDawn V1",
"Draenor - IronDawn V2",
"Draenor - IronDawn V3a",
"Draenor - IronDawn V3b",
"Draenor - IronDawn V4",
"Draenor - KeepersOfTheTemple H",
"Draenor - KhadgarsPlan V1",
"Draenor - KhadgarsPlan V2",
"Draenor - KhadgarsPlan V3",
"Draenor - KhadgarsPlan V4",
"Draenor - LaboriousMisery A",
"Draenor - LaboriousMisery H",
"Draenor - MagnificentDesolation2 A2",
"Draenor - MagnificentDesolation2 H",
"Draenor - MagnificentDesolation2 H1",
"Draenor - MagnificentDesolation2 H2",
"Draenor - MagnificentDesolation A",
"Draenor - MagnificentDesolation B",
"Draenor - MagnificentDesolation H",
"Draenor - MagnificentDesolation Piano",
"Draenor - Malach H1",
"Draenor - Malach H2",
"Draenor - Malach H3",
"Draenor - Malach H4",
"Draenor - MalevolentMystique A",
"Draenor - MalevolentMystique B1",
"Draenor - MalevolentMystique B2",
"Draenor - MalevolentMystique C",
"Draenor - MalevolentMystique H",
"Draenor - MalevolentPrescience B",
"Draenor - MalevolentPrescience H",
"Draenor - ManDown A1",
"Draenor - ManDown A2",
"Draenor - ManDown A3",
"Draenor - ManDown B",
"Draenor - ManDown C",
"Draenor - ManDown D",
"Draenor - ManDown E",
"Draenor - ManDown F",
"Draenor - ManDown H1",
"Draenor - Mobilize A",
"Draenor - Mobilize B1",
"Draenor - Mobilize B2",
"Draenor - Mobilize C1",
"Draenor - Mobilize C2",
"Draenor - Mobilize D",
"Draenor - Mobilize E Stinger",
"Draenor - Mobilize H",
"Draenor - MountainsIntro A1",
"Draenor - MountainsIntro A2",
"Draenor - MountainsOfNagrand A1",
"Draenor - MountainsOfNagrand A2",
"Draenor - MountainsOfNagrand B",
"Draenor - MountainsOfNagrand H",
"Draenor - Mountains Ambient2",
"Draenor - Mountains Ambient3",
"Draenor - Mountains Stinger1",
"Draenor - Mystic A1",
"Draenor - Mystic A2",
"Draenor - Mystic B1",
"Draenor - Mystic B2",
"Draenor - Mystic C",
"Draenor - Mystic C2",
"Draenor - Mystic D1",
"Draenor - Mystic D2",
"Draenor - Mystic E",
"Draenor - Mystic F",
"Draenor - Mystic G",
"Draenor - Mystic H",
"Draenor - Nagrand V1",
"Draenor - Nagrand V2",
"Draenor - Nagrand V3a",
"Draenor - Nagrand V3b",
"Draenor - Nagrand V4",
"Draenor - Nagrand V5",
"Draenor - Nagrand V6",
"Draenor - Nagrand V7",
"Draenor - NightSpires V1",
"Draenor - NightSpires V2",
"Draenor - NightSpires V3",
"Draenor - NightSpires V4",
"Draenor - OgreMines A1",
"Draenor - OgreMines A2",
"Draenor - OgreMines B",
"Draenor - OgreMines H1",
"Draenor - OgreMines H2",
"Draenor - PatiencePoint A1",
"Draenor - PatiencePoint A2",
"Draenor - PatiencePoint B1",
"Draenor - PatiencePoint B2",
"Draenor - PatiencePoint H",
"Draenor - PlightOfTheOgres H1",
"Draenor - PlightOfTheOgres H2",
"Draenor - Premonition H",
"Draenor - PrevalentConfliction A",
"Draenor - ProtectTheThrone H1",
"Draenor - ProtectTheThrone H2",
"Draenor - ProtectTheThrone H3",
"Draenor - Proudmoore H",
"Draenor - QuietHeart A",
"Draenor - QuietHeart A1",
"Draenor - QuietHeart A2",
"Draenor - QuietHeart H",
"Draenor - QuietHeart H1",
"Draenor - QuietHeart H2",
"Draenor - RiseToTheDark H1",
"Draenor - RiseToTheDark H2",
"Draenor - Sacrifice 2a",
"Draenor - Sacrifice 2h",
"Draenor - Sacrifice B",
"Draenor - ShadowmoonPt1 A",
"Draenor - ShadowmoonPt1 H",
"Draenor - ShadowmoonRising H",
"Draenor - ShadowmoonSunsetIntro H",
"Draenor - ShadowmoonSunsetReprise H",
"Draenor - Shadowmoon V1",
"Draenor - Shadowmoon V2",
"Draenor - Shadowmoon V3",
"Draenor - Shadowmoon V4",
"Draenor - Shadowmoon V5",
"Draenor - Shakedown A",
"Draenor - Shakedown B",
"Draenor - Shakedown C",
"Draenor - SmackTheGiant H1",
"Draenor - SmackTheGiant H2",
"Draenor - SmackTheGiant H3",
"Draenor - SmackTheGiant H4",
"Draenor - SpiresOfArak V1",
"Draenor - SpiresOfArak V2",
"Draenor - SpiresOfArak V4",
"Draenor - StormlordsOnTheMarch H1",
"Draenor - StormlordsOnTheMarch H2",
"Draenor - StormlordsOnTheMarch H3",
"Draenor - TheClansJoin A",
"Draenor - TheClansJoin B",
"Draenor - TheClansJoin H",
"Draenor - Tome A",
"Draenor - Tome B",
"Draenor - Tome H",
"Draenor - TraversingTheSpires A",
"Draenor - TraversingTheSpires B",
"Draenor - TraversingTheSpires C",
"Draenor - TraversingTheSpires H1",
"Draenor - TraversingTheSpires H2",
"Draenor - TsHaveIt A",
"Draenor - TsHaveIt B",
"Draenor - TsHaveIt C",
"Draenor - TsHaveIt H",
"Draenor - Village A",
"Draenor - Village B",
"Draenor - Village C1",
"Draenor - Village C2",
"Draenor - Village D",
"Draenor - Village F",
"Draenor - Village H",
"Draenor - Voce C",
"Draenor - Vows A1",
"Draenor - Vows A2",
"Draenor - Vows A3",
"Draenor - Vows B",
"Draenor - Vows C1",
"Draenor - Vows C2",
"Draenor - Vows C3",
"Draenor - Vows D1",
"Draenor - Vows D2",
"Draenor - Vows H1",
"Draenor - Vows H2",
"Draenor - Vows H3",
"Draenor - Vows H4",
"Draenor - Vows H5",
"Draenor - WarriorsJourney A",
"Draenor - WarriorsJourney B1",
"Draenor - WarriorsJourney B2",
"Draenor - WarriorsJourney B3",
"Draenor - WarriorsJourney C",
"Draenor - WarriorsJourney D",
"Draenor - WarriorsJourney E",
"Draenor - WarriorsJourney H1",
"Draenor - WarriorsJourney H2",
"Draenor - WarriorsJourney H3",
"Draenor - WarriorsJourney H4",
"Draenor - Warsong V1",
"Draenor - Warsong V2",
"Draenor - Warsong V3a",
"Draenor - Warsong V3b",
"Draenor - Warsong V4",
"Draenor - WolfAtTheGates A",
"Draenor - WolfAtTheGates B",
"Draenor - WolfAtTheGates H",
"Draenor - Wonder A1",
"Draenor - Wonder A2",
"Draenor - Wonder H",
"Draenor - WorldExpo A1",
"Draenor - WorldExpo A2",
"Draenor - WorldExpo A3",
"Draenor - WorldExpo B",
"Draenor - WorldExpo C",
"Draenor - WorldExpo D",
"Draenor - WorldExpo E1",
"Draenor - WorldExpo E2",
"Draenor - WorldExpo F1",
"Draenor - WorldExpo F2",
"Draenor - WorldExpo F3",
"Draenor - WorldExpo G",
"Draenor - WorldExpo H",
"Draenor - Hellfire Citadel - Falling 1A",
"Draenor - Hellfire Citadel - Falling 1B",
"Draenor - Hellfire Citadel - Falling 2H",
"Draenor - Hellfire Citadel - FelEssence A",
"Draenor - Hellfire Citadel - FelEssence B",
"Draenor - Hellfire Citadel - FelEssence C",
"Draenor - Hellfire Citadel - FelEssence D",
"Draenor - Hellfire Citadel - FelEssence H",
"Draenor - Hellfire Citadel - FeuDeLEnfer A",
"Draenor - Hellfire Citadel - FeuDeLEnfer H",
"Draenor - Hellfire Citadel - LostMoon A",
"Draenor - Hellfire Citadel - LostMoon B",
"Draenor - Hellfire Citadel - LostMoon H",
"Draenor - Hellfire Citadel - MortalNight A",
"Draenor - Hellfire Citadel - MortalNight B",
"Draenor - Hellfire Citadel - MortalNight C",
"Draenor - Hellfire Citadel - MortalNight H",
"Draenor - Hellfire Citadel - TanaanGloom A",
"Draenor - Hellfire Citadel - TanaanGloom B",
"Draenor - Hellfire Citadel - TanaanGloom C",
"Draenor - Hellfire Citadel - TanaanGloom H",
"Draenor - Hellfire Citadel - Tanaander A",
"Draenor - Hellfire Citadel - Tanaander B",
"Draenor - Hellfire Citadel - Tanaander C",
"Draenor - Hellfire Citadel - Tanaander H",
"Draenor - Hellfire Citadel - TheWanderer A",
"Draenor - Hellfire Citadel - TheWanderer B",
"Draenor - Hellfire Citadel - TheWanderer H",
"Draenor - Hellfire Citadel - Undaunted A",
"Draenor - Hellfire Citadel - Undaunted B",
"Draenor - Hellfire Citadel - Undaunted H",
"Legion - AnduinPt1 A1",
"Legion - AnduinPt1 A2",
"Legion - AnduinPt1 B",
"Legion - AnduinPt1 C",
"Legion - AnduinPt1 D",
"Legion - AnduinPt1 E",
"Legion - AnduinPt1 H1",
"Legion - AnduinPt1 H2",
"Legion - AnduinPt2 B",
"Legion - AnduinPt2 C",
"Legion - AnduinPt2 H",
"Legion - AsSoonAsPret A",
"Legion - AsSoonAsPret B",
"Legion - AsSoonAsPret H",
"Legion - BalloonRide Stinger 01",
"Legion - CanticleofSacrifice A",
"Legion - CanticleofSacrifice B",
"Legion - CanticleofSacrifice C",
"Legion - CanticleofSacrifice D",
"Legion - CanticleofSacrifice E",
"Legion - CanticleofSacrifice F",
"Legion - CanticleofSacrifice H",
"Legion - ClientScene 70 IF1 01",
"Legion - ClientScene 70 IF2 01",
"Legion - ClientScene 70 IF3 01",
"Legion - ClientScene MAW Intro Moment",
"Legion - DalaranDawn A",
"Legion - DalaranDawn B",
"Legion - DalaranDawn H",
"Legion - DalaranDusk A",
"Legion - DalaranDusk B",
"Legion - DalaranDusk C",
"Legion - DalaranDusk H",
"Legion - DalaranHalls1 A",
"Legion - DalaranHalls1 B",
"Legion - DalaranHalls1 C",
"Legion - DalaranHalls1 H",
"Legion - DalaranHalls2 A",
"Legion - DalaranHalls2 B",
"Legion - DalaranHalls2 H",
"Legion - DalaranJaina A",
"Legion - DalaranJaina B",
"Legion - DalaranJaina C",
"Legion - DalaranJaina H",
"Legion - DalaranKhadgar Day A",
"Legion - DalaranKhadgar Day B",
"Legion - DalaranKhadgar Day C",
"Legion - DalaranKhadgar Day H",
"Legion - DalaranKhadgar Night A",
"Legion - DalaranKhadgar Night B",
"Legion - DalaranKhadgar Night C",
"Legion - DalaranKhadgar Night H",
"Legion - DalaranSewers1 A",
"Legion - DalaranSewers1 B",
"Legion - DalaranSewers1 C",
"Legion - DalaranSewers1 H",
"Legion - DalaranSewers2 A",
"Legion - DalaranSewers2 B",
"Legion - DalaranSewers2 H",
"Legion - DemonHunterPt1 B",
"Legion - DemonHunterPt1 C",
"Legion - DemonHunterPt1 D",
"Legion - DemonHunterPt1 H",
"Legion - DemonHunterPt2 A",
"Legion - DemonHunterPt2 B1",
"Legion - DemonHunterPt2 B2",
"Legion - DemonHunterPt2 C",
"Legion - DemonHunterPt2 H",
"Legion - DemonHunterPt3 A",
"Legion - DemonHunterPt3 B",
"Legion - DemonHunterPt3 C",
"Legion - DemonHunterPt3 D",
"Legion - DemonHunterPt3 H",
"Legion - EmeraldNightmareOrch A",
"Legion - EmeraldNightmareOrch B",
"Legion - EmeraldNightmareOrch H",
"Legion - EmeraldNightmareSyn A",
"Legion - EmeraldNightmareSyn H",
"Legion - EmeraldNightmare C",
"Legion - EmeraldNightmare D",
"Legion - EmeraldNightmare E",
"Legion - EmeraldNightmare F",
"Legion - EmeraldNightmare G",
"Legion - EmeraldNightmare J",
"Legion - EmeraldNightmare K",
"Legion - EmeraldNightmare L",
"Legion - EmeraldNightmare M",
"Legion - EnchantedNightElves A",
"Legion - EnchantedNightElves B",
"Legion - EnchantedNightElves C",
"Legion - EnchantedNightElves H",
"Legion - EnrapturedWoodlands A",
"Legion - EnrapturedWoodlands B",
"Legion - EnrapturedWoodlands C",
"Legion - EnrapturedWoodlands H",
"Legion - FelGlade A",
"Legion - FelGlade B",
"Legion - FelGlade C",
"Legion - FelGlade H",
"Legion - Glimmer A",
"Legion - Glimmer H",
"Legion - HighElfTomb A",
"Legion - HighElfTomb H1",
"Legion - HighElfTomb H2",
"Legion - HighMountain10 A",
"Legion - HighMountain10 B",
"Legion - HighMountain10 H",
"Legion - HighMountain10 Stinger 01",
"Legion - HighMountain1 A",
"Legion - HighMountain1 B",
"Legion - HighMountain1 H",
"Legion - HighMountain2 A",
"Legion - HighMountain2 B",
"Legion - HighMountain2 H",
"Legion - HighMountain3 A",
"Legion - HighMountain3 B",
"Legion - HighMountain3 H",
"Legion - HighMountain4 A",
"Legion - HighMountain4 B",
"Legion - HighMountain4 H",
"Legion - HighMountain5 A",
"Legion - HighMountain5 B",
"Legion - HighMountain5 H",
"Legion - HighMountain6 A",
"Legion - HighMountain6 B",
"Legion - HighMountain6 H",
"Legion - HighMountain7 A",
"Legion - HighMountain7 B",
"Legion - HighMountain7 H",
"Legion - HighMountain8 A",
"Legion - HighMountain8 B",
"Legion - HighMountain8 H",
"Legion - HighMountain9 A",
"Legion - HighMountain9 H",
"Legion - HolyWarriorsGather A",
"Legion - HolyWarriorsGather B",
"Legion - HolyWarriorsGather C",
"Legion - HolyWarriorsGather H",
"Legion - HolyWarriorsOath A",
"Legion - HolyWarriorsOath B",
"Legion - HolyWarriorsOath C",
"Legion - HolyWarriorsOath D",
"Legion - HolyWarriorsOath E",
"Legion - HolyWarriorsOath F",
"Legion - HolyWarriorsOath G",
"Legion - HolyWarriorsOath H",
"Legion - Invincible Stinger 01",
"Legion - Kingdomswillburn MainTitle",
"Legion - LailaDemon A",
"Legion - LailaDemon B",
"Legion - LailaDemon C",
"Legion - LailaDemon D1",
"Legion - LailaDemon D2",
"Legion - LailaDemon H",
"Legion - LastStand A",
"Legion - LastStand B",
"Legion - LastStand C",
"Legion - LastStand D",
"Legion - LastStand E",
"Legion - LastStand F",
"Legion - LastStand H1",
"Legion - LastStand H1 Stinger 01",
"Legion - LastStand H2",
"Legion - LastStand H3End",
"Legion - LastStand H3 Stinger 01",
"Legion - LeyLines A",
"Legion - LeyLines B",
"Legion - LeyLines C",
"Legion - LeyLines H",
"Legion - MenaceoftheDarkTitans A",
"Legion - MenaceoftheDarkTitans B",
"Legion - MenaceoftheDarkTitans C",
"Legion - MenaceoftheDarkTitans H1",
"Legion - MenaceoftheDarkTitans H2",
"Legion - Mire1 H",
"Legion - Mire2 H",
"Legion - Mire3 H",
"Legion - Mire4 H",
"Legion - Mire5 H",
"Legion - MoonRising A",
"Legion - MoonRising B",
"Legion - MoonRising C",
"Legion - MoonRising H",
"Legion - MylunesMelody Full",
"Legion - NosSharah A",
"Legion - NosSharah B",
"Legion - NosSharah C",
"Legion - NosSharah D",
"Legion - NosSharah E",
"Legion - NosSharah H",
"Legion - OrderHallDevotions A",
"Legion - OrderHallDevotions B",
"Legion - OrderHallDevotions C",
"Legion - OrderHallDevotions D",
"Legion - OrderHallDevotions E",
"Legion - OrderHallDevotions F",
"Legion - OrderHallDevotions H",
"Legion - Passage A1",
"Legion - Passage A2",
"Legion - Passage B",
"Legion - Passage C",
"Legion - Passage D",
"Legion - Passage H1",
"Legion - Passage H2",
"Legion - Preserver H1",
"Legion - Preserver H2",
"Legion - Preserver H3End",
"Legion - Relentless A",
"Legion - Relentless B",
"Legion - Relentless C",
"Legion - Relentless D",
"Legion - Relentless E",
"Legion - Relentless F",
"Legion - Relentless G",
"Legion - Relentless H",
"Legion - Relentless J",
"Legion - RequiemfortheLostCities A",
"Legion - RequiemfortheLostCities B",
"Legion - RequiemfortheLostCities C",
"Legion - RequiemfortheLostCities D",
"Legion - RequiemfortheLostCities E",
"Legion - RequiemfortheLostCities F",
"Legion - RequiemfortheLostCities G",
"Legion - RequiemfortheLostCities H1",
"Legion - RequiemfortheLostCities H2",
"Legion - RequiemfortheLostCities H3End",
"Legion - Rose A",
"Legion - Rose H",
"Legion - RuinsOfAuberdine 01 Stinger 01",
"Legion - SacredStone A",
"Legion - SacredStone B",
"Legion - SacredStone H",
"Legion - SanctumofKarazhan H1",
"Legion - SanctumofKarazhan H2",
"Legion - Stormheim A",
"Legion - Stormheim B1",
"Legion - Stormheim B2",
"Legion - Stormheim C",
"Legion - Stormheim D",
"Legion - Stormheim E",
"Legion - Stormheim F",
"Legion - Stormheim G",
"Legion - Stormheim H",
"Legion - Suramar Pt1 A",
"Legion - Suramar pt1 b",
"Legion - Suramar Pt1 H",
"Legion - Suramar pt2 a",
"Legion - Suramar pt2 b",
"Legion - Suramar Pt2 H",
"Legion - Tempest A",
"Legion - Tempest B",
"Legion - Tempest B Stinger 01",
"Legion - Tempest C",
"Legion - Tempest D",
"Legion - Tempest E",
"Legion - Tempest F",
"Legion - Tempest G",
"Legion - Tempest H1",
"Legion - Tempest H2",
"Legion - Totems H",
"Legion - TourneyBAttle06 Stinger 01",
"Legion - WeAreNotAlone A",
"Legion - WeAreNotAlone B",
"Legion - WeAreNotAlone H",
"Legion - Weep Flute",
"Legion - Weep Horn",
"Legion - Weep Viola",
"Legion - Weep WW",
"Legion - WindsOutoftheEast A",
"Legion - WindsOutoftheEast H"
}
